/* config.c generated by valac 0.13.1.44-726e, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define version_string "valabind 0.4.5 - pancake@nopcode.org"



