/* config.c generated by valac 0.14.0.17-9c67, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define version_string "valabind 0.5.1 - pancake@nopcode.org"



