/* cxxwriter.c generated by valac 0.13.1.44-726e, the Vala compiler
 * generated from cxxwriter.vala, do not modify */

/* Copyleft 2009-2011 -- pancake // nopcode.org */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <valagee.h>


#define TYPE_CXX_WRITER (cxx_writer_get_type ())
#define CXX_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CXX_WRITER, CxxWriter))
#define CXX_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CXX_WRITER, CxxWriterClass))
#define IS_CXX_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CXX_WRITER))
#define IS_CXX_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CXX_WRITER))
#define CXX_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CXX_WRITER, CxxWriterClass))

typedef struct _CxxWriter CxxWriter;
typedef struct _CxxWriterClass CxxWriterClass;
typedef struct _CxxWriterPrivate CxxWriterPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define __g_list_free__vala_code_node_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__vala_code_node_unref0_ (var), NULL)))
#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_source_reference_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_reference_unref (var), NULL)))

struct _CxxWriter {
	ValaCodeVisitor parent_instance;
	CxxWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gboolean show_externs;
	gboolean glib_mode;
	gboolean cxx_mode;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _CxxWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _CxxWriterPrivate {
	ValaCodeContext* context;
	FILE* stream;
	gchar* classname;
	gchar* classcname;
	gchar* externs;
	gchar* statics;
	gchar* extends;
	gchar* enums;
	gchar* vectors;
	gchar* nspace;
	gchar* modulename;
	GHashTable* defined_classes;
};


static gpointer cxx_writer_parent_class = NULL;

GType cxx_writer_get_type (void) G_GNUC_CONST;
#define CXX_WRITER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CXX_WRITER, CxxWriterPrivate))
enum  {
	CXX_WRITER_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
static void _vala_code_node_unref0_ (gpointer var);
static void _g_list_free__vala_code_node_unref0_ (GList* self);
CxxWriter* cxx_writer_new (const gchar* name);
CxxWriter* cxx_writer_construct (GType object_type, const gchar* name);
static gchar* cxx_writer_get_alias (CxxWriter* self, const gchar* name);
void valabind_compiler_warning (const gchar* msg);
static gchar* cxx_writer_get_ctype (CxxWriter* self, const gchar* _type);
void valabind_compiler_error (const gchar* msg);
static inline gboolean cxx_writer_is_generic (CxxWriter* self, const gchar* type);
static gboolean cxx_writer_is_target_file (CxxWriter* self, const gchar* path);
static void cxx_writer_real_visit_source_file (ValaCodeVisitor* base, ValaSourceFile* source);
void cxx_writer_process_includes (CxxWriter* self, ValaSymbol* s);
void cxx_writer_walk_field (CxxWriter* self, ValaField* f);
void cxx_writer_walk_class (CxxWriter* self, const gchar* pfx, ValaClass* c);
void cxx_writer_walk_enum (CxxWriter* self, ValaEnum* e);
void cxx_writer_walk_method (CxxWriter* self, ValaMethod* m);
static void cxx_writer_real_visit_namespace (ValaCodeVisitor* base, ValaNamespace* ns);
void cxx_writer_write_file (CxxWriter* self, ValaCodeContext* context, const gchar* filename);
static void cxx_writer_finalize (ValaCodeVisitor* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


static void _vala_code_node_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL));
}


static void _g_list_free__vala_code_node_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _vala_code_node_unref0_, NULL);
	g_list_free (self);
}


CxxWriter* cxx_writer_construct (GType object_type, const gchar* name) {
	CxxWriter* self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_val_if_fail (name != NULL, NULL);
	self = (CxxWriter*) vala_code_visitor_construct (object_type);
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->enums);
	self->priv->enums = _tmp0_;
	_tmp1_ = g_strdup ("");
	_g_free0 (self->priv->statics);
	self->priv->statics = _tmp1_;
	_tmp2_ = g_strdup ("");
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp2_;
	_tmp3_ = g_strdup ("");
	_g_free0 (self->priv->extends);
	self->priv->extends = _tmp3_;
	_tmp4_ = g_strdup ("");
	_g_free0 (self->priv->vectors);
	self->priv->vectors = _tmp4_;
	_tmp5_ = g_strdup ("");
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp5_;
	_tmp6_ = name;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->priv->modulename);
	self->priv->modulename = _tmp7_;
	__g_list_free__g_free0_0 (self->includefiles);
	self->includefiles = NULL;
	return self;
}


CxxWriter* cxx_writer_new (const gchar* name) {
	return cxx_writer_construct (TYPE_CXX_WRITER, name);
}


static gchar* cxx_writer_get_alias (CxxWriter* self, const gchar* name) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* oname;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GQuark _tmp5_ = 0U;
	static GQuark _tmp4_label0 = 0;
	static GQuark _tmp4_label1 = 0;
	static GQuark _tmp4_label2 = 0;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	oname = _tmp1_;
	_tmp2_ = name;
	_tmp3_ = _tmp2_;
	_tmp5_ = (NULL == _tmp3_) ? 0 : g_quark_from_string (_tmp3_);
	if (((_tmp5_ == ((0 != _tmp4_label0) ? _tmp4_label0 : (_tmp4_label0 = g_quark_from_static_string ("break")))) || (_tmp5_ == ((0 != _tmp4_label1) ? _tmp4_label1 : (_tmp4_label1 = g_quark_from_static_string ("print"))))) || (_tmp5_ == ((0 != _tmp4_label2) ? _tmp4_label2 : (_tmp4_label2 = g_quark_from_static_string ("continue"))))) {
		switch (0) {
			default:
			{
				const gchar* _tmp6_;
				gchar* _tmp7_;
				_tmp6_ = name;
				_tmp7_ = g_strconcat ("_", _tmp6_, NULL);
				result = _tmp7_;
				_g_free0 (oname);
				return result;
			}
		}
	}
	_tmp8_ = name;
	_tmp9_ = oname;
	if (g_strcmp0 (_tmp8_, _tmp9_) != 0) {
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_;
		_tmp10_ = self->priv->classname;
		_tmp11_ = oname;
		_tmp12_ = self->priv->classname;
		_tmp13_ = name;
		_tmp14_ = g_strdup_printf ("%s.%s method renamed to %s.%s", _tmp10_, _tmp11_, _tmp12_, _tmp13_);
		_tmp15_ = _tmp14_;
		valabind_compiler_warning (_tmp15_);
		_g_free0 (_tmp15_);
	}
	_tmp16_ = name;
	_tmp17_ = g_strdup (_tmp16_);
	result = _tmp17_;
	_g_free0 (oname);
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_ = 0;
		gint _tmp8_;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_;
		glong _tmp14_;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_;
		glong _tmp17_;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		const gchar* _tmp9_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch4_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch4_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp8_;
		result = _tmp9_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally4;
	__catch4_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally4:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _result_;
	gchar* _tmp3_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_;
	glong string_length;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static gchar* cxx_writer_get_ctype (CxxWriter* self, const gchar* _type) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* type;
	gchar* iter_type;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	const gchar* _tmp13_;
	gchar* _tmp14_ = NULL;
	const gchar* _tmp15_;
	gboolean _tmp16_ = FALSE;
	const gchar* _tmp43_;
	gchar* _tmp44_ = NULL;
	const gchar* _tmp45_;
	const gchar* _tmp46_;
	GQuark _tmp48_ = 0U;
	static GQuark _tmp47_label0 = 0;
	static GQuark _tmp47_label1 = 0;
	static GQuark _tmp47_label2 = 0;
	static GQuark _tmp47_label3 = 0;
	static GQuark _tmp47_label4 = 0;
	static GQuark _tmp47_label5 = 0;
	static GQuark _tmp47_label6 = 0;
	static GQuark _tmp47_label7 = 0;
	static GQuark _tmp47_label8 = 0;
	static GQuark _tmp47_label9 = 0;
	static GQuark _tmp47_label10 = 0;
	static GQuark _tmp47_label11 = 0;
	static GQuark _tmp47_label12 = 0;
	static GQuark _tmp47_label13 = 0;
	static GQuark _tmp47_label14 = 0;
	static GQuark _tmp47_label15 = 0;
	static GQuark _tmp47_label16 = 0;
	static GQuark _tmp47_label17 = 0;
	static GQuark _tmp47_label18 = 0;
	static GQuark _tmp47_label19 = 0;
	static GQuark _tmp47_label20 = 0;
	static GQuark _tmp47_label21 = 0;
	static GQuark _tmp47_label22 = 0;
	static GQuark _tmp47_label23 = 0;
	static GQuark _tmp47_label24 = 0;
	static GQuark _tmp47_label25 = 0;
	static GQuark _tmp47_label26 = 0;
	static GQuark _tmp47_label27 = 0;
	static GQuark _tmp47_label28 = 0;
	static GQuark _tmp47_label29 = 0;
	static GQuark _tmp47_label30 = 0;
	static GQuark _tmp47_label31 = 0;
	const gchar* _tmp77_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (_type != NULL, NULL);
	_tmp0_ = _type;
	_tmp1_ = g_strdup (_tmp0_);
	type = _tmp1_;
	iter_type = NULL;
	_tmp2_ = type;
	if (g_strcmp0 (_tmp2_, "null") == 0) {
		valabind_compiler_error ("Cannot resolve type");
	}
	_tmp3_ = type;
	_tmp4_ = self->priv->nspace;
	_tmp5_ = g_str_has_prefix (_tmp3_, _tmp4_);
	if (_tmp5_) {
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		gint _tmp8_ = 0;
		gint _tmp9_;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_;
		gchar* _tmp12_;
		_tmp6_ = type;
		_tmp7_ = self->priv->nspace;
		_tmp8_ = strlen (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = string_substring (_tmp6_, (glong) _tmp9_, (glong) (-1));
		_tmp11_ = _tmp10_;
		_tmp12_ = g_strconcat (_tmp11_, "*", NULL);
		_g_free0 (type);
		type = _tmp12_;
		_g_free0 (_tmp11_);
	}
	_tmp13_ = type;
	_tmp14_ = string_replace (_tmp13_, ".", "");
	_g_free0 (type);
	type = _tmp14_;
	_tmp15_ = type;
	_tmp16_ = cxx_writer_is_generic (self, _tmp15_);
	if (_tmp16_) {
		const gchar* _tmp17_;
		gint _tmp18_ = 0;
		gint ptr;
		gchar* _tmp19_ = NULL;
		gint _tmp20_;
		const gchar* _tmp29_;
		gchar* _tmp30_;
		const gchar* _tmp31_;
		gchar* _tmp32_ = NULL;
		const gchar* _tmp33_;
		gchar* _tmp34_ = NULL;
		const gchar* _tmp35_;
		const gchar* _tmp36_;
		gchar* _tmp37_ = NULL;
		const gchar* _tmp38_;
		gchar** _tmp39_;
		gchar** _tmp40_ = NULL;
		gchar** _tmp41_;
		gint _tmp41__length1;
		gchar* _tmp42_;
		_tmp17_ = type;
		_tmp18_ = string_index_of (_tmp17_, "<", 0);
		ptr = _tmp18_;
		_tmp20_ = ptr;
		if (_tmp20_ == (-1)) {
			const gchar* _tmp21_;
			gchar* _tmp22_;
			_tmp21_ = type;
			_tmp22_ = g_strdup (_tmp21_);
			_g_free0 (_tmp19_);
			_tmp19_ = _tmp22_;
		} else {
			const gchar* _tmp23_;
			gint _tmp24_;
			const gchar* _tmp25_;
			gint _tmp26_ = 0;
			gint _tmp27_;
			gchar* _tmp28_ = NULL;
			_tmp23_ = type;
			_tmp24_ = ptr;
			_tmp25_ = type;
			_tmp26_ = strlen (_tmp25_);
			_tmp27_ = _tmp26_;
			_tmp28_ = string_slice (_tmp23_, (glong) _tmp24_, (glong) _tmp27_);
			_g_free0 (_tmp19_);
			_tmp19_ = _tmp28_;
		}
		_tmp29_ = _tmp19_;
		_tmp30_ = g_strdup (_tmp29_);
		_g_free0 (iter_type);
		iter_type = _tmp30_;
		_tmp31_ = iter_type;
		_tmp32_ = string_replace (_tmp31_, "<", "");
		_g_free0 (iter_type);
		iter_type = _tmp32_;
		_tmp33_ = iter_type;
		_tmp34_ = string_replace (_tmp33_, ">", "");
		_g_free0 (iter_type);
		iter_type = _tmp34_;
		_tmp35_ = iter_type;
		_tmp36_ = self->priv->nspace;
		_tmp37_ = string_replace (_tmp35_, _tmp36_, "");
		_g_free0 (iter_type);
		iter_type = _tmp37_;
		_tmp38_ = type;
		_tmp40_ = _tmp39_ = g_strsplit (_tmp38_, "<", 2);
		_tmp41_ = _tmp40_;
		_tmp41__length1 = _vala_array_length (_tmp39_);
		_tmp42_ = g_strdup (_tmp41_[0]);
		_g_free0 (type);
		type = _tmp42_;
		_tmp41_ = (_vala_array_free (_tmp41_, _tmp41__length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (_tmp19_);
	}
	_tmp43_ = type;
	_tmp44_ = string_replace (_tmp43_, "?", "");
	_g_free0 (type);
	type = _tmp44_;
	_tmp45_ = type;
	_tmp46_ = _tmp45_;
	_tmp48_ = (NULL == _tmp46_) ? 0 : g_quark_from_string (_tmp46_);
	if (_tmp48_ == ((0 != _tmp47_label0) ? _tmp47_label0 : (_tmp47_label0 = g_quark_from_static_string ("const gchar*")))) {
		switch (0) {
			default:
			{
				gchar* _tmp49_;
				_tmp49_ = g_strdup ("const char*");
				result = _tmp49_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label1) ? _tmp47_label1 : (_tmp47_label1 = g_quark_from_static_string ("G")))) || (_tmp48_ == ((0 != _tmp47_label2) ? _tmp47_label2 : (_tmp47_label2 = g_quark_from_static_string ("gconstpointer"))))) || (_tmp48_ == ((0 != _tmp47_label3) ? _tmp47_label3 : (_tmp47_label3 = g_quark_from_static_string ("gpointer"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp50_;
				_tmp50_ = g_strdup ("void*");
				result = _tmp50_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label4) ? _tmp47_label4 : (_tmp47_label4 = g_quark_from_static_string ("gdouble")))) {
		switch (0) {
			default:
			{
				gchar* _tmp51_;
				_tmp51_ = g_strdup ("double");
				result = _tmp51_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label5) ? _tmp47_label5 : (_tmp47_label5 = g_quark_from_static_string ("gfloat")))) {
		switch (0) {
			default:
			{
				gchar* _tmp52_;
				_tmp52_ = g_strdup ("float");
				result = _tmp52_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label6) ? _tmp47_label6 : (_tmp47_label6 = g_quark_from_static_string ("ut8")))) || (_tmp48_ == ((0 != _tmp47_label7) ? _tmp47_label7 : (_tmp47_label7 = g_quark_from_static_string ("uint8"))))) || (_tmp48_ == ((0 != _tmp47_label8) ? _tmp47_label8 : (_tmp47_label8 = g_quark_from_static_string ("guint8"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp53_;
				_tmp53_ = g_strdup ("unsigned char");
				result = _tmp53_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label9) ? _tmp47_label9 : (_tmp47_label9 = g_quark_from_static_string ("gchar**")))) {
		switch (0) {
			default:
			{
				gchar* _tmp54_;
				_tmp54_ = g_strdup ("char **");
				result = _tmp54_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label10) ? _tmp47_label10 : (_tmp47_label10 = g_quark_from_static_string ("gchar")))) {
		switch (0) {
			default:
			{
				gchar* _tmp55_;
				_tmp55_ = g_strdup ("char");
				result = _tmp55_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label11) ? _tmp47_label11 : (_tmp47_label11 = g_quark_from_static_string ("gchar*")))) || (_tmp48_ == ((0 != _tmp47_label12) ? _tmp47_label12 : (_tmp47_label12 = g_quark_from_static_string ("string"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp56_;
				_tmp56_ = g_strdup ("char *");
				result = _tmp56_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label13) ? _tmp47_label13 : (_tmp47_label13 = g_quark_from_static_string ("gint")))) {
		switch (0) {
			default:
			{
				gchar* _tmp57_;
				_tmp57_ = g_strdup ("int");
				result = _tmp57_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label14) ? _tmp47_label14 : (_tmp47_label14 = g_quark_from_static_string ("glong")))) {
		switch (0) {
			default:
			{
				gchar* _tmp58_;
				_tmp58_ = g_strdup ("long");
				result = _tmp58_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label15) ? _tmp47_label15 : (_tmp47_label15 = g_quark_from_static_string ("st64")))) || (_tmp48_ == ((0 != _tmp47_label16) ? _tmp47_label16 : (_tmp47_label16 = g_quark_from_static_string ("int64"))))) || (_tmp48_ == ((0 != _tmp47_label17) ? _tmp47_label17 : (_tmp47_label17 = g_quark_from_static_string ("gint64"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp59_;
				_tmp59_ = g_strdup ("long long");
				result = _tmp59_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label18) ? _tmp47_label18 : (_tmp47_label18 = g_quark_from_static_string ("ut64")))) || (_tmp48_ == ((0 != _tmp47_label19) ? _tmp47_label19 : (_tmp47_label19 = g_quark_from_static_string ("uint64"))))) || (_tmp48_ == ((0 != _tmp47_label20) ? _tmp47_label20 : (_tmp47_label20 = g_quark_from_static_string ("guint64"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp60_;
				_tmp60_ = g_strdup ("unsigned long long");
				result = _tmp60_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label21) ? _tmp47_label21 : (_tmp47_label21 = g_quark_from_static_string ("uint8*")))) || (_tmp48_ == ((0 != _tmp47_label22) ? _tmp47_label22 : (_tmp47_label22 = g_quark_from_static_string ("guint8*"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp61_;
				_tmp61_ = g_strdup ("unsigned char*");
				result = _tmp61_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label23) ? _tmp47_label23 : (_tmp47_label23 = g_quark_from_static_string ("guint16")))) || (_tmp48_ == ((0 != _tmp47_label24) ? _tmp47_label24 : (_tmp47_label24 = g_quark_from_static_string ("uint16"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp62_;
				_tmp62_ = g_strdup ("unsigned short");
				result = _tmp62_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label25) ? _tmp47_label25 : (_tmp47_label25 = g_quark_from_static_string ("ut32")))) || (_tmp48_ == ((0 != _tmp47_label26) ? _tmp47_label26 : (_tmp47_label26 = g_quark_from_static_string ("uint32"))))) || (_tmp48_ == ((0 != _tmp47_label27) ? _tmp47_label27 : (_tmp47_label27 = g_quark_from_static_string ("guint32"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp63_;
				_tmp63_ = g_strdup ("unsigned int");
				result = _tmp63_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label28) ? _tmp47_label28 : (_tmp47_label28 = g_quark_from_static_string ("bool")))) || (_tmp48_ == ((0 != _tmp47_label29) ? _tmp47_label29 : (_tmp47_label29 = g_quark_from_static_string ("gboolean"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp64_;
				_tmp64_ = g_strdup ("bool");
				result = _tmp64_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label30) ? _tmp47_label30 : (_tmp47_label30 = g_quark_from_static_string ("RFList")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp65_;
				_tmp65_ = iter_type;
				if (_tmp65_ != NULL) {
					const gchar* _tmp66_;
					gchar* _tmp67_;
					gchar* _tmp68_;
					gchar* _tmp69_;
					gchar* _tmp70_;
					_tmp66_ = iter_type;
					_tmp67_ = g_strconcat ("std::vector<", _tmp66_, NULL);
					_tmp68_ = _tmp67_;
					_tmp69_ = g_strconcat (_tmp68_, ">", NULL);
					_tmp70_ = _tmp69_;
					_g_free0 (_tmp68_);
					result = _tmp70_;
					_g_free0 (iter_type);
					_g_free0 (type);
					return result;
				}
				break;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label31) ? _tmp47_label31 : (_tmp47_label31 = g_quark_from_static_string ("RList")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp71_;
				_tmp71_ = iter_type;
				if (_tmp71_ != NULL) {
					const gchar* _tmp72_;
					gchar* _tmp73_;
					gchar* _tmp74_;
					gchar* _tmp75_;
					gchar* _tmp76_;
					_tmp72_ = iter_type;
					_tmp73_ = g_strconcat ("std::vector<", _tmp72_, NULL);
					_tmp74_ = _tmp73_;
					_tmp75_ = g_strconcat (_tmp74_, ">", NULL);
					_tmp76_ = _tmp75_;
					_g_free0 (_tmp74_);
					result = _tmp76_;
					_g_free0 (iter_type);
					_g_free0 (type);
					return result;
				}
				break;
			}
		}
	}
	_tmp77_ = type;
	result = _tmp77_;
	_g_free0 (iter_type);
	return result;
}


static gboolean cxx_writer_is_target_file (CxxWriter* self, const gchar* path) {
	gboolean result = FALSE;
	gchar** _tmp0_;
	gint _tmp0__length1;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	_tmp0_ = self->files;
	_tmp0__length1 = self->files_length1;
	{
		gchar** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
		file_collection = _tmp0_;
		file_collection_length1 = _tmp0__length1;
		for (file_it = 0; file_it < _tmp0__length1; file_it = file_it + 1) {
			gchar* _tmp1_;
			gchar* file = NULL;
			_tmp1_ = g_strdup (file_collection[file_it]);
			file = _tmp1_;
			{
				const gchar* _tmp2_;
				const gchar* _tmp3_;
				_tmp2_ = file;
				_tmp3_ = path;
				if (g_strcmp0 (_tmp2_, _tmp3_) == 0) {
					result = TRUE;
					_g_free0 (file);
					return result;
				}
				_g_free0 (file);
			}
		}
	}
	result = FALSE;
	return result;
}


static void cxx_writer_real_visit_source_file (ValaCodeVisitor* base, ValaSourceFile* source) {
	CxxWriter * self;
	ValaSourceFile* _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_;
	gboolean _tmp3_ = FALSE;
	self = (CxxWriter*) base;
	g_return_if_fail (source != NULL);
	_tmp0_ = source;
	_tmp1_ = vala_source_file_get_filename (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = cxx_writer_is_target_file (self, _tmp2_);
	if (_tmp3_) {
		ValaSourceFile* _tmp4_;
		_tmp4_ = source;
		vala_source_file_accept_children (_tmp4_, (ValaCodeVisitor*) self);
	}
}


void cxx_writer_process_includes (CxxWriter* self, ValaSymbol* s) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (s != NULL);
	{
		ValaSymbol* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _foo_list;
		ValaList* _tmp2_;
		gint _tmp3_ = 0;
		gint _tmp4_;
		gint _foo_size;
		gint _foo_index;
		_tmp0_ = s;
		_tmp1_ = vala_symbol_get_cheader_filenames (_tmp0_);
		_foo_list = _tmp1_;
		_tmp2_ = _foo_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_foo_size = _tmp4_;
		_foo_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			gchar* foo;
			gboolean include;
			GList* _tmp11_;
			gboolean _tmp15_;
			_tmp5_ = _foo_index;
			_foo_index = _tmp5_ + 1;
			_tmp6_ = _foo_index;
			_tmp7_ = _foo_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _foo_list;
			_tmp9_ = _foo_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			foo = (gchar*) _tmp10_;
			include = TRUE;
			_tmp11_ = self->includefiles;
			{
				GList* inc_collection = NULL;
				GList* inc_it = NULL;
				inc_collection = _tmp11_;
				for (inc_it = inc_collection; inc_it != NULL; inc_it = inc_it->next) {
					gchar* _tmp12_;
					gchar* inc = NULL;
					_tmp12_ = g_strdup ((const gchar*) inc_it->data);
					inc = _tmp12_;
					{
						const gchar* _tmp13_;
						const gchar* _tmp14_;
						_tmp13_ = inc;
						_tmp14_ = foo;
						if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
							include = FALSE;
							_g_free0 (inc);
							break;
						}
						_g_free0 (inc);
					}
				}
			}
			_tmp15_ = include;
			if (_tmp15_) {
				const gchar* _tmp16_;
				gchar* _tmp17_;
				_tmp16_ = foo;
				_tmp17_ = g_strdup (_tmp16_);
				self->includefiles = g_list_prepend (self->includefiles, _tmp17_);
			}
			_g_free0 (foo);
		}
		_vala_iterable_unref0 (_foo_list);
	}
}


void cxx_writer_walk_field (CxxWriter* self, ValaField* f) {
	ValaField* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	gboolean _tmp3_;
	ValaField* _tmp9_;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (f != NULL);
	_tmp0_ = f;
	_tmp1_ = vala_field_get_ctype (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_ == NULL;
	_g_free0 (_tmp2_);
	if (_tmp3_) {
	} else {
		ValaField* _tmp4_;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp4_ = f;
		_tmp5_ = vala_field_get_cname (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_strdup_printf ("Type for %s\n", _tmp6_);
		_tmp8_ = _tmp7_;
		valabind_compiler_warning (_tmp8_);
		_g_free0 (_tmp8_);
		_g_free0 (_tmp6_);
	}
	_tmp9_ = f;
	_tmp10_ = vala_variable_get_no_array_length ((ValaVariable*) _tmp9_);
	_tmp11_ = _tmp10_;
	if (_tmp11_) {
		g_print ("---> array without length\n");
	}
}


void cxx_writer_walk_class (CxxWriter* self, const gchar* pfx, ValaClass* c) {
	const gchar* _tmp15_;
	ValaClass* _tmp16_;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	ValaClass* _tmp20_;
	gchar* _tmp21_ = NULL;
	ValaClass* _tmp22_;
	gboolean has_constructor;
	ValaClass* _tmp35_;
	gboolean _tmp36_ = FALSE;
	gboolean _tmp37_;
	gboolean has_destructor;
	gboolean _tmp38_;
	GHashTable* _tmp42_;
	const gchar* _tmp43_;
	gconstpointer _tmp44_ = NULL;
	GHashTable* _tmp45_;
	const gchar* _tmp46_;
	gchar* _tmp47_;
	gboolean _tmp48_;
	const gchar* _tmp61_;
	const gchar* _tmp62_;
	gchar* _tmp63_ = NULL;
	gchar* _tmp64_;
	gchar* _tmp65_;
	const gchar* _tmp66_;
	gchar* _tmp67_;
	gboolean _tmp92_ = FALSE;
	gboolean _tmp93_;
	gboolean _tmp95_;
	const gchar* _tmp130_;
	gchar* _tmp131_;
	gchar* _tmp132_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (pfx != NULL);
	g_return_if_fail (c != NULL);
	{
		ValaClass* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _k_list;
		ValaList* _tmp2_;
		gint _tmp3_ = 0;
		gint _tmp4_;
		gint _k_size;
		gint _k_index;
		_tmp0_ = c;
		_tmp1_ = vala_class_get_classes (_tmp0_);
		_k_list = _tmp1_;
		_tmp2_ = _k_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_k_size = _tmp4_;
		_k_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ValaClass* k;
			ValaClass* _tmp11_;
			const gchar* _tmp12_ = NULL;
			const gchar* _tmp13_;
			ValaClass* _tmp14_;
			_tmp5_ = _k_index;
			_k_index = _tmp5_ + 1;
			_tmp6_ = _k_index;
			_tmp7_ = _k_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _k_list;
			_tmp9_ = _k_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			k = (ValaClass*) _tmp10_;
			_tmp11_ = c;
			_tmp12_ = vala_symbol_get_name ((ValaSymbol*) _tmp11_);
			_tmp13_ = _tmp12_;
			_tmp14_ = k;
			cxx_writer_walk_class (self, _tmp13_, _tmp14_);
			_vala_code_node_unref0 (k);
		}
		_vala_iterable_unref0 (_k_list);
	}
	_tmp15_ = pfx;
	_tmp16_ = c;
	_tmp17_ = vala_symbol_get_name ((ValaSymbol*) _tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp15_, _tmp18_, NULL);
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp19_;
	_tmp20_ = c;
	_tmp21_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) _tmp20_, FALSE);
	_g_free0 (self->priv->classcname);
	self->priv->classcname = _tmp21_;
	_tmp22_ = c;
	cxx_writer_process_includes (self, (ValaSymbol*) _tmp22_);
	has_constructor = FALSE;
	{
		ValaClass* _tmp23_;
		ValaList* _tmp24_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp25_;
		gint _tmp26_ = 0;
		gint _tmp27_;
		gint _m_size;
		gint _m_index;
		_tmp23_ = c;
		_tmp24_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) _tmp23_);
		_m_list = _tmp24_;
		_tmp25_ = _m_list;
		_tmp26_ = vala_collection_get_size ((ValaCollection*) _tmp25_);
		_tmp27_ = _tmp26_;
		_m_size = _tmp27_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp28_;
			gint _tmp29_;
			gint _tmp30_;
			ValaList* _tmp31_;
			gint _tmp32_;
			gpointer _tmp33_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp34_;
			_tmp28_ = _m_index;
			_m_index = _tmp28_ + 1;
			_tmp29_ = _m_index;
			_tmp30_ = _m_size;
			if (!(_tmp29_ < _tmp30_)) {
				break;
			}
			_tmp31_ = _m_list;
			_tmp32_ = _m_index;
			_tmp33_ = vala_list_get (_tmp31_, _tmp32_);
			m = (ValaMethod*) _tmp33_;
			_tmp34_ = m;
			if (VALA_IS_CREATION_METHOD (_tmp34_)) {
				has_constructor = TRUE;
				_vala_code_node_unref0 (m);
				break;
			}
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	_tmp35_ = c;
	_tmp36_ = vala_class_get_is_compact (_tmp35_);
	_tmp37_ = _tmp36_;
	has_destructor = !_tmp37_;
	_tmp38_ = self->glib_mode;
	if (_tmp38_) {
		const gchar* _tmp39_;
		const gchar* _tmp40_;
		gchar* _tmp41_ = NULL;
		_tmp39_ = self->priv->nspace;
		_tmp40_ = self->priv->classname;
		_tmp41_ = g_strdup_printf ("%s_%s", _tmp39_, _tmp40_);
		_g_free0 (self->priv->classname);
		self->priv->classname = _tmp41_;
	}
	_tmp42_ = self->priv->defined_classes;
	_tmp43_ = self->priv->classname;
	_tmp44_ = g_hash_table_lookup (_tmp42_, _tmp43_);
	if (GPOINTER_TO_INT (_tmp44_)) {
		return;
	}
	_tmp45_ = self->priv->defined_classes;
	_tmp46_ = self->priv->classname;
	_tmp47_ = g_strdup (_tmp46_);
	g_hash_table_insert (_tmp45_, _tmp47_, GINT_TO_POINTER (TRUE));
	_tmp48_ = self->glib_mode;
	if (_tmp48_) {
		const gchar* _tmp49_;
		const gchar* _tmp50_;
		const gchar* _tmp51_;
		gchar* _tmp52_ = NULL;
		gchar* _tmp53_;
		gchar* _tmp54_;
		_tmp49_ = self->priv->extends;
		_tmp50_ = self->priv->modulename;
		_tmp51_ = self->priv->classcname;
		_tmp52_ = g_strdup_printf ("class %s_%s {\n", _tmp50_, _tmp51_);
		_tmp53_ = _tmp52_;
		_tmp54_ = g_strconcat (_tmp49_, _tmp53_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp54_;
		_g_free0 (_tmp53_);
	} else {
		const gchar* _tmp55_;
		const gchar* _tmp56_;
		const gchar* _tmp57_;
		gchar* _tmp58_ = NULL;
		gchar* _tmp59_;
		gchar* _tmp60_;
		_tmp55_ = self->priv->extends;
		_tmp56_ = self->priv->modulename;
		_tmp57_ = self->priv->classname;
		_tmp58_ = g_strdup_printf ("class %s_%s {\n", _tmp56_, _tmp57_);
		_tmp59_ = _tmp58_;
		_tmp60_ = g_strconcat (_tmp55_, _tmp59_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp60_;
		_g_free0 (_tmp59_);
	}
	_tmp61_ = self->priv->extends;
	_tmp62_ = self->priv->classname;
	_tmp63_ = g_strdup_printf (" %s *self;\n", _tmp62_);
	_tmp64_ = _tmp63_;
	_tmp65_ = g_strconcat (_tmp61_, _tmp64_, NULL);
	_g_free0 (self->priv->extends);
	self->priv->extends = _tmp65_;
	_g_free0 (_tmp64_);
	_tmp66_ = self->priv->extends;
	_tmp67_ = g_strconcat (_tmp66_, " public:\n", NULL);
	_g_free0 (self->priv->extends);
	self->priv->extends = _tmp67_;
	{
		ValaClass* _tmp68_;
		ValaList* _tmp69_ = NULL;
		ValaList* _e_list;
		ValaList* _tmp70_;
		gint _tmp71_ = 0;
		gint _tmp72_;
		gint _e_size;
		gint _e_index;
		_tmp68_ = c;
		_tmp69_ = vala_class_get_enums (_tmp68_);
		_e_list = _tmp69_;
		_tmp70_ = _e_list;
		_tmp71_ = vala_collection_get_size ((ValaCollection*) _tmp70_);
		_tmp72_ = _tmp71_;
		_e_size = _tmp72_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp73_;
			gint _tmp74_;
			gint _tmp75_;
			ValaList* _tmp76_;
			gint _tmp77_;
			gpointer _tmp78_ = NULL;
			ValaEnum* e;
			ValaEnum* _tmp79_;
			_tmp73_ = _e_index;
			_e_index = _tmp73_ + 1;
			_tmp74_ = _e_index;
			_tmp75_ = _e_size;
			if (!(_tmp74_ < _tmp75_)) {
				break;
			}
			_tmp76_ = _e_list;
			_tmp77_ = _e_index;
			_tmp78_ = vala_list_get (_tmp76_, _tmp77_);
			e = (ValaEnum*) _tmp78_;
			_tmp79_ = e;
			cxx_writer_walk_enum (self, _tmp79_);
			_vala_code_node_unref0 (e);
		}
		_vala_iterable_unref0 (_e_list);
	}
	{
		ValaClass* _tmp80_;
		ValaList* _tmp81_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp82_;
		gint _tmp83_ = 0;
		gint _tmp84_;
		gint _f_size;
		gint _f_index;
		_tmp80_ = c;
		_tmp81_ = vala_class_get_fields (_tmp80_);
		_f_list = _tmp81_;
		_tmp82_ = _f_list;
		_tmp83_ = vala_collection_get_size ((ValaCollection*) _tmp82_);
		_tmp84_ = _tmp83_;
		_f_size = _tmp84_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp85_;
			gint _tmp86_;
			gint _tmp87_;
			ValaList* _tmp88_;
			gint _tmp89_;
			gpointer _tmp90_ = NULL;
			ValaField* f;
			ValaField* _tmp91_;
			_tmp85_ = _f_index;
			_f_index = _tmp85_ + 1;
			_tmp86_ = _f_index;
			_tmp87_ = _f_size;
			if (!(_tmp86_ < _tmp87_)) {
				break;
			}
			_tmp88_ = _f_list;
			_tmp89_ = _f_index;
			_tmp90_ = vala_list_get (_tmp88_, _tmp89_);
			f = (ValaField*) _tmp90_;
			_tmp91_ = f;
			cxx_writer_walk_field (self, _tmp91_);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	_tmp93_ = has_destructor;
	if (_tmp93_) {
		gboolean _tmp94_;
		_tmp94_ = has_constructor;
		_tmp92_ = _tmp94_;
	} else {
		_tmp92_ = FALSE;
	}
	_tmp95_ = _tmp92_;
	if (_tmp95_) {
		ValaClass* _tmp96_;
		gboolean _tmp97_ = FALSE;
		_tmp96_ = c;
		_tmp97_ = vala_typesymbol_is_reference_counting ((ValaTypeSymbol*) _tmp96_);
		if (_tmp97_) {
			ValaClass* _tmp98_;
			gchar* _tmp99_ = NULL;
			gchar* freefun;
			const gchar* _tmp100_;
			_tmp98_ = c;
			_tmp99_ = vala_typesymbol_get_unref_function ((ValaTypeSymbol*) _tmp98_);
			freefun = _tmp99_;
			_tmp100_ = freefun;
			if (_tmp100_ != NULL) {
				const gchar* _tmp101_;
				const gchar* _tmp102_;
				const gchar* _tmp103_;
				const gchar* _tmp104_;
				gchar* _tmp105_ = NULL;
				gchar* _tmp106_;
				gchar* _tmp107_;
				_tmp101_ = self->priv->extends;
				_tmp102_ = self->priv->modulename;
				_tmp103_ = self->priv->classname;
				_tmp104_ = freefun;
				_tmp105_ = g_strdup_printf ("  ~%s_%s() {\n    %s (self);\n  }\n", _tmp102_, _tmp103_, _tmp104_);
				_tmp106_ = _tmp105_;
				_tmp107_ = g_strconcat (_tmp101_, _tmp106_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp107_;
				_g_free0 (_tmp106_);
			}
			_g_free0 (freefun);
		} else {
			ValaClass* _tmp108_;
			gchar* _tmp109_ = NULL;
			gchar* freefun;
			const gchar* _tmp110_;
			_tmp108_ = c;
			_tmp109_ = vala_typesymbol_get_free_function ((ValaTypeSymbol*) _tmp108_);
			freefun = _tmp109_;
			_tmp110_ = freefun;
			if (_tmp110_ != NULL) {
				const gchar* _tmp111_;
				const gchar* _tmp112_;
				const gchar* _tmp113_;
				const gchar* _tmp114_;
				gchar* _tmp115_ = NULL;
				gchar* _tmp116_;
				gchar* _tmp117_;
				_tmp111_ = self->priv->extends;
				_tmp112_ = self->priv->modulename;
				_tmp113_ = self->priv->classname;
				_tmp114_ = freefun;
				_tmp115_ = g_strdup_printf ("  ~%s_%s() {\n    %s (self);\n  }\n", _tmp112_, _tmp113_, _tmp114_);
				_tmp116_ = _tmp115_;
				_tmp117_ = g_strconcat (_tmp111_, _tmp116_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp117_;
				_g_free0 (_tmp116_);
			}
			_g_free0 (freefun);
		}
	}
	{
		ValaClass* _tmp118_;
		ValaList* _tmp119_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp120_;
		gint _tmp121_ = 0;
		gint _tmp122_;
		gint _m_size;
		gint _m_index;
		_tmp118_ = c;
		_tmp119_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) _tmp118_);
		_m_list = _tmp119_;
		_tmp120_ = _m_list;
		_tmp121_ = vala_collection_get_size ((ValaCollection*) _tmp120_);
		_tmp122_ = _tmp121_;
		_m_size = _tmp122_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp123_;
			gint _tmp124_;
			gint _tmp125_;
			ValaList* _tmp126_;
			gint _tmp127_;
			gpointer _tmp128_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp129_;
			_tmp123_ = _m_index;
			_m_index = _tmp123_ + 1;
			_tmp124_ = _m_index;
			_tmp125_ = _m_size;
			if (!(_tmp124_ < _tmp125_)) {
				break;
			}
			_tmp126_ = _m_list;
			_tmp127_ = _m_index;
			_tmp128_ = vala_list_get (_tmp126_, _tmp127_);
			m = (ValaMethod*) _tmp128_;
			_tmp129_ = m;
			cxx_writer_walk_method (self, _tmp129_);
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	_tmp130_ = self->priv->extends;
	_tmp131_ = g_strconcat (_tmp130_, "};\n", NULL);
	_g_free0 (self->priv->extends);
	self->priv->extends = _tmp131_;
	_tmp132_ = g_strdup ("");
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp132_;
}


void cxx_writer_walk_enum (CxxWriter* self, ValaEnum* e) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
}


static inline gboolean cxx_writer_is_generic (CxxWriter* self, const gchar* type) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_;
	gboolean _tmp5_;
	gboolean _tmp8_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (type != NULL, FALSE);
	_tmp2_ = self->cxx_mode;
	if (_tmp2_) {
		const gchar* _tmp3_;
		gint _tmp4_ = 0;
		_tmp3_ = type;
		_tmp4_ = string_index_of (_tmp3_, "<", 0);
		_tmp1_ = _tmp4_ != (-1);
	} else {
		_tmp1_ = FALSE;
	}
	_tmp5_ = _tmp1_;
	if (_tmp5_) {
		const gchar* _tmp6_;
		gint _tmp7_ = 0;
		_tmp6_ = type;
		_tmp7_ = string_index_of (_tmp6_, ">", 0);
		_tmp0_ = _tmp7_ != (-1);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp8_ = _tmp0_;
	result = _tmp8_;
	return result;
}


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


void cxx_writer_walk_method (CxxWriter* self, ValaMethod* m) {
	gboolean first;
	ValaMethod* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* cname;
	ValaMethod* _tmp2_;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* alias;
	gchar* ret = NULL;
	gchar* _tmp6_;
	gchar* def_args;
	gchar* _tmp7_;
	gchar* call_args;
	gboolean void_return = FALSE;
	ValaMethod* _tmp8_;
	ValaMemberBinding _tmp9_ = 0;
	ValaMemberBinding _tmp10_;
	gboolean is_static;
	ValaMethod* _tmp11_;
	gboolean is_constructor;
	ValaMethod* _tmp12_;
	ValaDataType* _tmp13_ = NULL;
	ValaDataType* _tmp14_;
	gchar* _tmp15_ = NULL;
	const gchar* _tmp16_;
	gboolean _tmp17_ = FALSE;
	const gchar* _tmp26_;
	const gchar* _tmp30_;
	ValaMethod* _tmp31_;
	gboolean _tmp32_ = FALSE;
	gchar* _tmp33_;
	gchar* applys;
	gchar* _tmp34_;
	gchar* clears;
	gchar* _tmp35_;
	gchar* pfx;
	const gchar* _tmp101_;
	const gchar* _tmp111_;
	const gchar* _tmp112_;
	gboolean _tmp118_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (m != NULL);
	first = TRUE;
	_tmp0_ = m;
	_tmp1_ = vala_method_get_cname (_tmp0_);
	cname = _tmp1_;
	_tmp2_ = m;
	_tmp3_ = vala_symbol_get_name ((ValaSymbol*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = cxx_writer_get_alias (self, _tmp4_);
	alias = _tmp5_;
	_tmp6_ = g_strdup ("");
	def_args = _tmp6_;
	_tmp7_ = g_strdup ("");
	call_args = _tmp7_;
	_tmp8_ = m;
	_tmp9_ = vala_method_get_binding (_tmp8_);
	_tmp10_ = _tmp9_;
	is_static = (_tmp10_ & VALA_MEMBER_BINDING_STATIC) != 0;
	_tmp11_ = m;
	is_constructor = VALA_IS_CREATION_METHOD (_tmp11_);
	_tmp12_ = m;
	_tmp13_ = vala_method_get_return_type (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = vala_code_node_to_string ((ValaCodeNode*) _tmp14_);
	_g_free0 (ret);
	ret = _tmp15_;
	_tmp16_ = ret;
	_tmp17_ = cxx_writer_is_generic (self, _tmp16_);
	if (_tmp17_) {
		const gchar* _tmp18_;
		gchar* _tmp19_ = NULL;
		_tmp18_ = ret;
		_tmp19_ = cxx_writer_get_ctype (self, _tmp18_);
		_g_free0 (ret);
		ret = _tmp19_;
	} else {
		ValaMethod* _tmp20_;
		ValaDataType* _tmp21_ = NULL;
		ValaDataType* _tmp22_;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_;
		gchar* _tmp25_ = NULL;
		_tmp20_ = m;
		_tmp21_ = vala_method_get_return_type (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_data_type_get_cname (_tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = cxx_writer_get_ctype (self, _tmp24_);
		_g_free0 (ret);
		ret = _tmp25_;
		_g_free0 (_tmp24_);
	}
	_tmp26_ = ret;
	if (_tmp26_ == NULL) {
		const gchar* _tmp27_;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_;
		_tmp27_ = cname;
		_tmp28_ = g_strdup_printf ("Cannot resolve return type for %s\n", _tmp27_);
		_tmp29_ = _tmp28_;
		valabind_compiler_error (_tmp29_);
		_g_free0 (_tmp29_);
	}
	_tmp30_ = ret;
	void_return = g_strcmp0 (_tmp30_, "void") == 0;
	_tmp31_ = m;
	_tmp32_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp31_);
	if (_tmp32_) {
		_g_free0 (call_args);
		_g_free0 (def_args);
		_g_free0 (ret);
		_g_free0 (alias);
		_g_free0 (cname);
		return;
	}
	_tmp33_ = g_strdup ("");
	applys = _tmp33_;
	_tmp34_ = g_strdup ("");
	clears = _tmp34_;
	_tmp35_ = g_strdup ("");
	pfx = _tmp35_;
	{
		ValaMethod* _tmp36_;
		ValaList* _tmp37_ = NULL;
		ValaList* _foo_list;
		ValaList* _tmp38_;
		gint _tmp39_ = 0;
		gint _tmp40_;
		gint _foo_size;
		gint _foo_index;
		_tmp36_ = m;
		_tmp37_ = vala_method_get_parameters (_tmp36_);
		_foo_list = _tmp37_;
		_tmp38_ = _foo_list;
		_tmp39_ = vala_collection_get_size ((ValaCollection*) _tmp38_);
		_tmp40_ = _tmp39_;
		_foo_size = _tmp40_;
		_foo_index = -1;
		while (TRUE) {
			gint _tmp41_;
			gint _tmp42_;
			gint _tmp43_;
			ValaList* _tmp44_;
			gint _tmp45_;
			gpointer _tmp46_ = NULL;
			ValaParameter* foo;
			ValaParameter* _tmp47_;
			const gchar* _tmp48_ = NULL;
			const gchar* _tmp49_;
			gchar* _tmp50_;
			gchar* arg_name;
			ValaParameter* _tmp51_;
			ValaDataType* _tmp52_ = NULL;
			ValaDataType* _tmp53_;
			ValaDataType* _tmp54_;
			ValaDataType* bar;
			ValaDataType* _tmp55_;
			ValaDataType* _tmp56_;
			gchar* _tmp57_ = NULL;
			gchar* _tmp58_;
			gchar* _tmp59_ = NULL;
			gchar* _tmp60_;
			gchar* arg_type;
			gboolean _tmp61_;
			ValaParameter* _tmp64_;
			ValaParameterDirection _tmp65_ = 0;
			ValaParameterDirection _tmp66_;
			const gchar* _tmp88_;
			const gchar* _tmp89_;
			const gchar* _tmp90_;
			gchar* _tmp91_ = NULL;
			gchar* _tmp92_;
			gchar* _tmp93_;
			const gchar* _tmp94_;
			const gchar* _tmp95_;
			const gchar* _tmp96_;
			const gchar* _tmp97_;
			gchar* _tmp98_ = NULL;
			gchar* _tmp99_;
			gchar* _tmp100_;
			_tmp41_ = _foo_index;
			_foo_index = _tmp41_ + 1;
			_tmp42_ = _foo_index;
			_tmp43_ = _foo_size;
			if (!(_tmp42_ < _tmp43_)) {
				break;
			}
			_tmp44_ = _foo_list;
			_tmp45_ = _foo_index;
			_tmp46_ = vala_list_get (_tmp44_, _tmp45_);
			foo = (ValaParameter*) _tmp46_;
			_tmp47_ = foo;
			_tmp48_ = vala_symbol_get_name ((ValaSymbol*) _tmp47_);
			_tmp49_ = _tmp48_;
			_tmp50_ = g_strdup (_tmp49_);
			arg_name = _tmp50_;
			_tmp51_ = foo;
			_tmp52_ = vala_variable_get_variable_type ((ValaVariable*) _tmp51_);
			_tmp53_ = _tmp52_;
			_tmp54_ = _vala_code_node_ref0 (_tmp53_);
			bar = _tmp54_;
			_tmp55_ = bar;
			if (_tmp55_ == NULL) {
				_vala_code_node_unref0 (bar);
				_g_free0 (arg_name);
				_vala_code_node_unref0 (foo);
				continue;
			}
			_tmp56_ = bar;
			_tmp57_ = vala_data_type_get_cname (_tmp56_);
			_tmp58_ = _tmp57_;
			_tmp59_ = cxx_writer_get_ctype (self, _tmp58_);
			_tmp60_ = _tmp59_;
			_g_free0 (_tmp58_);
			arg_type = _tmp60_;
			_tmp61_ = first;
			if (_tmp61_) {
				gchar* _tmp62_;
				_tmp62_ = g_strdup ("");
				_g_free0 (pfx);
				pfx = _tmp62_;
				first = FALSE;
			} else {
				gchar* _tmp63_;
				_tmp63_ = g_strdup (", ");
				_g_free0 (pfx);
				pfx = _tmp63_;
			}
			_tmp64_ = foo;
			_tmp65_ = vala_parameter_get_direction (_tmp64_);
			_tmp66_ = _tmp65_;
			if (_tmp66_ != VALA_PARAMETER_DIRECTION_IN) {
				gchar* _tmp67_;
				gchar* var_name;
				ValaParameter* _tmp68_;
				ValaParameterDirection _tmp69_ = 0;
				ValaParameterDirection _tmp70_;
				const gchar* _tmp76_;
				gint _tmp77_ = 0;
				const gchar* _tmp80_;
				const gchar* _tmp81_;
				const gchar* _tmp82_;
				const gchar* _tmp83_;
				const gchar* _tmp84_;
				gchar* _tmp85_ = NULL;
				gchar* _tmp86_;
				gchar* _tmp87_;
				_tmp67_ = g_strdup ("");
				var_name = _tmp67_;
				_tmp68_ = foo;
				_tmp69_ = vala_parameter_get_direction (_tmp68_);
				_tmp70_ = _tmp69_;
				if (_tmp70_ == VALA_PARAMETER_DIRECTION_OUT) {
					gchar* _tmp71_;
					_tmp71_ = g_strdup ("OUTPUT");
					_g_free0 (var_name);
					var_name = _tmp71_;
				} else {
					ValaParameter* _tmp72_;
					ValaParameterDirection _tmp73_ = 0;
					ValaParameterDirection _tmp74_;
					_tmp72_ = foo;
					_tmp73_ = vala_parameter_get_direction (_tmp72_);
					_tmp74_ = _tmp73_;
					if (_tmp74_ == VALA_PARAMETER_DIRECTION_REF) {
						gchar* _tmp75_;
						_tmp75_ = g_strdup ("INOUT");
						_g_free0 (var_name);
						var_name = _tmp75_;
					}
				}
				_tmp76_ = arg_type;
				_tmp77_ = string_index_of (_tmp76_, "*", 0);
				if (_tmp77_ == (-1)) {
					const gchar* _tmp78_;
					gchar* _tmp79_;
					_tmp78_ = arg_type;
					_tmp79_ = g_strconcat (_tmp78_, "*", NULL);
					_g_free0 (arg_type);
					arg_type = _tmp79_;
				}
				_tmp80_ = applys;
				_tmp81_ = arg_type;
				_tmp82_ = var_name;
				_tmp83_ = arg_type;
				_tmp84_ = arg_name;
				_tmp85_ = g_strdup_printf ("  %%apply %s %s { %s %s };\n", _tmp81_, _tmp82_, _tmp83_, _tmp84_);
				_tmp86_ = _tmp85_;
				_tmp87_ = g_strconcat (_tmp80_, _tmp86_, NULL);
				_g_free0 (applys);
				applys = _tmp87_;
				_g_free0 (_tmp86_);
				_g_free0 (var_name);
			}
			_tmp88_ = call_args;
			_tmp89_ = pfx;
			_tmp90_ = arg_name;
			_tmp91_ = g_strdup_printf ("%s%s", _tmp89_, _tmp90_);
			_tmp92_ = _tmp91_;
			_tmp93_ = g_strconcat (_tmp88_, _tmp92_, NULL);
			_g_free0 (call_args);
			call_args = _tmp93_;
			_g_free0 (_tmp92_);
			_tmp94_ = def_args;
			_tmp95_ = pfx;
			_tmp96_ = arg_type;
			_tmp97_ = arg_name;
			_tmp98_ = g_strdup_printf ("%s%s %s", _tmp95_, _tmp96_, _tmp97_);
			_tmp99_ = _tmp98_;
			_tmp100_ = g_strconcat (_tmp94_, _tmp99_, NULL);
			_g_free0 (def_args);
			def_args = _tmp100_;
			_g_free0 (_tmp99_);
			_g_free0 (arg_type);
			_vala_code_node_unref0 (bar);
			_g_free0 (arg_name);
			_vala_code_node_unref0 (foo);
		}
		_vala_iterable_unref0 (_foo_list);
	}
	_tmp101_ = self->priv->classname;
	if (g_strcmp0 (_tmp101_, "") == 0) {
		const gchar* _tmp102_;
		const gchar* _tmp103_;
		const gchar* _tmp104_;
		const gchar* _tmp105_;
		gchar* _tmp106_ = NULL;
		gchar* _tmp107_;
		gchar* _tmp108_;
		const gchar* _tmp109_;
		gchar* _tmp110_;
		_tmp102_ = self->priv->externs;
		_tmp103_ = ret;
		_tmp104_ = cname;
		_tmp105_ = def_args;
		_tmp106_ = g_strdup_printf ("extern %s %s (%s);\n", _tmp103_, _tmp104_, _tmp105_);
		_tmp107_ = _tmp106_;
		_tmp108_ = g_strconcat (_tmp102_, _tmp107_, NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp108_;
		_g_free0 (_tmp107_);
		is_constructor = FALSE;
		is_static = TRUE;
		_tmp109_ = self->priv->nspace;
		_tmp110_ = g_strdup (_tmp109_);
		_g_free0 (self->priv->classname);
		self->priv->classname = _tmp110_;
	}
	_tmp111_ = self->priv->nspace;
	_tmp112_ = self->priv->classname;
	if (g_strcmp0 (_tmp111_, _tmp112_) == 0) {
		const gchar* _tmp113_;
		gchar* _tmp114_;
		gchar* _tmp115_;
		const gchar* _tmp116_;
		gchar* _tmp117_;
		_tmp113_ = self->priv->nspace;
		_tmp114_ = g_strconcat (_tmp113_, "_", NULL);
		_tmp115_ = _tmp114_;
		_tmp116_ = alias;
		_tmp117_ = g_strconcat (_tmp115_, _tmp116_, NULL);
		_g_free0 (alias);
		alias = _tmp117_;
		_g_free0 (_tmp115_);
	}
	_tmp118_ = is_constructor;
	if (_tmp118_) {
		const gchar* _tmp119_;
		const gchar* _tmp120_;
		const gchar* _tmp121_;
		const gchar* _tmp122_;
		gchar* _tmp123_ = NULL;
		gchar* _tmp124_;
		gchar* _tmp125_;
		const gchar* _tmp126_;
		const gchar* _tmp127_;
		const gchar* _tmp128_;
		const gchar* _tmp129_;
		gchar* _tmp130_ = NULL;
		gchar* _tmp131_;
		gchar* _tmp132_;
		gboolean _tmp133_;
		const gchar* _tmp136_;
		const gchar* _tmp137_;
		const gchar* _tmp138_;
		gchar* _tmp139_ = NULL;
		gchar* _tmp140_;
		gchar* _tmp141_;
		const gchar* _tmp142_;
		const gchar* _tmp143_;
		gchar* _tmp144_;
		_tmp119_ = self->priv->externs;
		_tmp120_ = self->priv->classcname;
		_tmp121_ = cname;
		_tmp122_ = def_args;
		_tmp123_ = g_strdup_printf ("extern %s* %s (%s);\n", _tmp120_, _tmp121_, _tmp122_);
		_tmp124_ = _tmp123_;
		_tmp125_ = g_strconcat (_tmp119_, _tmp124_, NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp125_;
		_g_free0 (_tmp124_);
		_tmp126_ = self->priv->extends;
		_tmp127_ = self->priv->modulename;
		_tmp128_ = self->priv->classname;
		_tmp129_ = def_args;
		_tmp130_ = g_strdup_printf ("  %s_%s (%s) {\n", _tmp127_, _tmp128_, _tmp129_);
		_tmp131_ = _tmp130_;
		_tmp132_ = g_strconcat (_tmp126_, _tmp131_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp132_;
		_g_free0 (_tmp131_);
		_tmp133_ = self->glib_mode;
		if (_tmp133_) {
			const gchar* _tmp134_;
			gchar* _tmp135_;
			_tmp134_ = self->priv->extends;
			_tmp135_ = g_strconcat (_tmp134_, "    g_type_init ();\n", NULL);
			_g_free0 (self->priv->extends);
			self->priv->extends = _tmp135_;
		}
		_tmp136_ = self->priv->extends;
		_tmp137_ = cname;
		_tmp138_ = call_args;
		_tmp139_ = g_strdup_printf ("    self = %s (%s);\n  }\n", _tmp137_, _tmp138_);
		_tmp140_ = _tmp139_;
		_tmp141_ = g_strconcat (_tmp136_, _tmp140_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp141_;
		_g_free0 (_tmp140_);
		_tmp142_ = self->priv->extends;
		_tmp143_ = clears;
		_tmp144_ = g_strconcat (_tmp142_, _tmp143_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp144_;
	} else {
		gboolean _tmp145_;
		gboolean _tmp153_;
		gboolean _tmp168_ = FALSE;
		gboolean _tmp169_;
		gboolean _tmp172_;
		const gchar* _tmp283_;
		const gchar* _tmp284_;
		gchar* _tmp285_;
		_tmp145_ = is_static;
		if (!_tmp145_) {
			gchar* _tmp146_ = NULL;
			const gchar* _tmp147_;
			const gchar* _tmp151_;
			gchar* _tmp152_;
			_tmp147_ = call_args;
			if (g_strcmp0 (_tmp147_, "") == 0) {
				gchar* _tmp148_;
				_tmp148_ = g_strdup ("self");
				_g_free0 (_tmp146_);
				_tmp146_ = _tmp148_;
			} else {
				const gchar* _tmp149_;
				gchar* _tmp150_;
				_tmp149_ = call_args;
				_tmp150_ = g_strconcat ("self, ", _tmp149_, NULL);
				_g_free0 (_tmp146_);
				_tmp146_ = _tmp150_;
			}
			_tmp151_ = _tmp146_;
			_tmp152_ = g_strdup (_tmp151_);
			_g_free0 (call_args);
			call_args = _tmp152_;
			_g_free0 (_tmp146_);
		}
		_tmp153_ = is_static;
		if (_tmp153_) {
			const gchar* _tmp154_;
			const gchar* _tmp155_;
			const gchar* _tmp156_;
			const gchar* _tmp157_;
			gchar* _tmp158_ = NULL;
			gchar* _tmp159_;
			gchar* _tmp160_;
			_tmp154_ = self->priv->extends;
			_tmp155_ = ret;
			_tmp156_ = alias;
			_tmp157_ = def_args;
			_tmp158_ = g_strdup_printf ("  static %s %s (%s) {\n", _tmp155_, _tmp156_, _tmp157_);
			_tmp159_ = _tmp158_;
			_tmp160_ = g_strconcat (_tmp154_, _tmp159_, NULL);
			_g_free0 (self->priv->extends);
			self->priv->extends = _tmp160_;
			_g_free0 (_tmp159_);
		} else {
			const gchar* _tmp161_;
			const gchar* _tmp162_;
			const gchar* _tmp163_;
			const gchar* _tmp164_;
			gchar* _tmp165_ = NULL;
			gchar* _tmp166_;
			gchar* _tmp167_;
			_tmp161_ = self->priv->extends;
			_tmp162_ = ret;
			_tmp163_ = alias;
			_tmp164_ = def_args;
			_tmp165_ = g_strdup_printf ("  %s %s (%s) {\n", _tmp162_, _tmp163_, _tmp164_);
			_tmp166_ = _tmp165_;
			_tmp167_ = g_strconcat (_tmp161_, _tmp166_, NULL);
			_g_free0 (self->priv->extends);
			self->priv->extends = _tmp167_;
			_g_free0 (_tmp166_);
		}
		_tmp169_ = self->cxx_mode;
		if (_tmp169_) {
			const gchar* _tmp170_;
			gint _tmp171_ = 0;
			_tmp170_ = ret;
			_tmp171_ = string_index_of (_tmp170_, "std::vector", 0);
			_tmp168_ = _tmp171_ != (-1);
		} else {
			_tmp168_ = FALSE;
		}
		_tmp172_ = _tmp168_;
		if (_tmp172_) {
			const gchar* _tmp173_;
			gint _tmp174_ = 0;
			gint ptr;
			gchar* _tmp175_ = NULL;
			gint _tmp176_;
			const gchar* _tmp185_;
			gchar* _tmp186_;
			gchar* iter_type;
			const gchar* _tmp187_;
			gchar* _tmp188_ = NULL;
			const gchar* _tmp189_;
			gchar* _tmp190_ = NULL;
			const gchar* _tmp191_;
			ValaMethod* _tmp192_;
			ValaDataType* _tmp193_ = NULL;
			ValaDataType* _tmp194_;
			gchar* _tmp195_ = NULL;
			gchar* _tmp196_;
			gint _tmp197_ = 0;
			gboolean _tmp198_;
			const gchar* _tmp268_;
			const gchar* _tmp269_;
			const gchar* _tmp270_;
			gchar* _tmp271_ = NULL;
			gchar* _tmp272_;
			gchar* _tmp273_;
			_tmp173_ = ret;
			_tmp174_ = string_index_of (_tmp173_, "<", 0);
			ptr = _tmp174_;
			_tmp176_ = ptr;
			if (_tmp176_ == (-1)) {
				const gchar* _tmp177_;
				gchar* _tmp178_;
				_tmp177_ = ret;
				_tmp178_ = g_strdup (_tmp177_);
				_g_free0 (_tmp175_);
				_tmp175_ = _tmp178_;
			} else {
				const gchar* _tmp179_;
				gint _tmp180_;
				const gchar* _tmp181_;
				gint _tmp182_ = 0;
				gint _tmp183_;
				gchar* _tmp184_ = NULL;
				_tmp179_ = ret;
				_tmp180_ = ptr;
				_tmp181_ = ret;
				_tmp182_ = strlen (_tmp181_);
				_tmp183_ = _tmp182_;
				_tmp184_ = string_slice (_tmp179_, (glong) _tmp180_, (glong) _tmp183_);
				_g_free0 (_tmp175_);
				_tmp175_ = _tmp184_;
			}
			_tmp185_ = _tmp175_;
			_tmp186_ = g_strdup (_tmp185_);
			iter_type = _tmp186_;
			_tmp187_ = iter_type;
			_tmp188_ = string_replace (_tmp187_, "<", "");
			_g_free0 (iter_type);
			iter_type = _tmp188_;
			_tmp189_ = iter_type;
			_tmp190_ = string_replace (_tmp189_, ">", "");
			_g_free0 (iter_type);
			iter_type = _tmp190_;
			_tmp191_ = iter_type;
			if (g_strcmp0 (_tmp191_, "G*") == 0) {
				valabind_compiler_error ("Fuck, no <G> type support.\n");
			}
			_tmp192_ = m;
			_tmp193_ = vala_method_get_return_type (_tmp192_);
			_tmp194_ = _tmp193_;
			_tmp195_ = vala_code_node_to_string ((ValaCodeNode*) _tmp194_);
			_tmp196_ = _tmp195_;
			_tmp197_ = string_index_of (_tmp196_, "RFList", 0);
			_tmp198_ = _tmp197_ != (-1);
			_g_free0 (_tmp196_);
			if (_tmp198_) {
				const gchar* _tmp199_;
				const gchar* _tmp200_;
				gchar* _tmp201_ = NULL;
				gchar* _tmp202_;
				gchar* _tmp203_;
				const gchar* _tmp204_;
				gchar* _tmp205_;
				const gchar* _tmp206_;
				const gchar* _tmp207_;
				gchar* _tmp208_ = NULL;
				gchar* _tmp209_;
				gchar* _tmp210_;
				const gchar* _tmp211_;
				const gchar* _tmp212_;
				const gchar* _tmp213_;
				gchar* _tmp214_ = NULL;
				gchar* _tmp215_;
				gchar* _tmp216_;
				const gchar* _tmp217_;
				gchar* _tmp218_;
				const gchar* _tmp219_;
				const gchar* _tmp220_;
				gchar* _tmp221_ = NULL;
				gchar* _tmp222_;
				gchar* _tmp223_;
				const gchar* _tmp224_;
				gchar* _tmp225_;
				const gchar* _tmp226_;
				gchar* _tmp227_;
				const gchar* _tmp228_;
				gchar* _tmp229_;
				_tmp199_ = self->priv->extends;
				_tmp200_ = ret;
				_tmp201_ = g_strdup_printf ("    %s ret;\n", _tmp200_);
				_tmp202_ = _tmp201_;
				_tmp203_ = g_strconcat (_tmp199_, _tmp202_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp203_;
				_g_free0 (_tmp202_);
				_tmp204_ = self->priv->extends;
				_tmp205_ = g_strconcat (_tmp204_, "    void** array;\n", NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp205_;
				_tmp206_ = self->priv->extends;
				_tmp207_ = iter_type;
				_tmp208_ = g_strdup_printf ("    %s *item;\n", _tmp207_);
				_tmp209_ = _tmp208_;
				_tmp210_ = g_strconcat (_tmp206_, _tmp209_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp210_;
				_g_free0 (_tmp209_);
				_tmp211_ = self->priv->extends;
				_tmp212_ = cname;
				_tmp213_ = call_args;
				_tmp214_ = g_strdup_printf ("    array = %s (%s);\n", _tmp212_, _tmp213_);
				_tmp215_ = _tmp214_;
				_tmp216_ = g_strconcat (_tmp211_, _tmp215_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp216_;
				_g_free0 (_tmp215_);
				_tmp217_ = self->priv->extends;
				_tmp218_ = g_strconcat (_tmp217_, "    r_flist_rewind (array);\n", NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp218_;
				_tmp219_ = self->priv->extends;
				_tmp220_ = iter_type;
				_tmp221_ = g_strdup_printf ("    while (*array != 0 && (item = (%s*)(*array++)))\n", _tmp220_);
				_tmp222_ = _tmp221_;
				_tmp223_ = g_strconcat (_tmp219_, _tmp222_, NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp223_;
				_g_free0 (_tmp222_);
				_tmp224_ = self->priv->extends;
				_tmp225_ = g_strconcat (_tmp224_, "        ret.push_back(*item);\n", NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp225_;
				_tmp226_ = self->priv->extends;
				_tmp227_ = g_strconcat (_tmp226_, "    return ret;\n", NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp227_;
				_tmp228_ = self->priv->extends;
				_tmp229_ = g_strconcat (_tmp228_, "  }\n", NULL);
				_g_free0 (self->priv->extends);
				self->priv->extends = _tmp229_;
			} else {
				ValaMethod* _tmp230_;
				ValaDataType* _tmp231_ = NULL;
				ValaDataType* _tmp232_;
				gchar* _tmp233_ = NULL;
				gchar* _tmp234_;
				gint _tmp235_ = 0;
				gboolean _tmp236_;
				_tmp230_ = m;
				_tmp231_ = vala_method_get_return_type (_tmp230_);
				_tmp232_ = _tmp231_;
				_tmp233_ = vala_code_node_to_string ((ValaCodeNode*) _tmp232_);
				_tmp234_ = _tmp233_;
				_tmp235_ = string_index_of (_tmp234_, "RList", 0);
				_tmp236_ = _tmp235_ != (-1);
				_g_free0 (_tmp234_);
				if (_tmp236_) {
					const gchar* _tmp237_;
					const gchar* _tmp238_;
					gchar* _tmp239_ = NULL;
					gchar* _tmp240_;
					gchar* _tmp241_;
					const gchar* _tmp242_;
					gchar* _tmp243_;
					const gchar* _tmp244_;
					gchar* _tmp245_;
					const gchar* _tmp246_;
					const gchar* _tmp247_;
					gchar* _tmp248_ = NULL;
					gchar* _tmp249_;
					gchar* _tmp250_;
					const gchar* _tmp251_;
					const gchar* _tmp252_;
					const gchar* _tmp253_;
					gchar* _tmp254_ = NULL;
					gchar* _tmp255_;
					gchar* _tmp256_;
					const gchar* _tmp257_;
					const gchar* _tmp258_;
					gchar* _tmp259_ = NULL;
					gchar* _tmp260_;
					gchar* _tmp261_;
					const gchar* _tmp262_;
					gchar* _tmp263_;
					const gchar* _tmp264_;
					gchar* _tmp265_;
					const gchar* _tmp266_;
					gchar* _tmp267_;
					_tmp237_ = self->priv->extends;
					_tmp238_ = ret;
					_tmp239_ = g_strdup_printf ("    %s ret;\n", _tmp238_);
					_tmp240_ = _tmp239_;
					_tmp241_ = g_strconcat (_tmp237_, _tmp240_, NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp241_;
					_g_free0 (_tmp240_);
					_tmp242_ = self->priv->extends;
					_tmp243_ = g_strconcat (_tmp242_, "    RList *list;\n", NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp243_;
					_tmp244_ = self->priv->extends;
					_tmp245_ = g_strconcat (_tmp244_, "    RListIter *iter;\n", NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp245_;
					_tmp246_ = self->priv->extends;
					_tmp247_ = iter_type;
					_tmp248_ = g_strdup_printf ("    %s *item;\n", _tmp247_);
					_tmp249_ = _tmp248_;
					_tmp250_ = g_strconcat (_tmp246_, _tmp249_, NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp250_;
					_g_free0 (_tmp249_);
					_tmp251_ = self->priv->extends;
					_tmp252_ = cname;
					_tmp253_ = call_args;
					_tmp254_ = g_strdup_printf ("    list = %s (%s);\n", _tmp252_, _tmp253_);
					_tmp255_ = _tmp254_;
					_tmp256_ = g_strconcat (_tmp251_, _tmp255_, NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp256_;
					_g_free0 (_tmp255_);
					_tmp257_ = self->priv->extends;
					_tmp258_ = iter_type;
					_tmp259_ = g_strdup_printf ("    for (iter = list->head; iter && (item = (%s*)iter->data); iter = i" \
"ter->n)\n", _tmp258_);
					_tmp260_ = _tmp259_;
					_tmp261_ = g_strconcat (_tmp257_, _tmp260_, NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp261_;
					_g_free0 (_tmp260_);
					_tmp262_ = self->priv->extends;
					_tmp263_ = g_strconcat (_tmp262_, "        ret.push_back(*item);\n", NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp263_;
					_tmp264_ = self->priv->extends;
					_tmp265_ = g_strconcat (_tmp264_, "    return ret;\n", NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp265_;
					_tmp266_ = self->priv->extends;
					_tmp267_ = g_strconcat (_tmp266_, "  }\n", NULL);
					_g_free0 (self->priv->extends);
					self->priv->extends = _tmp267_;
				}
			}
			_tmp268_ = self->priv->vectors;
			_tmp269_ = iter_type;
			_tmp270_ = iter_type;
			_tmp271_ = g_strdup_printf ("  %%template(%sVector) std::vector<%s>;\n", _tmp269_, _tmp270_);
			_tmp272_ = _tmp271_;
			_tmp273_ = g_strconcat (_tmp268_, _tmp272_, NULL);
			_g_free0 (self->priv->vectors);
			self->priv->vectors = _tmp273_;
			_g_free0 (_tmp272_);
			_g_free0 (iter_type);
			_g_free0 (_tmp175_);
		} else {
			const gchar* _tmp274_ = NULL;
			gboolean _tmp275_;
			const gchar* _tmp276_;
			const gchar* _tmp277_;
			const gchar* _tmp278_;
			const gchar* _tmp279_;
			gchar* _tmp280_ = NULL;
			gchar* _tmp281_;
			gchar* _tmp282_;
			_tmp275_ = void_return;
			if (_tmp275_) {
				_tmp274_ = "";
			} else {
				_tmp274_ = "return";
			}
			_tmp276_ = self->priv->extends;
			_tmp277_ = _tmp274_;
			_tmp278_ = cname;
			_tmp279_ = call_args;
			_tmp280_ = g_strdup_printf ("    %s %s (%s);\n  }\n", _tmp277_, _tmp278_, _tmp279_);
			_tmp281_ = _tmp280_;
			_tmp282_ = g_strconcat (_tmp276_, _tmp281_, NULL);
			_g_free0 (self->priv->extends);
			self->priv->extends = _tmp282_;
			_g_free0 (_tmp281_);
		}
		_tmp283_ = self->priv->extends;
		_tmp284_ = clears;
		_tmp285_ = g_strconcat (_tmp283_, _tmp284_, NULL);
		_g_free0 (self->priv->extends);
		self->priv->extends = _tmp285_;
	}
	_g_free0 (pfx);
	_g_free0 (clears);
	_g_free0 (applys);
	_g_free0 (call_args);
	_g_free0 (def_args);
	_g_free0 (ret);
	_g_free0 (alias);
	_g_free0 (cname);
}


static gpointer _vala_source_reference_ref0 (gpointer self) {
	return self ? vala_source_reference_ref (self) : NULL;
}


static void cxx_writer_real_visit_namespace (ValaCodeVisitor* base, ValaNamespace* ns) {
	CxxWriter * self;
	ValaNamespace* _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	ValaNamespace* _tmp4_;
	ValaSourceReference* _tmp5_ = NULL;
	ValaSourceReference* _tmp6_;
	ValaSourceReference* _tmp7_;
	ValaSourceReference* sr;
	gboolean _tmp8_ = FALSE;
	ValaSourceReference* _tmp9_;
	gboolean _tmp16_;
	ValaNamespace* _tmp17_;
	const gchar* _tmp18_ = NULL;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	ValaNamespace* _tmp21_;
	const gchar* _tmp93_ = NULL;
	ValaNamespace* _tmp94_;
	const gchar* _tmp95_ = NULL;
	const gchar* _tmp96_;
	const gchar* _tmp97_;
	const gchar* _tmp101_;
	gchar* _tmp102_;
	gchar* classprefix;
	self = (CxxWriter*) base;
	g_return_if_fail (ns != NULL);
	_tmp0_ = ns;
	_tmp1_ = vala_symbol_get_name ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == NULL) {
		return;
	}
	_tmp3_ = g_strdup ("");
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp3_;
	_tmp4_ = ns;
	_tmp5_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = _vala_source_reference_ref0 (_tmp6_);
	sr = _tmp7_;
	_tmp9_ = sr;
	if (_tmp9_ != NULL) {
		ValaSourceReference* _tmp10_;
		ValaSourceFile* _tmp11_ = NULL;
		ValaSourceFile* _tmp12_;
		const gchar* _tmp13_ = NULL;
		const gchar* _tmp14_;
		gboolean _tmp15_ = FALSE;
		_tmp10_ = sr;
		_tmp11_ = vala_source_reference_get_file (_tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = vala_source_file_get_filename (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = cxx_writer_is_target_file (self, _tmp14_);
		_tmp8_ = !_tmp15_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp16_ = _tmp8_;
	if (_tmp16_) {
		_vala_source_reference_unref0 (sr);
		return;
	}
	_tmp17_ = ns;
	_tmp18_ = vala_symbol_get_name ((ValaSymbol*) _tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strdup (_tmp19_);
	_g_free0 (self->priv->nspace);
	self->priv->nspace = _tmp20_;
	_tmp21_ = ns;
	cxx_writer_process_includes (self, (ValaSymbol*) _tmp21_);
	{
		ValaNamespace* _tmp22_;
		ValaList* _tmp23_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp24_;
		gint _tmp25_ = 0;
		gint _tmp26_;
		gint _f_size;
		gint _f_index;
		_tmp22_ = ns;
		_tmp23_ = vala_namespace_get_fields (_tmp22_);
		_f_list = _tmp23_;
		_tmp24_ = _f_list;
		_tmp25_ = vala_collection_get_size ((ValaCollection*) _tmp24_);
		_tmp26_ = _tmp25_;
		_f_size = _tmp26_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp27_;
			gint _tmp28_;
			gint _tmp29_;
			ValaList* _tmp30_;
			gint _tmp31_;
			gpointer _tmp32_ = NULL;
			ValaField* f;
			ValaField* _tmp33_;
			_tmp27_ = _f_index;
			_f_index = _tmp27_ + 1;
			_tmp28_ = _f_index;
			_tmp29_ = _f_size;
			if (!(_tmp28_ < _tmp29_)) {
				break;
			}
			_tmp30_ = _f_list;
			_tmp31_ = _f_index;
			_tmp32_ = vala_list_get (_tmp30_, _tmp31_);
			f = (ValaField*) _tmp32_;
			_tmp33_ = f;
			cxx_writer_walk_field (self, _tmp33_);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	{
		ValaNamespace* _tmp34_;
		ValaList* _tmp35_ = NULL;
		ValaList* _e_list;
		ValaList* _tmp36_;
		gint _tmp37_ = 0;
		gint _tmp38_;
		gint _e_size;
		gint _e_index;
		_tmp34_ = ns;
		_tmp35_ = vala_namespace_get_enums (_tmp34_);
		_e_list = _tmp35_;
		_tmp36_ = _e_list;
		_tmp37_ = vala_collection_get_size ((ValaCollection*) _tmp36_);
		_tmp38_ = _tmp37_;
		_e_size = _tmp38_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp39_;
			gint _tmp40_;
			gint _tmp41_;
			ValaList* _tmp42_;
			gint _tmp43_;
			gpointer _tmp44_ = NULL;
			ValaEnum* e;
			ValaEnum* _tmp45_;
			_tmp39_ = _e_index;
			_e_index = _tmp39_ + 1;
			_tmp40_ = _e_index;
			_tmp41_ = _e_size;
			if (!(_tmp40_ < _tmp41_)) {
				break;
			}
			_tmp42_ = _e_list;
			_tmp43_ = _e_index;
			_tmp44_ = vala_list_get (_tmp42_, _tmp43_);
			e = (ValaEnum*) _tmp44_;
			_tmp45_ = e;
			cxx_writer_walk_enum (self, _tmp45_);
			_vala_code_node_unref0 (e);
		}
		_vala_iterable_unref0 (_e_list);
	}
	{
		ValaNamespace* _tmp46_;
		ValaList* _tmp47_ = NULL;
		ValaList* _c_list;
		ValaList* _tmp48_;
		gint _tmp49_ = 0;
		gint _tmp50_;
		gint _c_size;
		gint _c_index;
		_tmp46_ = ns;
		_tmp47_ = vala_namespace_get_structs (_tmp46_);
		_c_list = _tmp47_;
		_tmp48_ = _c_list;
		_tmp49_ = vala_collection_get_size ((ValaCollection*) _tmp48_);
		_tmp50_ = _tmp49_;
		_c_size = _tmp50_;
		_c_index = -1;
		while (TRUE) {
			gint _tmp51_;
			gint _tmp52_;
			gint _tmp53_;
			ValaList* _tmp54_;
			gint _tmp55_;
			gpointer _tmp56_ = NULL;
			ValaStruct* c;
			_tmp51_ = _c_index;
			_c_index = _tmp51_ + 1;
			_tmp52_ = _c_index;
			_tmp53_ = _c_size;
			if (!(_tmp52_ < _tmp53_)) {
				break;
			}
			_tmp54_ = _c_list;
			_tmp55_ = _c_index;
			_tmp56_ = vala_list_get (_tmp54_, _tmp55_);
			c = (ValaStruct*) _tmp56_;
			{
				ValaStruct* _tmp57_;
				ValaList* _tmp58_ = NULL;
				ValaList* _m_list;
				ValaList* _tmp59_;
				gint _tmp60_ = 0;
				gint _tmp61_;
				gint _m_size;
				gint _m_index;
				_tmp57_ = c;
				_tmp58_ = vala_struct_get_methods (_tmp57_);
				_m_list = _tmp58_;
				_tmp59_ = _m_list;
				_tmp60_ = vala_collection_get_size ((ValaCollection*) _tmp59_);
				_tmp61_ = _tmp60_;
				_m_size = _tmp61_;
				_m_index = -1;
				while (TRUE) {
					gint _tmp62_;
					gint _tmp63_;
					gint _tmp64_;
					ValaList* _tmp65_;
					gint _tmp66_;
					gpointer _tmp67_ = NULL;
					ValaMethod* m;
					ValaMethod* _tmp68_;
					_tmp62_ = _m_index;
					_m_index = _tmp62_ + 1;
					_tmp63_ = _m_index;
					_tmp64_ = _m_size;
					if (!(_tmp63_ < _tmp64_)) {
						break;
					}
					_tmp65_ = _m_list;
					_tmp66_ = _m_index;
					_tmp67_ = vala_list_get (_tmp65_, _tmp66_);
					m = (ValaMethod*) _tmp67_;
					_tmp68_ = m;
					cxx_writer_walk_method (self, _tmp68_);
					_vala_code_node_unref0 (m);
				}
				_vala_iterable_unref0 (_m_list);
			}
			{
				ValaStruct* _tmp69_;
				ValaList* _tmp70_ = NULL;
				ValaList* _f_list;
				ValaList* _tmp71_;
				gint _tmp72_ = 0;
				gint _tmp73_;
				gint _f_size;
				gint _f_index;
				_tmp69_ = c;
				_tmp70_ = vala_struct_get_fields (_tmp69_);
				_f_list = _tmp70_;
				_tmp71_ = _f_list;
				_tmp72_ = vala_collection_get_size ((ValaCollection*) _tmp71_);
				_tmp73_ = _tmp72_;
				_f_size = _tmp73_;
				_f_index = -1;
				while (TRUE) {
					gint _tmp74_;
					gint _tmp75_;
					gint _tmp76_;
					ValaList* _tmp77_;
					gint _tmp78_;
					gpointer _tmp79_ = NULL;
					ValaField* f;
					ValaField* _tmp80_;
					_tmp74_ = _f_index;
					_f_index = _tmp74_ + 1;
					_tmp75_ = _f_index;
					_tmp76_ = _f_size;
					if (!(_tmp75_ < _tmp76_)) {
						break;
					}
					_tmp77_ = _f_list;
					_tmp78_ = _f_index;
					_tmp79_ = vala_list_get (_tmp77_, _tmp78_);
					f = (ValaField*) _tmp79_;
					_tmp80_ = f;
					cxx_writer_walk_field (self, _tmp80_);
					_vala_code_node_unref0 (f);
				}
				_vala_iterable_unref0 (_f_list);
			}
			_vala_code_node_unref0 (c);
		}
		_vala_iterable_unref0 (_c_list);
	}
	{
		ValaNamespace* _tmp81_;
		ValaList* _tmp82_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp83_;
		gint _tmp84_ = 0;
		gint _tmp85_;
		gint _m_size;
		gint _m_index;
		_tmp81_ = ns;
		_tmp82_ = vala_namespace_get_methods (_tmp81_);
		_m_list = _tmp82_;
		_tmp83_ = _m_list;
		_tmp84_ = vala_collection_get_size ((ValaCollection*) _tmp83_);
		_tmp85_ = _tmp84_;
		_m_size = _tmp85_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp86_;
			gint _tmp87_;
			gint _tmp88_;
			ValaList* _tmp89_;
			gint _tmp90_;
			gpointer _tmp91_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp92_;
			_tmp86_ = _m_index;
			_m_index = _tmp86_ + 1;
			_tmp87_ = _m_index;
			_tmp88_ = _m_size;
			if (!(_tmp87_ < _tmp88_)) {
				break;
			}
			_tmp89_ = _m_list;
			_tmp90_ = _m_index;
			_tmp91_ = vala_list_get (_tmp89_, _tmp90_);
			m = (ValaMethod*) _tmp91_;
			_tmp92_ = m;
			cxx_writer_walk_method (self, _tmp92_);
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	_tmp94_ = ns;
	_tmp95_ = vala_symbol_get_name ((ValaSymbol*) _tmp94_);
	_tmp96_ = _tmp95_;
	_tmp97_ = self->priv->modulename;
	if (g_strcmp0 (_tmp96_, _tmp97_) == 0) {
		ValaNamespace* _tmp98_;
		const gchar* _tmp99_ = NULL;
		const gchar* _tmp100_;
		_tmp98_ = ns;
		_tmp99_ = vala_symbol_get_name ((ValaSymbol*) _tmp98_);
		_tmp100_ = _tmp99_;
		_tmp93_ = _tmp100_;
	} else {
		_tmp93_ = "";
	}
	_tmp101_ = _tmp93_;
	_tmp102_ = g_strdup (_tmp101_);
	classprefix = _tmp102_;
	{
		ValaNamespace* _tmp103_;
		ValaList* _tmp104_ = NULL;
		ValaList* _c_list;
		ValaList* _tmp105_;
		gint _tmp106_ = 0;
		gint _tmp107_;
		gint _c_size;
		gint _c_index;
		_tmp103_ = ns;
		_tmp104_ = vala_namespace_get_classes (_tmp103_);
		_c_list = _tmp104_;
		_tmp105_ = _c_list;
		_tmp106_ = vala_collection_get_size ((ValaCollection*) _tmp105_);
		_tmp107_ = _tmp106_;
		_c_size = _tmp107_;
		_c_index = -1;
		while (TRUE) {
			gint _tmp108_;
			gint _tmp109_;
			gint _tmp110_;
			ValaList* _tmp111_;
			gint _tmp112_;
			gpointer _tmp113_ = NULL;
			ValaClass* c;
			const gchar* _tmp114_;
			ValaClass* _tmp115_;
			_tmp108_ = _c_index;
			_c_index = _tmp108_ + 1;
			_tmp109_ = _c_index;
			_tmp110_ = _c_size;
			if (!(_tmp109_ < _tmp110_)) {
				break;
			}
			_tmp111_ = _c_list;
			_tmp112_ = _c_index;
			_tmp113_ = vala_list_get (_tmp111_, _tmp112_);
			c = (ValaClass*) _tmp113_;
			_tmp114_ = classprefix;
			_tmp115_ = c;
			cxx_writer_walk_class (self, _tmp114_, _tmp115_);
			_vala_code_node_unref0 (c);
		}
		_vala_iterable_unref0 (_c_list);
	}
	_g_free0 (classprefix);
	_vala_source_reference_unref0 (sr);
}


static gpointer _vala_code_context_ref0 (gpointer self) {
	return self ? vala_code_context_ref (self) : NULL;
}


void cxx_writer_write_file (CxxWriter* self, ValaCodeContext* context, const gchar* filename) {
	const gchar* _tmp0_;
	FILE* _tmp1_ = NULL;
	FILE* _tmp2_;
	ValaCodeContext* _tmp6_;
	ValaCodeContext* _tmp7_;
	ValaCodeContext* _tmp8_;
	GList* _tmp9_;
	guint _tmp10_ = 0U;
	GList* _tmp17_;
	FILE* _tmp21_;
	const gchar* _tmp22_;
	FILE* _tmp23_;
	const gchar* _tmp24_;
	FILE* _tmp25_;
	const gchar* _tmp26_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (filename != NULL);
	_tmp0_ = filename;
	_tmp1_ = fopen (_tmp0_, "w");
	_fclose0 (self->priv->stream);
	self->priv->stream = _tmp1_;
	_tmp2_ = self->priv->stream;
	if (_tmp2_ == NULL) {
		const gchar* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		_tmp3_ = filename;
		_tmp4_ = g_strdup_printf ("Cannot open %s for writing", _tmp3_);
		_tmp5_ = _tmp4_;
		g_error ("cxxwriter.vala:409: %s", _tmp5_);
		_g_free0 (_tmp5_);
	}
	_tmp6_ = context;
	_tmp7_ = _vala_code_context_ref0 (_tmp6_);
	_vala_code_context_unref0 (self->priv->context);
	self->priv->context = _tmp7_;
	_tmp8_ = context;
	vala_code_context_accept (_tmp8_, (ValaCodeVisitor*) self);
	_tmp9_ = self->includefiles;
	_tmp10_ = g_list_length (_tmp9_);
	if (_tmp10_ > ((guint) 0)) {
		FILE* _tmp11_;
		GList* _tmp12_;
		FILE* _tmp16_;
		_tmp11_ = self->priv->stream;
		fprintf (_tmp11_, "extern \"C\" {\n");
		_tmp12_ = self->includefiles;
		{
			GList* inc_collection = NULL;
			GList* inc_it = NULL;
			inc_collection = _tmp12_;
			for (inc_it = inc_collection; inc_it != NULL; inc_it = inc_it->next) {
				gchar* _tmp13_;
				gchar* inc = NULL;
				_tmp13_ = g_strdup ((const gchar*) inc_it->data);
				inc = _tmp13_;
				{
					FILE* _tmp14_;
					const gchar* _tmp15_;
					_tmp14_ = self->priv->stream;
					_tmp15_ = inc;
					fprintf (_tmp14_, "#include <%s>\n", _tmp15_);
					_g_free0 (inc);
				}
			}
		}
		_tmp16_ = self->priv->stream;
		fprintf (_tmp16_, "}\n#include <vector>\n");
	}
	_tmp17_ = self->includefiles;
	{
		GList* inc_collection = NULL;
		GList* inc_it = NULL;
		inc_collection = _tmp17_;
		for (inc_it = inc_collection; inc_it != NULL; inc_it = inc_it->next) {
			gchar* _tmp18_;
			gchar* inc = NULL;
			_tmp18_ = g_strdup ((const gchar*) inc_it->data);
			inc = _tmp18_;
			{
				FILE* _tmp19_;
				const gchar* _tmp20_;
				_tmp19_ = self->priv->stream;
				_tmp20_ = inc;
				fprintf (_tmp19_, "#include <%s>\n", _tmp20_);
				_g_free0 (inc);
			}
		}
	}
	_tmp21_ = self->priv->stream;
	_tmp22_ = self->priv->enums;
	fprintf (_tmp21_, "%s\n", _tmp22_);
	_tmp23_ = self->priv->stream;
	_tmp24_ = self->priv->statics;
	fprintf (_tmp23_, "%s\n", _tmp24_);
	_tmp25_ = self->priv->stream;
	_tmp26_ = self->priv->extends;
	fprintf (_tmp25_, "%s\n", _tmp26_);
	_fclose0 (self->priv->stream);
	self->priv->stream = NULL;
}


static void cxx_writer_class_init (CxxWriterClass * klass) {
	cxx_writer_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->finalize = cxx_writer_finalize;
	g_type_class_add_private (klass, sizeof (CxxWriterPrivate));
	VALA_CODE_VISITOR_CLASS (klass)->visit_source_file = cxx_writer_real_visit_source_file;
	VALA_CODE_VISITOR_CLASS (klass)->visit_namespace = cxx_writer_real_visit_namespace;
}


static void cxx_writer_instance_init (CxxWriter * self) {
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	self->priv = CXX_WRITER_GET_PRIVATE (self);
	_tmp0_ = g_str_hash;
	_tmp1_ = g_str_equal;
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, NULL);
	self->priv->defined_classes = _tmp2_;
}


static void cxx_writer_finalize (ValaCodeVisitor* obj) {
	CxxWriter * self;
	self = CXX_WRITER (obj);
	_g_free0 (self->pkgname);
	self->files = (_vala_array_free (self->files, self->files_length1, (GDestroyNotify) g_free), NULL);
	__g_list_free__g_free0_0 (self->includefiles);
	__g_list_free__vala_code_node_unref0_0 (self->methods);
	_vala_code_context_unref0 (self->priv->context);
	_fclose0 (self->priv->stream);
	_g_free0 (self->priv->classname);
	_g_free0 (self->priv->classcname);
	_g_free0 (self->priv->externs);
	_g_free0 (self->priv->statics);
	_g_free0 (self->priv->extends);
	_g_free0 (self->priv->enums);
	_g_free0 (self->priv->vectors);
	_g_free0 (self->priv->nspace);
	_g_free0 (self->priv->modulename);
	_g_hash_table_unref0 (self->priv->defined_classes);
	VALA_CODE_VISITOR_CLASS (cxx_writer_parent_class)->finalize (obj);
}


GType cxx_writer_get_type (void) {
	static volatile gsize cxx_writer_type_id__volatile = 0;
	if (g_once_init_enter (&cxx_writer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CxxWriterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cxx_writer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CxxWriter), 0, (GInstanceInitFunc) cxx_writer_instance_init, NULL };
		GType cxx_writer_type_id;
		cxx_writer_type_id = g_type_register_static (VALA_TYPE_CODE_VISITOR, "CxxWriter", &g_define_type_info, 0);
		g_once_init_leave (&cxx_writer_type_id__volatile, cxx_writer_type_id);
	}
	return cxx_writer_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



