/* girwriter.c generated by valac 0.13.1.44-726e, the Vala compiler
 * generated from girwriter.vala, do not modify */

/* Copyleft 2011 -- pancake // nopcode.org */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <valagee.h>


#define TYPE_GIR_WRITER (gir_writer_get_type ())
#define GIR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GIR_WRITER, GirWriter))
#define GIR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GIR_WRITER, GirWriterClass))
#define IS_GIR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GIR_WRITER))
#define IS_GIR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GIR_WRITER))
#define GIR_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GIR_WRITER, GirWriterClass))

typedef struct _GirWriter GirWriter;
typedef struct _GirWriterClass GirWriterClass;
typedef struct _GirWriterPrivate GirWriterPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define __g_list_free__vala_code_node_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__vala_code_node_unref0_ (var), NULL)))
#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_source_reference_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_reference_unref (var), NULL)))

struct _GirWriter {
	ValaCodeVisitor parent_instance;
	GirWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gboolean show_externs;
	gboolean glib_mode;
	gboolean cxx_mode;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _GirWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _GirWriterPrivate {
	ValaCodeContext* context;
	FILE* stream;
	gchar* classname;
	gchar* classcname;
	gchar* externs;
	gchar* statics;
	gchar* extends;
	gchar* enums;
	gchar* vectors;
	gchar* nspace;
	gchar* modulename;
};


static gpointer gir_writer_parent_class = NULL;

GType gir_writer_get_type (void) G_GNUC_CONST;
#define GIR_WRITER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GIR_WRITER, GirWriterPrivate))
enum  {
	GIR_WRITER_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
static void _vala_code_node_unref0_ (gpointer var);
static void _g_list_free__vala_code_node_unref0_ (GList* self);
GirWriter* gir_writer_new (const gchar* name);
GirWriter* gir_writer_construct (GType object_type, const gchar* name);
static gchar* gir_writer_get_alias (GirWriter* self, const gchar* name);
void valabind_compiler_warning (const gchar* msg);
static gchar* gir_writer_get_ctype (GirWriter* self, const gchar* _type);
void valabind_compiler_error (const gchar* msg);
static inline gboolean gir_writer_is_generic (GirWriter* self, const gchar* type);
static gboolean gir_writer_is_target_file (GirWriter* self, const gchar* path);
static void gir_writer_real_visit_source_file (ValaCodeVisitor* base, ValaSourceFile* source);
void gir_writer_process_includes (GirWriter* self, ValaSymbol* s);
void gir_writer_walk_field (GirWriter* self, ValaField* f);
void gir_writer_walk_struct (GirWriter* self, const gchar* pfx, ValaStruct* s);
void gir_writer_walk_method (GirWriter* self, ValaMethod* m);
void gir_writer_walk_class (GirWriter* self, const gchar* pfx, ValaClass* c);
void gir_writer_walk_enum (GirWriter* self, ValaEnum* e);
static void gir_writer_real_visit_namespace (ValaCodeVisitor* base, ValaNamespace* ns);
void gir_writer_write_file (GirWriter* self, ValaCodeContext* context, const gchar* filename);
static void gir_writer_finalize (ValaCodeVisitor* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


static void _vala_code_node_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL));
}


static void _g_list_free__vala_code_node_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _vala_code_node_unref0_, NULL);
	g_list_free (self);
}


GirWriter* gir_writer_construct (GType object_type, const gchar* name) {
	GirWriter* self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_val_if_fail (name != NULL, NULL);
	self = (GirWriter*) vala_code_visitor_construct (object_type);
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->enums);
	self->priv->enums = _tmp0_;
	_tmp1_ = g_strdup ("");
	_g_free0 (self->priv->statics);
	self->priv->statics = _tmp1_;
	_tmp2_ = g_strdup ("");
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp2_;
	_tmp3_ = g_strdup ("");
	_g_free0 (self->priv->extends);
	self->priv->extends = _tmp3_;
	_tmp4_ = g_strdup ("");
	_g_free0 (self->priv->vectors);
	self->priv->vectors = _tmp4_;
	_tmp5_ = g_strdup ("");
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp5_;
	_tmp6_ = name;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->priv->modulename);
	self->priv->modulename = _tmp7_;
	__g_list_free__g_free0_0 (self->includefiles);
	self->includefiles = NULL;
	return self;
}


GirWriter* gir_writer_new (const gchar* name) {
	return gir_writer_construct (TYPE_GIR_WRITER, name);
}


static gchar* gir_writer_get_alias (GirWriter* self, const gchar* name) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* oname;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GQuark _tmp5_ = 0U;
	static GQuark _tmp4_label0 = 0;
	static GQuark _tmp4_label1 = 0;
	static GQuark _tmp4_label2 = 0;
	static GQuark _tmp4_label3 = 0;
	static GQuark _tmp4_label4 = 0;
	static GQuark _tmp4_label5 = 0;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	oname = _tmp1_;
	_tmp2_ = name;
	_tmp3_ = _tmp2_;
	_tmp5_ = (NULL == _tmp3_) ? 0 : g_quark_from_string (_tmp3_);
	if (_tmp5_ == ((0 != _tmp4_label0) ? _tmp4_label0 : (_tmp4_label0 = g_quark_from_static_string ("cmd")))) {
		switch (0) {
			default:
			{
				name = "_cmd";
				break;
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label1) ? _tmp4_label1 : (_tmp4_label1 = g_quark_from_static_string ("def")))) {
		switch (0) {
			default:
			{
				name = "_def";
				break;
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label2) ? _tmp4_label2 : (_tmp4_label2 = g_quark_from_static_string ("print")))) {
		switch (0) {
			default:
			{
				name = "_print";
				break;
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label3) ? _tmp4_label3 : (_tmp4_label3 = g_quark_from_static_string ("del")))) {
		switch (0) {
			default:
			{
				name = "_del";
				break;
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label4) ? _tmp4_label4 : (_tmp4_label4 = g_quark_from_static_string ("from")))) {
		switch (0) {
			default:
			{
				name = "_from";
				break;
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label5) ? _tmp4_label5 : (_tmp4_label5 = g_quark_from_static_string ("continue")))) {
		switch (0) {
			default:
			{
				name = "cont";
				break;
			}
		}
	}
	_tmp6_ = name;
	_tmp7_ = oname;
	if (g_strcmp0 (_tmp6_, _tmp7_) != 0) {
		const gchar* _tmp8_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		_tmp8_ = self->priv->classname;
		_tmp9_ = oname;
		_tmp10_ = self->priv->classname;
		_tmp11_ = name;
		_tmp12_ = g_strdup_printf ("%s.%s method renamed to %s.%s", _tmp8_, _tmp9_, _tmp10_, _tmp11_);
		_tmp13_ = _tmp12_;
		valabind_compiler_warning (_tmp13_);
		_g_free0 (_tmp13_);
	}
	_tmp14_ = name;
	_tmp15_ = g_strdup (_tmp14_);
	result = _tmp15_;
	_g_free0 (oname);
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_ = 0;
		gint _tmp8_;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_;
		glong _tmp14_;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_;
		glong _tmp17_;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		const gchar* _tmp9_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch2_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch2_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp8_;
		result = _tmp9_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally2;
	__catch2_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _result_;
	gchar* _tmp3_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_;
	glong string_length;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static gchar* gir_writer_get_ctype (GirWriter* self, const gchar* _type) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* type;
	gchar* iter_type;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	const gchar* _tmp13_;
	gchar* _tmp14_ = NULL;
	const gchar* _tmp15_;
	gboolean _tmp16_ = FALSE;
	const gchar* _tmp43_;
	gchar* _tmp44_ = NULL;
	const gchar* _tmp45_;
	const gchar* _tmp46_;
	GQuark _tmp48_ = 0U;
	static GQuark _tmp47_label0 = 0;
	static GQuark _tmp47_label1 = 0;
	static GQuark _tmp47_label2 = 0;
	static GQuark _tmp47_label3 = 0;
	static GQuark _tmp47_label4 = 0;
	static GQuark _tmp47_label5 = 0;
	static GQuark _tmp47_label6 = 0;
	static GQuark _tmp47_label7 = 0;
	static GQuark _tmp47_label8 = 0;
	static GQuark _tmp47_label9 = 0;
	static GQuark _tmp47_label10 = 0;
	static GQuark _tmp47_label11 = 0;
	static GQuark _tmp47_label12 = 0;
	static GQuark _tmp47_label13 = 0;
	static GQuark _tmp47_label14 = 0;
	static GQuark _tmp47_label15 = 0;
	static GQuark _tmp47_label16 = 0;
	static GQuark _tmp47_label17 = 0;
	static GQuark _tmp47_label18 = 0;
	static GQuark _tmp47_label19 = 0;
	static GQuark _tmp47_label20 = 0;
	static GQuark _tmp47_label21 = 0;
	static GQuark _tmp47_label22 = 0;
	static GQuark _tmp47_label23 = 0;
	static GQuark _tmp47_label24 = 0;
	static GQuark _tmp47_label25 = 0;
	static GQuark _tmp47_label26 = 0;
	static GQuark _tmp47_label27 = 0;
	static GQuark _tmp47_label28 = 0;
	static GQuark _tmp47_label29 = 0;
	static GQuark _tmp47_label30 = 0;
	static GQuark _tmp47_label31 = 0;
	static GQuark _tmp47_label32 = 0;
	const gchar* _tmp78_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (_type != NULL, NULL);
	_tmp0_ = _type;
	_tmp1_ = g_strdup (_tmp0_);
	type = _tmp1_;
	iter_type = NULL;
	_tmp2_ = type;
	if (g_strcmp0 (_tmp2_, "null") == 0) {
		valabind_compiler_error ("Cannot resolve type");
	}
	_tmp3_ = type;
	_tmp4_ = self->priv->nspace;
	_tmp5_ = g_str_has_prefix (_tmp3_, _tmp4_);
	if (_tmp5_) {
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		gint _tmp8_ = 0;
		gint _tmp9_;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_;
		gchar* _tmp12_;
		_tmp6_ = type;
		_tmp7_ = self->priv->nspace;
		_tmp8_ = strlen (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = string_substring (_tmp6_, (glong) _tmp9_, (glong) (-1));
		_tmp11_ = _tmp10_;
		_tmp12_ = g_strconcat (_tmp11_, "*", NULL);
		_g_free0 (type);
		type = _tmp12_;
		_g_free0 (_tmp11_);
	}
	_tmp13_ = type;
	_tmp14_ = string_replace (_tmp13_, ".", "");
	_g_free0 (type);
	type = _tmp14_;
	_tmp15_ = type;
	_tmp16_ = gir_writer_is_generic (self, _tmp15_);
	if (_tmp16_) {
		const gchar* _tmp17_;
		gint _tmp18_ = 0;
		gint ptr;
		gchar* _tmp19_ = NULL;
		gint _tmp20_;
		const gchar* _tmp29_;
		gchar* _tmp30_;
		const gchar* _tmp31_;
		gchar* _tmp32_ = NULL;
		const gchar* _tmp33_;
		gchar* _tmp34_ = NULL;
		const gchar* _tmp35_;
		const gchar* _tmp36_;
		gchar* _tmp37_ = NULL;
		const gchar* _tmp38_;
		gchar** _tmp39_;
		gchar** _tmp40_ = NULL;
		gchar** _tmp41_;
		gint _tmp41__length1;
		gchar* _tmp42_;
		_tmp17_ = type;
		_tmp18_ = string_index_of (_tmp17_, "<", 0);
		ptr = _tmp18_;
		_tmp20_ = ptr;
		if (_tmp20_ == (-1)) {
			const gchar* _tmp21_;
			gchar* _tmp22_;
			_tmp21_ = type;
			_tmp22_ = g_strdup (_tmp21_);
			_g_free0 (_tmp19_);
			_tmp19_ = _tmp22_;
		} else {
			const gchar* _tmp23_;
			gint _tmp24_;
			const gchar* _tmp25_;
			gint _tmp26_ = 0;
			gint _tmp27_;
			gchar* _tmp28_ = NULL;
			_tmp23_ = type;
			_tmp24_ = ptr;
			_tmp25_ = type;
			_tmp26_ = strlen (_tmp25_);
			_tmp27_ = _tmp26_;
			_tmp28_ = string_slice (_tmp23_, (glong) _tmp24_, (glong) _tmp27_);
			_g_free0 (_tmp19_);
			_tmp19_ = _tmp28_;
		}
		_tmp29_ = _tmp19_;
		_tmp30_ = g_strdup (_tmp29_);
		_g_free0 (iter_type);
		iter_type = _tmp30_;
		_tmp31_ = iter_type;
		_tmp32_ = string_replace (_tmp31_, "<", "");
		_g_free0 (iter_type);
		iter_type = _tmp32_;
		_tmp33_ = iter_type;
		_tmp34_ = string_replace (_tmp33_, ">", "");
		_g_free0 (iter_type);
		iter_type = _tmp34_;
		_tmp35_ = iter_type;
		_tmp36_ = self->priv->nspace;
		_tmp37_ = string_replace (_tmp35_, _tmp36_, "");
		_g_free0 (iter_type);
		iter_type = _tmp37_;
		_tmp38_ = type;
		_tmp40_ = _tmp39_ = g_strsplit (_tmp38_, "<", 2);
		_tmp41_ = _tmp40_;
		_tmp41__length1 = _vala_array_length (_tmp39_);
		_tmp42_ = g_strdup (_tmp41_[0]);
		_g_free0 (type);
		type = _tmp42_;
		_tmp41_ = (_vala_array_free (_tmp41_, _tmp41__length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (_tmp19_);
	}
	_tmp43_ = type;
	_tmp44_ = string_replace (_tmp43_, "?", "");
	_g_free0 (type);
	type = _tmp44_;
	_tmp45_ = type;
	_tmp46_ = _tmp45_;
	_tmp48_ = (NULL == _tmp46_) ? 0 : g_quark_from_string (_tmp46_);
	if (_tmp48_ == ((0 != _tmp47_label0) ? _tmp47_label0 : (_tmp47_label0 = g_quark_from_static_string ("const gchar*")))) {
		switch (0) {
			default:
			{
				gchar* _tmp49_;
				_tmp49_ = g_strdup ("const char*");
				result = _tmp49_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label1) ? _tmp47_label1 : (_tmp47_label1 = g_quark_from_static_string ("G")))) || (_tmp48_ == ((0 != _tmp47_label2) ? _tmp47_label2 : (_tmp47_label2 = g_quark_from_static_string ("gconstpointer"))))) || (_tmp48_ == ((0 != _tmp47_label3) ? _tmp47_label3 : (_tmp47_label3 = g_quark_from_static_string ("gpointer"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp50_;
				_tmp50_ = g_strdup ("void*");
				result = _tmp50_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label4) ? _tmp47_label4 : (_tmp47_label4 = g_quark_from_static_string ("gdouble")))) {
		switch (0) {
			default:
			{
				gchar* _tmp51_;
				_tmp51_ = g_strdup ("double");
				result = _tmp51_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label5) ? _tmp47_label5 : (_tmp47_label5 = g_quark_from_static_string ("gfloat")))) {
		switch (0) {
			default:
			{
				gchar* _tmp52_;
				_tmp52_ = g_strdup ("float");
				result = _tmp52_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label6) ? _tmp47_label6 : (_tmp47_label6 = g_quark_from_static_string ("break")))) {
		switch (0) {
			default:
			{
				gchar* _tmp53_;
				_tmp53_ = g_strdup ("_break");
				result = _tmp53_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label7) ? _tmp47_label7 : (_tmp47_label7 = g_quark_from_static_string ("ut8")))) || (_tmp48_ == ((0 != _tmp47_label8) ? _tmp47_label8 : (_tmp47_label8 = g_quark_from_static_string ("uint8"))))) || (_tmp48_ == ((0 != _tmp47_label9) ? _tmp47_label9 : (_tmp47_label9 = g_quark_from_static_string ("guint8"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp54_;
				_tmp54_ = g_strdup ("unsigned char");
				result = _tmp54_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label10) ? _tmp47_label10 : (_tmp47_label10 = g_quark_from_static_string ("gchar**")))) {
		switch (0) {
			default:
			{
				gchar* _tmp55_;
				_tmp55_ = g_strdup ("char **");
				result = _tmp55_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label11) ? _tmp47_label11 : (_tmp47_label11 = g_quark_from_static_string ("gchar")))) {
		switch (0) {
			default:
			{
				gchar* _tmp56_;
				_tmp56_ = g_strdup ("char");
				result = _tmp56_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label12) ? _tmp47_label12 : (_tmp47_label12 = g_quark_from_static_string ("gchar*")))) || (_tmp48_ == ((0 != _tmp47_label13) ? _tmp47_label13 : (_tmp47_label13 = g_quark_from_static_string ("string"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp57_;
				_tmp57_ = g_strdup ("string");
				result = _tmp57_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label14) ? _tmp47_label14 : (_tmp47_label14 = g_quark_from_static_string ("gint")))) {
		switch (0) {
			default:
			{
				gchar* _tmp58_;
				_tmp58_ = g_strdup ("int");
				result = _tmp58_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label15) ? _tmp47_label15 : (_tmp47_label15 = g_quark_from_static_string ("glong")))) {
		switch (0) {
			default:
			{
				gchar* _tmp59_;
				_tmp59_ = g_strdup ("long");
				result = _tmp59_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label16) ? _tmp47_label16 : (_tmp47_label16 = g_quark_from_static_string ("st64")))) || (_tmp48_ == ((0 != _tmp47_label17) ? _tmp47_label17 : (_tmp47_label17 = g_quark_from_static_string ("int64"))))) || (_tmp48_ == ((0 != _tmp47_label18) ? _tmp47_label18 : (_tmp47_label18 = g_quark_from_static_string ("gint64"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp60_;
				_tmp60_ = g_strdup ("long long");
				result = _tmp60_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label19) ? _tmp47_label19 : (_tmp47_label19 = g_quark_from_static_string ("ut64")))) || (_tmp48_ == ((0 != _tmp47_label20) ? _tmp47_label20 : (_tmp47_label20 = g_quark_from_static_string ("uint64"))))) || (_tmp48_ == ((0 != _tmp47_label21) ? _tmp47_label21 : (_tmp47_label21 = g_quark_from_static_string ("guint64"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp61_;
				_tmp61_ = g_strdup ("unsigned long long");
				result = _tmp61_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label22) ? _tmp47_label22 : (_tmp47_label22 = g_quark_from_static_string ("uint8*")))) || (_tmp48_ == ((0 != _tmp47_label23) ? _tmp47_label23 : (_tmp47_label23 = g_quark_from_static_string ("guint8*"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp62_;
				_tmp62_ = g_strdup ("unsigned char*");
				result = _tmp62_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label24) ? _tmp47_label24 : (_tmp47_label24 = g_quark_from_static_string ("guint16")))) || (_tmp48_ == ((0 != _tmp47_label25) ? _tmp47_label25 : (_tmp47_label25 = g_quark_from_static_string ("uint16"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp63_;
				_tmp63_ = g_strdup ("unsigned short");
				result = _tmp63_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (((_tmp48_ == ((0 != _tmp47_label26) ? _tmp47_label26 : (_tmp47_label26 = g_quark_from_static_string ("ut32")))) || (_tmp48_ == ((0 != _tmp47_label27) ? _tmp47_label27 : (_tmp47_label27 = g_quark_from_static_string ("uint32"))))) || (_tmp48_ == ((0 != _tmp47_label28) ? _tmp47_label28 : (_tmp47_label28 = g_quark_from_static_string ("guint32"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp64_;
				_tmp64_ = g_strdup ("unsigned int");
				result = _tmp64_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if ((_tmp48_ == ((0 != _tmp47_label29) ? _tmp47_label29 : (_tmp47_label29 = g_quark_from_static_string ("bool")))) || (_tmp48_ == ((0 != _tmp47_label30) ? _tmp47_label30 : (_tmp47_label30 = g_quark_from_static_string ("gboolean"))))) {
		switch (0) {
			default:
			{
				gchar* _tmp65_;
				_tmp65_ = g_strdup ("gboolean");
				result = _tmp65_;
				_g_free0 (iter_type);
				_g_free0 (type);
				return result;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label31) ? _tmp47_label31 : (_tmp47_label31 = g_quark_from_static_string ("RFList")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp66_;
				_tmp66_ = iter_type;
				if (_tmp66_ != NULL) {
					const gchar* _tmp67_;
					gchar* _tmp68_;
					gchar* _tmp69_;
					gchar* _tmp70_;
					gchar* _tmp71_;
					_tmp67_ = iter_type;
					_tmp68_ = g_strconcat ("std::vector<", _tmp67_, NULL);
					_tmp69_ = _tmp68_;
					_tmp70_ = g_strconcat (_tmp69_, ">", NULL);
					_tmp71_ = _tmp70_;
					_g_free0 (_tmp69_);
					result = _tmp71_;
					_g_free0 (iter_type);
					_g_free0 (type);
					return result;
				}
				break;
			}
		}
	} else if (_tmp48_ == ((0 != _tmp47_label32) ? _tmp47_label32 : (_tmp47_label32 = g_quark_from_static_string ("RList")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp72_;
				_tmp72_ = iter_type;
				if (_tmp72_ != NULL) {
					const gchar* _tmp73_;
					gchar* _tmp74_;
					gchar* _tmp75_;
					gchar* _tmp76_;
					gchar* _tmp77_;
					_tmp73_ = iter_type;
					_tmp74_ = g_strconcat ("std::vector<", _tmp73_, NULL);
					_tmp75_ = _tmp74_;
					_tmp76_ = g_strconcat (_tmp75_, ">", NULL);
					_tmp77_ = _tmp76_;
					_g_free0 (_tmp75_);
					result = _tmp77_;
					_g_free0 (iter_type);
					_g_free0 (type);
					return result;
				}
				break;
			}
		}
	}
	_tmp78_ = type;
	result = _tmp78_;
	_g_free0 (iter_type);
	return result;
}


static gboolean gir_writer_is_target_file (GirWriter* self, const gchar* path) {
	gboolean result = FALSE;
	gchar** _tmp0_;
	gint _tmp0__length1;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	_tmp0_ = self->files;
	_tmp0__length1 = self->files_length1;
	{
		gchar** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
		file_collection = _tmp0_;
		file_collection_length1 = _tmp0__length1;
		for (file_it = 0; file_it < _tmp0__length1; file_it = file_it + 1) {
			gchar* _tmp1_;
			gchar* file = NULL;
			_tmp1_ = g_strdup (file_collection[file_it]);
			file = _tmp1_;
			{
				const gchar* _tmp2_;
				const gchar* _tmp3_;
				_tmp2_ = file;
				_tmp3_ = path;
				if (g_strcmp0 (_tmp2_, _tmp3_) == 0) {
					result = TRUE;
					_g_free0 (file);
					return result;
				}
				_g_free0 (file);
			}
		}
	}
	result = FALSE;
	return result;
}


static void gir_writer_real_visit_source_file (ValaCodeVisitor* base, ValaSourceFile* source) {
	GirWriter * self;
	ValaSourceFile* _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_;
	gboolean _tmp3_ = FALSE;
	self = (GirWriter*) base;
	g_return_if_fail (source != NULL);
	_tmp0_ = source;
	_tmp1_ = vala_source_file_get_filename (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = gir_writer_is_target_file (self, _tmp2_);
	if (_tmp3_) {
		ValaSourceFile* _tmp4_;
		_tmp4_ = source;
		vala_source_file_accept_children (_tmp4_, (ValaCodeVisitor*) self);
	}
}


void gir_writer_process_includes (GirWriter* self, ValaSymbol* s) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (s != NULL);
	{
		ValaSymbol* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _foo_list;
		ValaList* _tmp2_;
		gint _tmp3_ = 0;
		gint _tmp4_;
		gint _foo_size;
		gint _foo_index;
		_tmp0_ = s;
		_tmp1_ = vala_symbol_get_cheader_filenames (_tmp0_);
		_foo_list = _tmp1_;
		_tmp2_ = _foo_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_foo_size = _tmp4_;
		_foo_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			gchar* foo;
			gboolean include;
			GList* _tmp11_;
			gboolean _tmp15_;
			_tmp5_ = _foo_index;
			_foo_index = _tmp5_ + 1;
			_tmp6_ = _foo_index;
			_tmp7_ = _foo_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _foo_list;
			_tmp9_ = _foo_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			foo = (gchar*) _tmp10_;
			include = TRUE;
			_tmp11_ = self->includefiles;
			{
				GList* inc_collection = NULL;
				GList* inc_it = NULL;
				inc_collection = _tmp11_;
				for (inc_it = inc_collection; inc_it != NULL; inc_it = inc_it->next) {
					gchar* _tmp12_;
					gchar* inc = NULL;
					_tmp12_ = g_strdup ((const gchar*) inc_it->data);
					inc = _tmp12_;
					{
						const gchar* _tmp13_;
						const gchar* _tmp14_;
						_tmp13_ = inc;
						_tmp14_ = foo;
						if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
							include = FALSE;
							_g_free0 (inc);
							break;
						}
						_g_free0 (inc);
					}
				}
			}
			_tmp15_ = include;
			if (_tmp15_) {
				const gchar* _tmp16_;
				gchar* _tmp17_;
				_tmp16_ = foo;
				_tmp17_ = g_strdup (_tmp16_);
				self->includefiles = g_list_prepend (self->includefiles, _tmp17_);
			}
			_g_free0 (foo);
		}
		_vala_iterable_unref0 (_foo_list);
	}
}


void gir_writer_walk_field (GirWriter* self, ValaField* f) {
	ValaField* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* name;
	ValaField* _tmp2_;
	ValaDataType* _tmp3_ = NULL;
	ValaDataType* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* type;
	const gchar* _tmp6_;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (f != NULL);
	_tmp0_ = f;
	_tmp1_ = vala_field_get_cname (_tmp0_);
	name = _tmp1_;
	_tmp2_ = f;
	_tmp3_ = vala_variable_get_variable_type ((ValaVariable*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_code_node_to_string ((ValaCodeNode*) _tmp4_);
	type = _tmp5_;
	_tmp6_ = type;
	_tmp7_ = gir_writer_get_ctype (self, _tmp6_);
	_g_free0 (type);
	type = _tmp7_;
	_tmp8_ = self->priv->externs;
	_tmp9_ = name;
	_tmp10_ = g_strconcat ("    <field name=\"", _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, "\" type=\"", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = type;
	_tmp15_ = g_strconcat (_tmp13_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp16_, "\"/>\n", NULL);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp8_, _tmp18_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp19_;
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (type);
	_g_free0 (name);
}


void gir_writer_walk_struct (GirWriter* self, const gchar* pfx, ValaStruct* s) {
	ValaStruct* _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* name;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (pfx != NULL);
	g_return_if_fail (s != NULL);
	_tmp0_ = s;
	_tmp1_ = vala_symbol_get_name ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	name = _tmp3_;
	_tmp4_ = self->priv->externs;
	_tmp5_ = name;
	_tmp6_ = g_strconcat ("  <struct name=\"", _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp7_, "\">\n", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp4_, _tmp9_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp10_;
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	{
		ValaStruct* _tmp11_;
		ValaList* _tmp12_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp13_;
		gint _tmp14_ = 0;
		gint _tmp15_;
		gint _m_size;
		gint _m_index;
		_tmp11_ = s;
		_tmp12_ = vala_struct_get_methods (_tmp11_);
		_m_list = _tmp12_;
		_tmp13_ = _m_list;
		_tmp14_ = vala_collection_get_size ((ValaCollection*) _tmp13_);
		_tmp15_ = _tmp14_;
		_m_size = _tmp15_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp16_;
			gint _tmp17_;
			gint _tmp18_;
			ValaList* _tmp19_;
			gint _tmp20_;
			gpointer _tmp21_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp22_;
			_tmp16_ = _m_index;
			_m_index = _tmp16_ + 1;
			_tmp17_ = _m_index;
			_tmp18_ = _m_size;
			if (!(_tmp17_ < _tmp18_)) {
				break;
			}
			_tmp19_ = _m_list;
			_tmp20_ = _m_index;
			_tmp21_ = vala_list_get (_tmp19_, _tmp20_);
			m = (ValaMethod*) _tmp21_;
			_tmp22_ = m;
			gir_writer_walk_method (self, _tmp22_);
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	{
		ValaStruct* _tmp23_;
		ValaList* _tmp24_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp25_;
		gint _tmp26_ = 0;
		gint _tmp27_;
		gint _f_size;
		gint _f_index;
		_tmp23_ = s;
		_tmp24_ = vala_struct_get_fields (_tmp23_);
		_f_list = _tmp24_;
		_tmp25_ = _f_list;
		_tmp26_ = vala_collection_get_size ((ValaCollection*) _tmp25_);
		_tmp27_ = _tmp26_;
		_f_size = _tmp27_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp28_;
			gint _tmp29_;
			gint _tmp30_;
			ValaList* _tmp31_;
			gint _tmp32_;
			gpointer _tmp33_ = NULL;
			ValaField* f;
			ValaField* _tmp34_;
			_tmp28_ = _f_index;
			_f_index = _tmp28_ + 1;
			_tmp29_ = _f_index;
			_tmp30_ = _f_size;
			if (!(_tmp29_ < _tmp30_)) {
				break;
			}
			_tmp31_ = _f_list;
			_tmp32_ = _f_index;
			_tmp33_ = vala_list_get (_tmp31_, _tmp32_);
			f = (ValaField*) _tmp33_;
			_tmp34_ = f;
			gir_writer_walk_field (self, _tmp34_);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	_tmp35_ = self->priv->externs;
	_tmp36_ = g_strconcat (_tmp35_, "  </struct>\n", NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp36_;
	_g_free0 (name);
}


void gir_writer_walk_class (GirWriter* self, const gchar* pfx, ValaClass* c) {
	const gchar* _tmp15_;
	ValaClass* _tmp16_;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	ValaClass* _tmp20_;
	gchar* _tmp21_ = NULL;
	ValaClass* _tmp22_;
	gboolean _tmp23_;
	const gchar* _tmp27_;
	const gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	const gchar* _tmp70_;
	gchar* _tmp71_;
	gchar* _tmp72_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (pfx != NULL);
	g_return_if_fail (c != NULL);
	{
		ValaClass* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _k_list;
		ValaList* _tmp2_;
		gint _tmp3_ = 0;
		gint _tmp4_;
		gint _k_size;
		gint _k_index;
		_tmp0_ = c;
		_tmp1_ = vala_class_get_classes (_tmp0_);
		_k_list = _tmp1_;
		_tmp2_ = _k_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_k_size = _tmp4_;
		_k_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ValaClass* k;
			ValaClass* _tmp11_;
			const gchar* _tmp12_ = NULL;
			const gchar* _tmp13_;
			ValaClass* _tmp14_;
			_tmp5_ = _k_index;
			_k_index = _tmp5_ + 1;
			_tmp6_ = _k_index;
			_tmp7_ = _k_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _k_list;
			_tmp9_ = _k_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			k = (ValaClass*) _tmp10_;
			_tmp11_ = c;
			_tmp12_ = vala_symbol_get_name ((ValaSymbol*) _tmp11_);
			_tmp13_ = _tmp12_;
			_tmp14_ = k;
			gir_writer_walk_class (self, _tmp13_, _tmp14_);
			_vala_code_node_unref0 (k);
		}
		_vala_iterable_unref0 (_k_list);
	}
	_tmp15_ = pfx;
	_tmp16_ = c;
	_tmp17_ = vala_symbol_get_name ((ValaSymbol*) _tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp15_, _tmp18_, NULL);
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp19_;
	_tmp20_ = c;
	_tmp21_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) _tmp20_, FALSE);
	_g_free0 (self->priv->classcname);
	self->priv->classcname = _tmp21_;
	_tmp22_ = c;
	gir_writer_process_includes (self, (ValaSymbol*) _tmp22_);
	_tmp23_ = self->glib_mode;
	if (_tmp23_) {
		const gchar* _tmp24_;
		const gchar* _tmp25_;
		gchar* _tmp26_ = NULL;
		_tmp24_ = self->priv->nspace;
		_tmp25_ = self->priv->classname;
		_tmp26_ = g_strdup_printf ("%s%s", _tmp24_, _tmp25_);
		_g_free0 (self->priv->classname);
		self->priv->classname = _tmp26_;
	}
	_tmp27_ = self->priv->externs;
	_tmp28_ = self->priv->classname;
	_tmp29_ = g_strconcat ("  <object name=\"", _tmp28_, NULL);
	_tmp30_ = _tmp29_;
	_tmp31_ = g_strconcat (_tmp30_, "\">\n", NULL);
	_tmp32_ = _tmp31_;
	_tmp33_ = g_strconcat (_tmp27_, _tmp32_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp33_;
	_g_free0 (_tmp32_);
	_g_free0 (_tmp30_);
	{
		ValaClass* _tmp34_;
		ValaList* _tmp35_ = NULL;
		ValaList* _e_list;
		ValaList* _tmp36_;
		gint _tmp37_ = 0;
		gint _tmp38_;
		gint _e_size;
		gint _e_index;
		_tmp34_ = c;
		_tmp35_ = vala_class_get_enums (_tmp34_);
		_e_list = _tmp35_;
		_tmp36_ = _e_list;
		_tmp37_ = vala_collection_get_size ((ValaCollection*) _tmp36_);
		_tmp38_ = _tmp37_;
		_e_size = _tmp38_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp39_;
			gint _tmp40_;
			gint _tmp41_;
			ValaList* _tmp42_;
			gint _tmp43_;
			gpointer _tmp44_ = NULL;
			ValaEnum* e;
			ValaEnum* _tmp45_;
			_tmp39_ = _e_index;
			_e_index = _tmp39_ + 1;
			_tmp40_ = _e_index;
			_tmp41_ = _e_size;
			if (!(_tmp40_ < _tmp41_)) {
				break;
			}
			_tmp42_ = _e_list;
			_tmp43_ = _e_index;
			_tmp44_ = vala_list_get (_tmp42_, _tmp43_);
			e = (ValaEnum*) _tmp44_;
			_tmp45_ = e;
			gir_writer_walk_enum (self, _tmp45_);
			_vala_code_node_unref0 (e);
		}
		_vala_iterable_unref0 (_e_list);
	}
	{
		ValaClass* _tmp46_;
		ValaList* _tmp47_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp48_;
		gint _tmp49_ = 0;
		gint _tmp50_;
		gint _f_size;
		gint _f_index;
		_tmp46_ = c;
		_tmp47_ = vala_class_get_fields (_tmp46_);
		_f_list = _tmp47_;
		_tmp48_ = _f_list;
		_tmp49_ = vala_collection_get_size ((ValaCollection*) _tmp48_);
		_tmp50_ = _tmp49_;
		_f_size = _tmp50_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp51_;
			gint _tmp52_;
			gint _tmp53_;
			ValaList* _tmp54_;
			gint _tmp55_;
			gpointer _tmp56_ = NULL;
			ValaField* f;
			ValaField* _tmp57_;
			_tmp51_ = _f_index;
			_f_index = _tmp51_ + 1;
			_tmp52_ = _f_index;
			_tmp53_ = _f_size;
			if (!(_tmp52_ < _tmp53_)) {
				break;
			}
			_tmp54_ = _f_list;
			_tmp55_ = _f_index;
			_tmp56_ = vala_list_get (_tmp54_, _tmp55_);
			f = (ValaField*) _tmp56_;
			_tmp57_ = f;
			gir_writer_walk_field (self, _tmp57_);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	{
		ValaClass* _tmp58_;
		ValaList* _tmp59_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp60_;
		gint _tmp61_ = 0;
		gint _tmp62_;
		gint _m_size;
		gint _m_index;
		_tmp58_ = c;
		_tmp59_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) _tmp58_);
		_m_list = _tmp59_;
		_tmp60_ = _m_list;
		_tmp61_ = vala_collection_get_size ((ValaCollection*) _tmp60_);
		_tmp62_ = _tmp61_;
		_m_size = _tmp62_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp63_;
			gint _tmp64_;
			gint _tmp65_;
			ValaList* _tmp66_;
			gint _tmp67_;
			gpointer _tmp68_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp69_;
			_tmp63_ = _m_index;
			_m_index = _tmp63_ + 1;
			_tmp64_ = _m_index;
			_tmp65_ = _m_size;
			if (!(_tmp64_ < _tmp65_)) {
				break;
			}
			_tmp66_ = _m_list;
			_tmp67_ = _m_index;
			_tmp68_ = vala_list_get (_tmp66_, _tmp67_);
			m = (ValaMethod*) _tmp68_;
			_tmp69_ = m;
			gir_writer_walk_method (self, _tmp69_);
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	_tmp70_ = self->priv->externs;
	_tmp71_ = g_strconcat (_tmp70_, "  </object>\n", NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp71_;
	_tmp72_ = g_strdup ("");
	_g_free0 (self->priv->classname);
	self->priv->classname = _tmp72_;
}


void gir_writer_walk_enum (GirWriter* self, ValaEnum* e) {
	const gchar* _tmp0_;
	ValaEnum* _tmp1_;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* enumname;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* tmp;
	const gchar* _tmp37_;
	gchar* _tmp38_;
	const gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	gchar* _tmp43_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	_tmp0_ = self->priv->classname;
	_tmp1_ = e;
	_tmp2_ = vala_symbol_get_name ((ValaSymbol*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp0_, _tmp3_, NULL);
	enumname = _tmp4_;
	_tmp5_ = enumname;
	_tmp6_ = g_strconcat ("  <enum name=\"", _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp7_, "\">\n", NULL);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	tmp = _tmp9_;
	{
		ValaEnum* _tmp10_;
		ValaList* _tmp11_ = NULL;
		ValaList* _v_list;
		ValaList* _tmp12_;
		gint _tmp13_ = 0;
		gint _tmp14_;
		gint _v_size;
		gint _v_index;
		_tmp10_ = e;
		_tmp11_ = vala_enum_get_values (_tmp10_);
		_v_list = _tmp11_;
		_tmp12_ = _v_list;
		_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
		_tmp14_ = _tmp13_;
		_v_size = _tmp14_;
		_v_index = -1;
		while (TRUE) {
			gint _tmp15_;
			gint _tmp16_;
			gint _tmp17_;
			ValaList* _tmp18_;
			gint _tmp19_;
			gpointer _tmp20_ = NULL;
			ValaEnumValue* v;
			const gchar* _tmp21_;
			ValaEnum* _tmp22_;
			const gchar* _tmp23_ = NULL;
			const gchar* _tmp24_;
			gchar* _tmp25_;
			gchar* _tmp26_;
			gchar* _tmp27_;
			gchar* _tmp28_;
			ValaEnumValue* _tmp29_;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gchar* _tmp34_;
			gchar* _tmp35_;
			gchar* _tmp36_;
			_tmp15_ = _v_index;
			_v_index = _tmp15_ + 1;
			_tmp16_ = _v_index;
			_tmp17_ = _v_size;
			if (!(_tmp16_ < _tmp17_)) {
				break;
			}
			_tmp18_ = _v_list;
			_tmp19_ = _v_index;
			_tmp20_ = vala_list_get (_tmp18_, _tmp19_);
			v = (ValaEnumValue*) _tmp20_;
			_tmp21_ = tmp;
			_tmp22_ = e;
			_tmp23_ = vala_symbol_get_name ((ValaSymbol*) _tmp22_);
			_tmp24_ = _tmp23_;
			_tmp25_ = g_strconcat ("    <member name=\"", _tmp24_, NULL);
			_tmp26_ = _tmp25_;
			_tmp27_ = g_strconcat (_tmp26_, "\" value=\"", NULL);
			_tmp28_ = _tmp27_;
			_tmp29_ = v;
			_tmp30_ = vala_constant_get_cname ((ValaConstant*) _tmp29_);
			_tmp31_ = _tmp30_;
			_tmp32_ = g_strconcat (_tmp28_, _tmp31_, NULL);
			_tmp33_ = _tmp32_;
			_tmp34_ = g_strconcat (_tmp33_, "\"/>\n", NULL);
			_tmp35_ = _tmp34_;
			_tmp36_ = g_strconcat (_tmp21_, _tmp35_, NULL);
			_g_free0 (tmp);
			tmp = _tmp36_;
			_g_free0 (_tmp35_);
			_g_free0 (_tmp33_);
			_g_free0 (_tmp31_);
			_g_free0 (_tmp28_);
			_g_free0 (_tmp26_);
			_vala_code_node_unref0 (v);
		}
		_vala_iterable_unref0 (_v_list);
	}
	_tmp37_ = tmp;
	_tmp38_ = g_strconcat (_tmp37_, "  </enum>\n", NULL);
	_g_free0 (tmp);
	tmp = _tmp38_;
	_tmp39_ = tmp;
	_tmp40_ = g_strconcat (_tmp39_, "\n", NULL);
	_tmp41_ = _tmp40_;
	_tmp42_ = self->priv->enums;
	_tmp43_ = g_strconcat (_tmp41_, _tmp42_, NULL);
	_g_free0 (self->priv->enums);
	self->priv->enums = _tmp43_;
	_g_free0 (_tmp41_);
	_g_free0 (tmp);
	_g_free0 (enumname);
}


static inline gboolean gir_writer_is_generic (GirWriter* self, const gchar* type) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_;
	gboolean _tmp5_;
	gboolean _tmp8_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (type != NULL, FALSE);
	_tmp2_ = self->cxx_mode;
	if (_tmp2_) {
		const gchar* _tmp3_;
		gint _tmp4_ = 0;
		_tmp3_ = type;
		_tmp4_ = string_index_of (_tmp3_, "<", 0);
		_tmp1_ = _tmp4_ != (-1);
	} else {
		_tmp1_ = FALSE;
	}
	_tmp5_ = _tmp1_;
	if (_tmp5_) {
		const gchar* _tmp6_;
		gint _tmp7_ = 0;
		_tmp6_ = type;
		_tmp7_ = string_index_of (_tmp6_, ">", 0);
		_tmp0_ = _tmp7_ != (-1);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp8_ = _tmp0_;
	result = _tmp8_;
	return result;
}


static gpointer _vala_iterable_ref0 (gpointer self) {
	return self ? vala_iterable_ref (self) : NULL;
}


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


void gir_writer_walk_method (GirWriter* self, ValaMethod* m) {
	ValaMethod* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* cname;
	ValaMethod* _tmp2_;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* alias;
	gchar* ret = NULL;
	gchar* vret = NULL;
	gboolean void_return = FALSE;
	ValaMethod* _tmp6_;
	ValaMemberBinding _tmp7_ = 0;
	ValaMemberBinding _tmp8_;
	gboolean is_static;
	ValaMethod* _tmp9_;
	gboolean is_constructor;
	ValaMethod* _tmp10_;
	ValaDataType* _tmp11_ = NULL;
	ValaDataType* _tmp12_;
	gchar* _tmp13_ = NULL;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	const gchar* _tmp16_;
	gboolean _tmp17_ = FALSE;
	const gchar* _tmp26_;
	const gchar* _tmp30_;
	ValaMethod* _tmp31_;
	gboolean _tmp32_ = FALSE;
	const gchar* _tmp33_ = NULL;
	gboolean _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* type;
	gboolean _tmp37_ = FALSE;
	const gchar* _tmp38_;
	gboolean _tmp40_;
	gboolean _tmp42_;
	const gchar* _tmp44_;
	const gchar* _tmp45_;
	gchar* _tmp46_;
	gchar* _tmp47_;
	gchar* _tmp48_;
	gchar* _tmp49_;
	const gchar* _tmp50_;
	gchar* _tmp51_;
	gchar* _tmp52_;
	gchar* _tmp53_;
	gchar* _tmp54_;
	const gchar* _tmp55_;
	gchar* _tmp56_;
	gchar* _tmp57_;
	gchar* _tmp58_;
	gchar* _tmp59_;
	gchar* _tmp60_;
	gboolean _tmp61_;
	ValaMethod* _tmp73_;
	ValaList* _tmp74_ = NULL;
	ValaList* parameters;
	ValaList* _tmp75_;
	gint _tmp76_ = 0;
	gint _tmp77_;
	const gchar* _tmp130_;
	const gchar* _tmp131_;
	gchar* _tmp132_;
	gchar* _tmp133_;
	gchar* _tmp134_;
	gchar* _tmp135_;
	gchar* _tmp136_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (m != NULL);
	_tmp0_ = m;
	_tmp1_ = vala_method_get_cname (_tmp0_);
	cname = _tmp1_;
	_tmp2_ = m;
	_tmp3_ = vala_symbol_get_name ((ValaSymbol*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = gir_writer_get_alias (self, _tmp4_);
	alias = _tmp5_;
	_tmp6_ = m;
	_tmp7_ = vala_method_get_binding (_tmp6_);
	_tmp8_ = _tmp7_;
	is_static = (_tmp8_ & VALA_MEMBER_BINDING_STATIC) != 0;
	_tmp9_ = m;
	is_constructor = VALA_IS_CREATION_METHOD (_tmp9_);
	_tmp10_ = m;
	_tmp11_ = vala_method_get_return_type (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_code_node_to_string ((ValaCodeNode*) _tmp12_);
	_g_free0 (vret);
	vret = _tmp13_;
	_tmp14_ = vret;
	_tmp15_ = g_strdup (_tmp14_);
	_g_free0 (ret);
	ret = _tmp15_;
	_tmp16_ = ret;
	_tmp17_ = gir_writer_is_generic (self, _tmp16_);
	if (_tmp17_) {
		const gchar* _tmp18_;
		gchar* _tmp19_ = NULL;
		_tmp18_ = vret;
		_tmp19_ = gir_writer_get_ctype (self, _tmp18_);
		_g_free0 (ret);
		ret = _tmp19_;
	} else {
		ValaMethod* _tmp20_;
		ValaDataType* _tmp21_ = NULL;
		ValaDataType* _tmp22_;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_;
		gchar* _tmp25_ = NULL;
		_tmp20_ = m;
		_tmp21_ = vala_method_get_return_type (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_data_type_get_cname (_tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = gir_writer_get_ctype (self, _tmp24_);
		_g_free0 (ret);
		ret = _tmp25_;
		_g_free0 (_tmp24_);
	}
	_tmp26_ = ret;
	if (_tmp26_ == NULL) {
		const gchar* _tmp27_;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_;
		_tmp27_ = cname;
		_tmp28_ = g_strdup_printf ("Cannot resolve return type for %s\n", _tmp27_);
		_tmp29_ = _tmp28_;
		valabind_compiler_error (_tmp29_);
		_g_free0 (_tmp29_);
	}
	_tmp30_ = ret;
	void_return = g_strcmp0 (_tmp30_, "void") == 0;
	_tmp31_ = m;
	_tmp32_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp31_);
	if (_tmp32_) {
		_g_free0 (vret);
		_g_free0 (ret);
		_g_free0 (alias);
		_g_free0 (cname);
		return;
	}
	_tmp34_ = is_static;
	if (_tmp34_) {
		_tmp33_ = "function";
	} else {
		_tmp33_ = "method";
	}
	_tmp35_ = _tmp33_;
	_tmp36_ = g_strdup (_tmp35_);
	type = _tmp36_;
	_tmp38_ = self->priv->classname;
	if (g_strcmp0 (_tmp38_, "") != 0) {
		gboolean _tmp39_;
		_tmp39_ = is_static;
		_tmp37_ = !_tmp39_;
	} else {
		_tmp37_ = FALSE;
	}
	_tmp40_ = _tmp37_;
	if (_tmp40_) {
		gchar* _tmp41_;
		_tmp41_ = g_strdup ("method");
		_g_free0 (type);
		type = _tmp41_;
	}
	_tmp42_ = is_constructor;
	if (_tmp42_) {
		gchar* _tmp43_;
		_tmp43_ = g_strdup ("constructor");
		_g_free0 (type);
		type = _tmp43_;
	}
	_tmp44_ = self->priv->externs;
	_tmp45_ = type;
	_tmp46_ = g_strconcat ("<", _tmp45_, NULL);
	_tmp47_ = _tmp46_;
	_tmp48_ = g_strconcat (_tmp47_, " name=\"", NULL);
	_tmp49_ = _tmp48_;
	_tmp50_ = alias;
	_tmp51_ = g_strconcat (_tmp49_, _tmp50_, NULL);
	_tmp52_ = _tmp51_;
	_tmp53_ = g_strconcat (_tmp52_, "\" c:identifier=\"", NULL);
	_tmp54_ = _tmp53_;
	_tmp55_ = cname;
	_tmp56_ = g_strconcat (_tmp54_, _tmp55_, NULL);
	_tmp57_ = _tmp56_;
	_tmp58_ = g_strconcat (_tmp57_, "\">\n", NULL);
	_tmp59_ = _tmp58_;
	_tmp60_ = g_strconcat (_tmp44_, _tmp59_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp60_;
	_g_free0 (_tmp59_);
	_g_free0 (_tmp57_);
	_g_free0 (_tmp54_);
	_g_free0 (_tmp52_);
	_g_free0 (_tmp49_);
	_g_free0 (_tmp47_);
	_tmp61_ = void_return;
	if (_tmp61_) {
		const gchar* _tmp62_;
		gchar* _tmp63_;
		_tmp62_ = self->priv->externs;
		_tmp63_ = g_strconcat (_tmp62_, "  <return-type type=\"void\"/>\n", NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp63_;
	} else {
		const gchar* _tmp64_;
		gchar* _tmp65_ = NULL;
		gchar* rtype;
		const gchar* _tmp66_;
		const gchar* _tmp67_;
		gchar* _tmp68_;
		gchar* _tmp69_;
		gchar* _tmp70_;
		gchar* _tmp71_;
		gchar* _tmp72_;
		_tmp64_ = ret;
		_tmp65_ = gir_writer_get_ctype (self, _tmp64_);
		rtype = _tmp65_;
		_tmp66_ = self->priv->externs;
		_tmp67_ = rtype;
		_tmp68_ = g_strconcat ("  <return-type type=\"", _tmp67_, NULL);
		_tmp69_ = _tmp68_;
		_tmp70_ = g_strconcat (_tmp69_, "\" />\n", NULL);
		_tmp71_ = _tmp70_;
		_tmp72_ = g_strconcat (_tmp66_, _tmp71_, NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp72_;
		_g_free0 (_tmp71_);
		_g_free0 (_tmp69_);
		_g_free0 (rtype);
	}
	_tmp73_ = m;
	_tmp74_ = vala_method_get_parameters (_tmp73_);
	parameters = _tmp74_;
	_tmp75_ = parameters;
	_tmp76_ = vala_collection_get_size ((ValaCollection*) _tmp75_);
	_tmp77_ = _tmp76_;
	if (_tmp77_ > 0) {
		const gchar* _tmp78_;
		gchar* _tmp79_;
		const gchar* _tmp128_;
		gchar* _tmp129_;
		_tmp78_ = self->priv->externs;
		_tmp79_ = g_strconcat (_tmp78_, "  <parameters>\n", NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp79_;
		{
			ValaList* _tmp80_;
			ValaList* _tmp81_;
			ValaList* _foo_list;
			ValaList* _tmp82_;
			gint _tmp83_ = 0;
			gint _tmp84_;
			gint _foo_size;
			gint _foo_index;
			_tmp80_ = parameters;
			_tmp81_ = _vala_iterable_ref0 (_tmp80_);
			_foo_list = _tmp81_;
			_tmp82_ = _foo_list;
			_tmp83_ = vala_collection_get_size ((ValaCollection*) _tmp82_);
			_tmp84_ = _tmp83_;
			_foo_size = _tmp84_;
			_foo_index = -1;
			while (TRUE) {
				gint _tmp85_;
				gint _tmp86_;
				gint _tmp87_;
				ValaList* _tmp88_;
				gint _tmp89_;
				gpointer _tmp90_ = NULL;
				ValaParameter* foo;
				ValaParameter* _tmp91_;
				const gchar* _tmp92_ = NULL;
				const gchar* _tmp93_;
				gchar* _tmp94_;
				gchar* arg_name;
				ValaParameter* _tmp95_;
				ValaDataType* _tmp96_ = NULL;
				ValaDataType* _tmp97_;
				ValaDataType* _tmp98_;
				ValaDataType* bar;
				ValaDataType* _tmp99_;
				ValaDataType* _tmp100_;
				gchar* _tmp101_ = NULL;
				gchar* arg_type;
				ValaDataType* _tmp102_;
				gchar* _tmp103_ = NULL;
				gchar* _tmp104_;
				gchar* _tmp105_ = NULL;
				gchar* _tmp106_;
				gchar* arg_ctype;
				const gchar* _tmp107_;
				const gchar* _tmp108_;
				gchar* _tmp109_;
				gchar* _tmp110_;
				gchar* _tmp111_;
				gchar* _tmp112_;
				gchar* _tmp113_;
				const gchar* _tmp114_;
				const gchar* _tmp115_;
				gchar* _tmp116_;
				gchar* _tmp117_;
				gchar* _tmp118_;
				gchar* _tmp119_;
				const gchar* _tmp120_;
				gchar* _tmp121_;
				gchar* _tmp122_;
				gchar* _tmp123_;
				gchar* _tmp124_;
				gchar* _tmp125_;
				const gchar* _tmp126_;
				gchar* _tmp127_;
				_tmp85_ = _foo_index;
				_foo_index = _tmp85_ + 1;
				_tmp86_ = _foo_index;
				_tmp87_ = _foo_size;
				if (!(_tmp86_ < _tmp87_)) {
					break;
				}
				_tmp88_ = _foo_list;
				_tmp89_ = _foo_index;
				_tmp90_ = vala_list_get (_tmp88_, _tmp89_);
				foo = (ValaParameter*) _tmp90_;
				_tmp91_ = foo;
				_tmp92_ = vala_symbol_get_name ((ValaSymbol*) _tmp91_);
				_tmp93_ = _tmp92_;
				_tmp94_ = g_strdup (_tmp93_);
				arg_name = _tmp94_;
				_tmp95_ = foo;
				_tmp96_ = vala_variable_get_variable_type ((ValaVariable*) _tmp95_);
				_tmp97_ = _tmp96_;
				_tmp98_ = _vala_code_node_ref0 (_tmp97_);
				bar = _tmp98_;
				_tmp99_ = bar;
				if (_tmp99_ == NULL) {
					_vala_code_node_unref0 (bar);
					_g_free0 (arg_name);
					_vala_code_node_unref0 (foo);
					continue;
				}
				_tmp100_ = bar;
				_tmp101_ = vala_code_node_to_string ((ValaCodeNode*) _tmp100_);
				arg_type = _tmp101_;
				_tmp102_ = bar;
				_tmp103_ = vala_data_type_get_cname (_tmp102_);
				_tmp104_ = _tmp103_;
				_tmp105_ = gir_writer_get_ctype (self, _tmp104_);
				_tmp106_ = _tmp105_;
				_g_free0 (_tmp104_);
				arg_ctype = _tmp106_;
				_tmp107_ = self->priv->externs;
				_tmp108_ = arg_name;
				_tmp109_ = g_strconcat ("    <parameter name=\"", _tmp108_, NULL);
				_tmp110_ = _tmp109_;
				_tmp111_ = g_strconcat (_tmp110_, "\" transfer-ownership=\"none\">\n", NULL);
				_tmp112_ = _tmp111_;
				_tmp113_ = g_strconcat (_tmp107_, _tmp112_, NULL);
				_g_free0 (self->priv->externs);
				self->priv->externs = _tmp113_;
				_g_free0 (_tmp112_);
				_g_free0 (_tmp110_);
				_tmp114_ = self->priv->externs;
				_tmp115_ = arg_type;
				_tmp116_ = g_strconcat ("      <type name=\"", _tmp115_, NULL);
				_tmp117_ = _tmp116_;
				_tmp118_ = g_strconcat (_tmp117_, "\" c:type=\"", NULL);
				_tmp119_ = _tmp118_;
				_tmp120_ = arg_ctype;
				_tmp121_ = g_strconcat (_tmp119_, _tmp120_, NULL);
				_tmp122_ = _tmp121_;
				_tmp123_ = g_strconcat (_tmp122_, "\"/>\n", NULL);
				_tmp124_ = _tmp123_;
				_tmp125_ = g_strconcat (_tmp114_, _tmp124_, NULL);
				_g_free0 (self->priv->externs);
				self->priv->externs = _tmp125_;
				_g_free0 (_tmp124_);
				_g_free0 (_tmp122_);
				_g_free0 (_tmp119_);
				_g_free0 (_tmp117_);
				_tmp126_ = self->priv->externs;
				_tmp127_ = g_strconcat (_tmp126_, "    </parameter>\n", NULL);
				_g_free0 (self->priv->externs);
				self->priv->externs = _tmp127_;
				_g_free0 (arg_ctype);
				_g_free0 (arg_type);
				_vala_code_node_unref0 (bar);
				_g_free0 (arg_name);
				_vala_code_node_unref0 (foo);
			}
			_vala_iterable_unref0 (_foo_list);
		}
		_tmp128_ = self->priv->externs;
		_tmp129_ = g_strconcat (_tmp128_, "  </parameters>\n", NULL);
		_g_free0 (self->priv->externs);
		self->priv->externs = _tmp129_;
	}
	_tmp130_ = self->priv->externs;
	_tmp131_ = type;
	_tmp132_ = g_strconcat ("</", _tmp131_, NULL);
	_tmp133_ = _tmp132_;
	_tmp134_ = g_strconcat (_tmp133_, ">\n", NULL);
	_tmp135_ = _tmp134_;
	_tmp136_ = g_strconcat (_tmp130_, _tmp135_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp136_;
	_g_free0 (_tmp135_);
	_g_free0 (_tmp133_);
	_vala_iterable_unref0 (parameters);
	_g_free0 (type);
	_g_free0 (vret);
	_g_free0 (ret);
	_g_free0 (alias);
	_g_free0 (cname);
}


static gpointer _vala_source_reference_ref0 (gpointer self) {
	return self ? vala_source_reference_ref (self) : NULL;
}


static void gir_writer_real_visit_namespace (ValaCodeVisitor* base, ValaNamespace* ns) {
	GirWriter * self;
	ValaNamespace* _tmp0_;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_;
	ValaNamespace* _tmp3_;
	ValaSourceReference* _tmp4_ = NULL;
	ValaSourceReference* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaSourceReference* sr;
	gboolean _tmp7_ = FALSE;
	ValaSourceReference* _tmp8_;
	gboolean _tmp15_;
	ValaNamespace* _tmp16_;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	ValaNamespace* _tmp20_;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	const gchar* _tmp88_;
	gchar* _tmp89_;
	self = (GirWriter*) base;
	g_return_if_fail (ns != NULL);
	_tmp0_ = ns;
	_tmp1_ = vala_symbol_get_name ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == NULL) {
		return;
	}
	_tmp3_ = ns;
	_tmp4_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _vala_source_reference_ref0 (_tmp5_);
	sr = _tmp6_;
	_tmp8_ = sr;
	if (_tmp8_ != NULL) {
		ValaSourceReference* _tmp9_;
		ValaSourceFile* _tmp10_ = NULL;
		ValaSourceFile* _tmp11_;
		const gchar* _tmp12_ = NULL;
		const gchar* _tmp13_;
		gboolean _tmp14_ = FALSE;
		_tmp9_ = sr;
		_tmp10_ = vala_source_reference_get_file (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = vala_source_file_get_filename (_tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = gir_writer_is_target_file (self, _tmp13_);
		_tmp7_ = !_tmp14_;
	} else {
		_tmp7_ = FALSE;
	}
	_tmp15_ = _tmp7_;
	if (_tmp15_) {
		_vala_source_reference_unref0 (sr);
		return;
	}
	_tmp16_ = ns;
	_tmp17_ = vala_symbol_get_name ((ValaSymbol*) _tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strdup (_tmp18_);
	_g_free0 (self->priv->nspace);
	self->priv->nspace = _tmp19_;
	_tmp20_ = ns;
	gir_writer_process_includes (self, (ValaSymbol*) _tmp20_);
	_tmp21_ = self->priv->externs;
	_tmp22_ = self->priv->nspace;
	_tmp23_ = g_strconcat ("<namespace version=\"1.0\" name=\"", _tmp22_, NULL);
	_tmp24_ = _tmp23_;
	_tmp25_ = g_strconcat (_tmp24_, "\">\n", NULL);
	_tmp26_ = _tmp25_;
	_tmp27_ = g_strconcat (_tmp21_, _tmp26_, NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp27_;
	_g_free0 (_tmp26_);
	_g_free0 (_tmp24_);
	{
		ValaNamespace* _tmp28_;
		ValaList* _tmp29_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp30_;
		gint _tmp31_ = 0;
		gint _tmp32_;
		gint _f_size;
		gint _f_index;
		_tmp28_ = ns;
		_tmp29_ = vala_namespace_get_fields (_tmp28_);
		_f_list = _tmp29_;
		_tmp30_ = _f_list;
		_tmp31_ = vala_collection_get_size ((ValaCollection*) _tmp30_);
		_tmp32_ = _tmp31_;
		_f_size = _tmp32_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp33_;
			gint _tmp34_;
			gint _tmp35_;
			ValaList* _tmp36_;
			gint _tmp37_;
			gpointer _tmp38_ = NULL;
			ValaField* f;
			ValaField* _tmp39_;
			_tmp33_ = _f_index;
			_f_index = _tmp33_ + 1;
			_tmp34_ = _f_index;
			_tmp35_ = _f_size;
			if (!(_tmp34_ < _tmp35_)) {
				break;
			}
			_tmp36_ = _f_list;
			_tmp37_ = _f_index;
			_tmp38_ = vala_list_get (_tmp36_, _tmp37_);
			f = (ValaField*) _tmp38_;
			_tmp39_ = f;
			gir_writer_walk_field (self, _tmp39_);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	{
		ValaNamespace* _tmp40_;
		ValaList* _tmp41_ = NULL;
		ValaList* _e_list;
		ValaList* _tmp42_;
		gint _tmp43_ = 0;
		gint _tmp44_;
		gint _e_size;
		gint _e_index;
		_tmp40_ = ns;
		_tmp41_ = vala_namespace_get_enums (_tmp40_);
		_e_list = _tmp41_;
		_tmp42_ = _e_list;
		_tmp43_ = vala_collection_get_size ((ValaCollection*) _tmp42_);
		_tmp44_ = _tmp43_;
		_e_size = _tmp44_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp45_;
			gint _tmp46_;
			gint _tmp47_;
			ValaList* _tmp48_;
			gint _tmp49_;
			gpointer _tmp50_ = NULL;
			ValaEnum* e;
			ValaEnum* _tmp51_;
			_tmp45_ = _e_index;
			_e_index = _tmp45_ + 1;
			_tmp46_ = _e_index;
			_tmp47_ = _e_size;
			if (!(_tmp46_ < _tmp47_)) {
				break;
			}
			_tmp48_ = _e_list;
			_tmp49_ = _e_index;
			_tmp50_ = vala_list_get (_tmp48_, _tmp49_);
			e = (ValaEnum*) _tmp50_;
			_tmp51_ = e;
			gir_writer_walk_enum (self, _tmp51_);
			_vala_code_node_unref0 (e);
		}
		_vala_iterable_unref0 (_e_list);
	}
	{
		ValaNamespace* _tmp52_;
		ValaList* _tmp53_ = NULL;
		ValaList* _s_list;
		ValaList* _tmp54_;
		gint _tmp55_ = 0;
		gint _tmp56_;
		gint _s_size;
		gint _s_index;
		_tmp52_ = ns;
		_tmp53_ = vala_namespace_get_structs (_tmp52_);
		_s_list = _tmp53_;
		_tmp54_ = _s_list;
		_tmp55_ = vala_collection_get_size ((ValaCollection*) _tmp54_);
		_tmp56_ = _tmp55_;
		_s_size = _tmp56_;
		_s_index = -1;
		while (TRUE) {
			gint _tmp57_;
			gint _tmp58_;
			gint _tmp59_;
			ValaList* _tmp60_;
			gint _tmp61_;
			gpointer _tmp62_ = NULL;
			ValaStruct* s;
			ValaStruct* _tmp63_;
			_tmp57_ = _s_index;
			_s_index = _tmp57_ + 1;
			_tmp58_ = _s_index;
			_tmp59_ = _s_size;
			if (!(_tmp58_ < _tmp59_)) {
				break;
			}
			_tmp60_ = _s_list;
			_tmp61_ = _s_index;
			_tmp62_ = vala_list_get (_tmp60_, _tmp61_);
			s = (ValaStruct*) _tmp62_;
			_tmp63_ = s;
			gir_writer_walk_struct (self, "", _tmp63_);
			_vala_code_node_unref0 (s);
		}
		_vala_iterable_unref0 (_s_list);
	}
	{
		ValaNamespace* _tmp64_;
		ValaList* _tmp65_ = NULL;
		ValaList* _m_list;
		ValaList* _tmp66_;
		gint _tmp67_ = 0;
		gint _tmp68_;
		gint _m_size;
		gint _m_index;
		_tmp64_ = ns;
		_tmp65_ = vala_namespace_get_methods (_tmp64_);
		_m_list = _tmp65_;
		_tmp66_ = _m_list;
		_tmp67_ = vala_collection_get_size ((ValaCollection*) _tmp66_);
		_tmp68_ = _tmp67_;
		_m_size = _tmp68_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp69_;
			gint _tmp70_;
			gint _tmp71_;
			ValaList* _tmp72_;
			gint _tmp73_;
			gpointer _tmp74_ = NULL;
			ValaMethod* m;
			ValaMethod* _tmp75_;
			_tmp69_ = _m_index;
			_m_index = _tmp69_ + 1;
			_tmp70_ = _m_index;
			_tmp71_ = _m_size;
			if (!(_tmp70_ < _tmp71_)) {
				break;
			}
			_tmp72_ = _m_list;
			_tmp73_ = _m_index;
			_tmp74_ = vala_list_get (_tmp72_, _tmp73_);
			m = (ValaMethod*) _tmp74_;
			_tmp75_ = m;
			gir_writer_walk_method (self, _tmp75_);
			_vala_code_node_unref0 (m);
		}
		_vala_iterable_unref0 (_m_list);
	}
	{
		ValaNamespace* _tmp76_;
		ValaList* _tmp77_ = NULL;
		ValaList* _c_list;
		ValaList* _tmp78_;
		gint _tmp79_ = 0;
		gint _tmp80_;
		gint _c_size;
		gint _c_index;
		_tmp76_ = ns;
		_tmp77_ = vala_namespace_get_classes (_tmp76_);
		_c_list = _tmp77_;
		_tmp78_ = _c_list;
		_tmp79_ = vala_collection_get_size ((ValaCollection*) _tmp78_);
		_tmp80_ = _tmp79_;
		_c_size = _tmp80_;
		_c_index = -1;
		while (TRUE) {
			gint _tmp81_;
			gint _tmp82_;
			gint _tmp83_;
			ValaList* _tmp84_;
			gint _tmp85_;
			gpointer _tmp86_ = NULL;
			ValaClass* c;
			ValaClass* _tmp87_;
			_tmp81_ = _c_index;
			_c_index = _tmp81_ + 1;
			_tmp82_ = _c_index;
			_tmp83_ = _c_size;
			if (!(_tmp82_ < _tmp83_)) {
				break;
			}
			_tmp84_ = _c_list;
			_tmp85_ = _c_index;
			_tmp86_ = vala_list_get (_tmp84_, _tmp85_);
			c = (ValaClass*) _tmp86_;
			_tmp87_ = c;
			gir_writer_walk_class (self, "", _tmp87_);
			_vala_code_node_unref0 (c);
		}
		_vala_iterable_unref0 (_c_list);
	}
	_tmp88_ = self->priv->externs;
	_tmp89_ = g_strconcat (_tmp88_, "</namespace>\n", NULL);
	_g_free0 (self->priv->externs);
	self->priv->externs = _tmp89_;
	_vala_source_reference_unref0 (sr);
}


static gpointer _vala_code_context_ref0 (gpointer self) {
	return self ? vala_code_context_ref (self) : NULL;
}


void gir_writer_write_file (GirWriter* self, ValaCodeContext* context, const gchar* filename) {
	const gchar* _tmp0_;
	FILE* _tmp1_ = NULL;
	FILE* _tmp2_;
	ValaCodeContext* _tmp6_;
	ValaCodeContext* _tmp7_;
	ValaCodeContext* _tmp8_;
	FILE* _tmp9_;
	FILE* _tmp10_;
	FILE* _tmp11_;
	FILE* _tmp12_;
	FILE* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	GList* _tmp19_;
	guint _tmp20_ = 0U;
	FILE* _tmp25_;
	const gchar* _tmp26_;
	FILE* _tmp27_;
	const gchar* _tmp28_;
	FILE* _tmp29_;
	const gchar* _tmp30_;
	FILE* _tmp31_;
	const gchar* _tmp32_;
	FILE* _tmp33_;
	FILE* _tmp34_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (filename != NULL);
	_tmp0_ = filename;
	_tmp1_ = fopen (_tmp0_, "w");
	_fclose0 (self->priv->stream);
	self->priv->stream = _tmp1_;
	_tmp2_ = self->priv->stream;
	if (_tmp2_ == NULL) {
		const gchar* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		_tmp3_ = filename;
		_tmp4_ = g_strdup_printf ("Cannot open %s for writing", _tmp3_);
		_tmp5_ = _tmp4_;
		g_error ("girwriter.vala:338: %s", _tmp5_);
		_g_free0 (_tmp5_);
	}
	_tmp6_ = context;
	_tmp7_ = _vala_code_context_ref0 (_tmp6_);
	_vala_code_context_unref0 (self->priv->context);
	self->priv->context = _tmp7_;
	_tmp8_ = context;
	vala_code_context_accept (_tmp8_, (ValaCodeVisitor*) self);
	_tmp9_ = self->priv->stream;
	fprintf (_tmp9_, "<?xml version=\"1.0\"?>\n");
	_tmp10_ = self->priv->stream;
	fprintf (_tmp10_, "<!-- automatically generated with valabind -->\n");
	_tmp11_ = self->priv->stream;
	fprintf (_tmp11_, "<!-- To compile: g-ir-compiler foo.gir > foo.typelib -->\n");
	_tmp12_ = self->priv->stream;
	fprintf (_tmp12_, "%s", "<repository version=\"1.2\"\n" "	xmlns=\"http://www.gtk.org/introspection/core/1.0\"\n" "	xmlns:c=\"http://www.gtk.org/introspection/c/1.0\"\n" "	xmlns:glib=\"http://www.gtk.org/introspection/glib/1.0\">\n");
	_tmp13_ = self->priv->stream;
	_tmp14_ = self->priv->modulename;
	_tmp15_ = g_strconcat ("  <namespace version=\"1.0\" name=\"", _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp16_, "\">\n", NULL);
	_tmp18_ = _tmp17_;
	fprintf (_tmp13_, "%s", _tmp18_);
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_tmp19_ = self->includefiles;
	_tmp20_ = g_list_length (_tmp19_);
	if (_tmp20_ > ((guint) 0)) {
		GList* _tmp21_;
		_tmp21_ = self->includefiles;
		{
			GList* inc_collection = NULL;
			GList* inc_it = NULL;
			inc_collection = _tmp21_;
			for (inc_it = inc_collection; inc_it != NULL; inc_it = inc_it->next) {
				gchar* _tmp22_;
				gchar* inc = NULL;
				_tmp22_ = g_strdup ((const gchar*) inc_it->data);
				inc = _tmp22_;
				{
					FILE* _tmp23_;
					const gchar* _tmp24_;
					_tmp23_ = self->priv->stream;
					_tmp24_ = inc;
					fprintf (_tmp23_, "  <c:include name=\"%s\"/>\n", _tmp24_);
					_g_free0 (inc);
				}
			}
		}
	}
	_tmp25_ = self->priv->stream;
	_tmp26_ = self->priv->enums;
	fprintf (_tmp25_, "%s\n", _tmp26_);
	_tmp27_ = self->priv->stream;
	_tmp28_ = self->priv->externs;
	fprintf (_tmp27_, "%s\n", _tmp28_);
	_tmp29_ = self->priv->stream;
	_tmp30_ = self->priv->statics;
	fprintf (_tmp29_, "%s\n", _tmp30_);
	_tmp31_ = self->priv->stream;
	_tmp32_ = self->priv->extends;
	fprintf (_tmp31_, "%s\n", _tmp32_);
	_tmp33_ = self->priv->stream;
	fprintf (_tmp33_, "  </namespace>\n");
	_tmp34_ = self->priv->stream;
	fprintf (_tmp34_, "</repository>\n");
	_fclose0 (self->priv->stream);
	self->priv->stream = NULL;
}


static void gir_writer_class_init (GirWriterClass * klass) {
	gir_writer_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->finalize = gir_writer_finalize;
	g_type_class_add_private (klass, sizeof (GirWriterPrivate));
	VALA_CODE_VISITOR_CLASS (klass)->visit_source_file = gir_writer_real_visit_source_file;
	VALA_CODE_VISITOR_CLASS (klass)->visit_namespace = gir_writer_real_visit_namespace;
}


static void gir_writer_instance_init (GirWriter * self) {
	self->priv = GIR_WRITER_GET_PRIVATE (self);
}


static void gir_writer_finalize (ValaCodeVisitor* obj) {
	GirWriter * self;
	self = GIR_WRITER (obj);
	_g_free0 (self->pkgname);
	self->files = (_vala_array_free (self->files, self->files_length1, (GDestroyNotify) g_free), NULL);
	__g_list_free__g_free0_0 (self->includefiles);
	__g_list_free__vala_code_node_unref0_0 (self->methods);
	_vala_code_context_unref0 (self->priv->context);
	_fclose0 (self->priv->stream);
	_g_free0 (self->priv->classname);
	_g_free0 (self->priv->classcname);
	_g_free0 (self->priv->externs);
	_g_free0 (self->priv->statics);
	_g_free0 (self->priv->extends);
	_g_free0 (self->priv->enums);
	_g_free0 (self->priv->vectors);
	_g_free0 (self->priv->nspace);
	_g_free0 (self->priv->modulename);
	VALA_CODE_VISITOR_CLASS (gir_writer_parent_class)->finalize (obj);
}


GType gir_writer_get_type (void) {
	static volatile gsize gir_writer_type_id__volatile = 0;
	if (g_once_init_enter (&gir_writer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GirWriterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gir_writer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GirWriter), 0, (GInstanceInitFunc) gir_writer_instance_init, NULL };
		GType gir_writer_type_id;
		gir_writer_type_id = g_type_register_static (VALA_TYPE_CODE_VISITOR, "GirWriter", &g_define_type_info, 0);
		g_once_init_leave (&gir_writer_type_id__volatile, gir_writer_type_id);
	}
	return gir_writer_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



