/* main.c generated by valac 0.14.0.17-9c67, the Vala compiler
 * generated from main.vala, do not modify */

/* Copyleft 2009-2011 -- pancake // nopcode.org */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_VALABIND_COMPILER (valabind_compiler_get_type ())
#define VALABIND_COMPILER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VALABIND_COMPILER, ValabindCompiler))
#define VALABIND_COMPILER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VALABIND_COMPILER, ValabindCompilerClass))
#define IS_VALABIND_COMPILER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VALABIND_COMPILER))
#define IS_VALABIND_COMPILER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VALABIND_COMPILER))
#define VALABIND_COMPILER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VALABIND_COMPILER, ValabindCompilerClass))

typedef struct _ValabindCompiler ValabindCompiler;
typedef struct _ValabindCompilerClass ValabindCompilerClass;
typedef struct _ValabindCompilerPrivate ValabindCompilerPrivate;
#define _valabind_compiler_unref0(var) ((var == NULL) ? NULL : (var = (valabind_compiler_unref (var), NULL)))

struct _ValabindCompiler {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValabindCompilerPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
};

struct _ValabindCompilerClass {
	GTypeClass parent_class;
	void (*finalize) (ValabindCompiler *self);
};


extern gchar** files;
extern gint files_length1;
gchar** files = NULL;
gint files_length1 = 0;
static gint _files_size_ = 0;
extern gchar* includefile;
gchar* includefile = NULL;
extern gchar* vapidir;
gchar* vapidir = NULL;
extern gboolean show_version;
gboolean show_version = FALSE;
extern gboolean show_externs;
gboolean show_externs = FALSE;
extern gboolean glibmode;
gboolean glibmode = FALSE;
extern gboolean cxxmode;
gboolean cxxmode = FALSE;
extern gboolean cxxoutput;
gboolean cxxoutput = FALSE;
extern gboolean gearoutput;
gboolean gearoutput = FALSE;
extern gboolean swigoutput;
gboolean swigoutput = FALSE;
extern gboolean giroutput;
gboolean giroutput = FALSE;
extern gchar* modulename;
gchar* modulename = NULL;
extern gchar* output;
gchar* output = NULL;
extern gchar* useprofile;
gchar* useprofile = NULL;
extern gchar** packages;
gchar** packages = NULL;

gint _vala_main (gchar** args, int args_length1);
#define version_string "valabind 0.5.1 - pancake@nopcode.org"
ValabindCompiler* valabind_compiler_new (const gchar* modulename, const gchar* vapidir, const gchar* profile);
ValabindCompiler* valabind_compiler_construct (GType object_type, const gchar* modulename, const gchar* vapidir, const gchar* profile);
gpointer valabind_compiler_ref (gpointer instance);
void valabind_compiler_unref (gpointer instance);
GParamSpec* param_spec_valabind_compiler (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_valabind_compiler (GValue* value, gpointer v_object);
void value_take_valabind_compiler (GValue* value, gpointer v_object);
gpointer value_get_valabind_compiler (const GValue* value);
GType valabind_compiler_get_type (void) G_GNUC_CONST;
gboolean valabind_compiler_add_external_package (ValabindCompiler* self, const gchar* pkg);
gboolean valabind_compiler_add_source_file (ValabindCompiler* self, const gchar* path);
void valabind_compiler_parse (ValabindCompiler* self);
void valabind_compiler_emit_gear (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
void valabind_compiler_emit_gir (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
void valabind_compiler_emit_cxx (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
void valabind_compiler_emit_swig (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

const GOptionEntry options[16] = {{"pkg", (gchar) 0, 0, G_OPTION_ARG_STRING_ARRAY, &packages, "Include binding for PACKAGE", "PACKAGE..."}, {"vapidir", 'V', 0, G_OPTION_ARG_STRING, &vapidir, "define alternative vapi directory", NULL}, {"include", 'i', 0, G_OPTION_ARG_STRING, &includefile, "include file", NULL}, {"externs", 'e', 0, G_OPTION_ARG_NONE, &show_externs, "render externs", NULL}, {"version", 'v', 0, G_OPTION_ARG_NONE, &show_version, "show version information", NULL}, {"output", 'o', 0, G_OPTION_ARG_STRING, &output, "specify output file name", NULL}, {"module", 'm', 0, G_OPTION_ARG_STRING, &modulename, "specify module name", "NAME"}, {"profile", 'p', 0, G_OPTION_ARG_NONE, &useprofile, "select Vala profile (posix, gobject, dova)", "posix"}, {"glib", 'g', 0, G_OPTION_ARG_NONE, &glibmode, "work in glib/gobject mode", NULL}, {"cxx-swig", 'x', 0, G_OPTION_ARG_NONE, &cxxmode, "generate c++ code for SWIG", NULL}, {"swig", '\0', 0, G_OPTION_ARG_NONE, &swigoutput, "generate swig interface code (default)", NULL}, {"gear", '\0', 0, G_OPTION_ARG_NONE, &gearoutput, "generate gearbox interface code", NULL}, {"gir", '\0', 0, G_OPTION_ARG_NONE, &giroutput, "generate GIR (GObject-Introspection-Runtime)", NULL}, {"cxx", '\0', 0, G_OPTION_ARG_NONE, &cxxoutput, "output C++ code instead of SWIG interface", NULL}, {"", (gchar) 0, 0, G_OPTION_ARG_FILENAME_ARRAY, &files, "vala/vapi input files", "FILE FILE .."}, {NULL}};

static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _result_;
	gchar* _tmp3_;
#line 1055 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 1055 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 1056 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 1056 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 1056 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 1056 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 1058 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 1058 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 124 "main.c"
		gchar* _tmp4_;
#line 1059 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 1059 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 1059 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
		return result;
#line 132 "main.c"
	} else {
#line 1061 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
		result = -1;
#line 1061 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
		return result;
#line 138 "main.c"
	}
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** _tmp2_ = NULL;
	gboolean _tmp10_;
	const gchar* _tmp11_;
	gchar** _tmp13_;
	gint _tmp13__length1;
	gint count;
	gboolean _tmp15_;
	gboolean _tmp17_;
	gboolean _tmp19_;
	gboolean _tmp21_;
	gint _tmp23_;
	const gchar* _tmp25_ = NULL;
	const gchar* _tmp26_;
	const gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* profile;
	gboolean _tmp30_;
	const gchar* _tmp32_;
	const gchar* _tmp33_;
	const gchar* _tmp34_;
	ValabindCompiler* _tmp35_;
	ValabindCompiler* vbc;
	gchar** _tmp36_;
	gint _tmp36__length1;
	gchar** _tmp46_;
	gint _tmp46__length1;
	ValabindCompiler* _tmp56_;
	const gchar* _tmp57_;
	gboolean _tmp69_;
	GError * _inner_error_ = NULL;
#line 55 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_g_free0 (output);
#line 55 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	output = NULL;
#line 56 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp0_ = g_strdup (".");
#line 56 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_g_free0 (vapidir);
#line 56 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	vapidir = _tmp0_;
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp1_ = g_strdup ("");
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp2_ = g_new0 (gchar*, 1 + 1);
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp2_[0] = _tmp1_;
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	files = (_vala_array_free (files, files_length1, (GDestroyNotify) g_free), NULL);
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	files = _tmp2_;
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	files_length1 = 1;
#line 57 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_files_size_ = files_length1;
#line 201 "main.c"
	{
		GOptionContext* _tmp3_;
		GOptionContext* opt_context;
		GOptionContext* _tmp4_;
		GOptionContext* _tmp5_;
		GOptionContext* _tmp6_;
#line 60 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp3_ = g_option_context_new ("- valabind");
#line 60 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		opt_context = _tmp3_;
#line 61 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp4_ = opt_context;
#line 61 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_option_context_set_help_enabled (_tmp4_, TRUE);
#line 62 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp5_ = opt_context;
#line 62 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_option_context_add_main_entries (_tmp5_, options, NULL);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp6_ = opt_context;
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_option_context_parse (_tmp6_, &args_length1, &args, &_inner_error_);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		if (_inner_error_ != NULL) {
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_g_option_context_free0 (opt_context);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			if (_inner_error_->domain == G_OPTION_ERROR) {
#line 230 "main.c"
				goto __catch0_g_option_error;
			}
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_g_option_context_free0 (opt_context);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			g_clear_error (&_inner_error_);
#line 63 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			return 0;
#line 241 "main.c"
		}
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_g_option_context_free0 (opt_context);
#line 245 "main.c"
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp7_;
		GError* _tmp8_;
		const gchar* _tmp9_;
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		e = _inner_error_;
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_inner_error_ = NULL;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp7_ = stderr;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp8_ = e;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp9_ = _tmp8_->message;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		fprintf (_tmp7_, "%s\nTry --help\n", _tmp9_);
#line 66 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		result = 1;
#line 66 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_g_error_free0 (e);
#line 66 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return result;
#line 272 "main.c"
	}
	__finally0:
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_inner_error_ != NULL) {
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_clear_error (&_inner_error_);
#line 59 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return 0;
#line 283 "main.c"
	}
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp10_ = show_version;
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp10_) {
#line 70 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		g_print ("%s\n", version_string);
#line 71 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		result = 0;
#line 71 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return result;
#line 295 "main.c"
	}
#line 74 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp11_ = modulename;
#line 74 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp11_ == NULL) {
#line 301 "main.c"
		FILE* _tmp12_;
#line 75 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp12_ = stderr;
#line 75 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		fprintf (_tmp12_, "No modulename specified. Use --module or --help\n");
#line 76 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		result = 1;
#line 76 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return result;
#line 311 "main.c"
	}
#line 79 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp13_ = files;
#line 79 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp13__length1 = files_length1;
#line 79 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp13__length1 == 0) {
#line 319 "main.c"
		FILE* _tmp14_;
#line 80 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp14_ = stderr;
#line 80 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		fprintf (_tmp14_, "No files given\n");
#line 81 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		result = 1;
#line 81 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return result;
#line 329 "main.c"
	}
#line 84 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	count = 0;
#line 85 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp15_ = swigoutput;
#line 85 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp15_) {
#line 337 "main.c"
		gint _tmp16_;
#line 85 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp16_ = count;
#line 85 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		count = _tmp16_ + 1;
#line 343 "main.c"
	}
#line 86 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp17_ = gearoutput;
#line 86 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp17_) {
#line 349 "main.c"
		gint _tmp18_;
#line 86 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp18_ = count;
#line 86 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		count = _tmp18_ + 1;
#line 355 "main.c"
	}
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp19_ = giroutput;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp19_) {
#line 361 "main.c"
		gint _tmp20_;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp20_ = count;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		count = _tmp20_ + 1;
#line 367 "main.c"
	}
#line 88 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp21_ = cxxoutput;
#line 88 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp21_) {
#line 373 "main.c"
		gint _tmp22_;
#line 88 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp22_ = count;
#line 88 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		count = _tmp22_ + 1;
#line 379 "main.c"
	}
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp23_ = count;
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp23_ > 1) {
#line 385 "main.c"
		FILE* _tmp24_;
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp24_ = stderr;
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		fprintf (_tmp24_, "Cannot use --swig, --gir, --gear or --cxx together\n");
#line 91 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		result = 1;
#line 91 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		return result;
#line 395 "main.c"
	}
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp26_ = useprofile;
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp26_ != NULL) {
#line 401 "main.c"
		const gchar* _tmp27_;
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp27_ = useprofile;
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp25_ = _tmp27_;
#line 407 "main.c"
	} else {
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp25_ = "posix";
#line 411 "main.c"
	}
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp28_ = _tmp25_;
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp29_ = g_strdup (_tmp28_);
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	profile = _tmp29_;
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp30_ = glibmode;
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp30_) {
#line 423 "main.c"
		gchar* _tmp31_;
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp31_ = g_strdup ("gobject");
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_g_free0 (profile);
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		profile = _tmp31_;
#line 431 "main.c"
	}
#line 98 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp32_ = modulename;
#line 98 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp33_ = vapidir;
#line 98 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp34_ = profile;
#line 98 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp35_ = valabind_compiler_new (_tmp32_, _tmp33_, _tmp34_);
#line 98 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	vbc = _tmp35_;
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp36_ = packages;
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp36__length1 = _vala_array_length (packages);
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp36_ != NULL) {
#line 449 "main.c"
		gchar** _tmp37_;
		gint _tmp37__length1;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp37_ = packages;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp37__length1 = _vala_array_length (packages);
#line 456 "main.c"
		{
			gchar** pkg_collection = NULL;
			gint pkg_collection_length1 = 0;
			gint _pkg_collection_size_ = 0;
			gint pkg_it = 0;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			pkg_collection = _tmp37_;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			pkg_collection_length1 = _tmp37__length1;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			for (pkg_it = 0; pkg_it < _tmp37__length1; pkg_it = pkg_it + 1) {
#line 468 "main.c"
				gchar* _tmp38_;
				gchar* pkg = NULL;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp38_ = g_strdup (pkg_collection[pkg_it]);
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				pkg = _tmp38_;
#line 475 "main.c"
				{
					const gchar* _tmp39_;
					gchar* _tmp40_;
					gchar* _tmp41_;
					gchar* _tmp42_;
					gchar* _tmp43_;
					ValabindCompiler* _tmp44_;
					const gchar* _tmp45_;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp39_ = pkg;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp40_ = g_strconcat ("Adding dependency ", _tmp39_, NULL);
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp41_ = _tmp40_;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp42_ = g_strconcat (_tmp41_, "\n", NULL);
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp43_ = _tmp42_;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					g_print ("%s", _tmp43_);
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_g_free0 (_tmp43_);
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_g_free0 (_tmp41_);
#line 102 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp44_ = vbc;
#line 102 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp45_ = pkg;
#line 102 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					valabind_compiler_add_external_package (_tmp44_, _tmp45_);
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_g_free0 (pkg);
#line 508 "main.c"
				}
			}
		}
	}
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp46_ = files;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp46__length1 = files_length1;
#line 517 "main.c"
	{
		gchar** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		file_collection = _tmp46_;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		file_collection_length1 = _tmp46__length1;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		for (file_it = 0; file_it < _tmp46__length1; file_it = file_it + 1) {
#line 529 "main.c"
			gchar* _tmp47_;
			gchar* file = NULL;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp47_ = g_strdup (file_collection[file_it]);
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			file = _tmp47_;
#line 536 "main.c"
			{
				const gchar* _tmp48_;
				gint _tmp49_ = 0;
				ValabindCompiler* _tmp54_;
				const gchar* _tmp55_;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp48_ = file;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp49_ = string_index_of (_tmp48_, ".vapi", 0);
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				if (_tmp49_ == (-1)) {
#line 548 "main.c"
					ValabindCompiler* _tmp50_;
					ValabindCompiler* _tmp51_;
					const gchar* _tmp52_;
					gchar* _tmp53_;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp50_ = vbc;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp50_->pkgmode = TRUE;
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp51_ = vbc;
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp52_ = file;
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp53_ = g_strdup (_tmp52_);
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_g_free0 (_tmp51_->pkgname);
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp51_->pkgname = _tmp53_;
#line 567 "main.c"
				}
#line 111 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp54_ = vbc;
#line 111 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp55_ = file;
#line 111 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				valabind_compiler_add_source_file (_tmp54_, _tmp55_);
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_g_free0 (file);
#line 577 "main.c"
			}
		}
	}
#line 113 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp56_ = vbc;
#line 113 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	valabind_compiler_parse (_tmp56_);
#line 114 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp57_ = output;
#line 114 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp57_ == NULL) {
#line 589 "main.c"
		const gchar* _tmp58_ = NULL;
		gboolean _tmp59_;
		const gchar* _tmp66_;
		const gchar* _tmp67_;
		gchar* _tmp68_ = NULL;
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp59_ = giroutput;
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		if (_tmp59_) {
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp58_ = "gir";
#line 601 "main.c"
		} else {
			const gchar* _tmp60_ = NULL;
			gboolean _tmp61_;
			const gchar* _tmp65_;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp61_ = gearoutput;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			if (_tmp61_) {
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp60_ = "gear";
#line 612 "main.c"
			} else {
				const gchar* _tmp62_ = NULL;
				gboolean _tmp63_;
				const gchar* _tmp64_;
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp63_ = cxxoutput;
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				if (_tmp63_) {
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp62_ = "cxx";
#line 623 "main.c"
				} else {
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
					_tmp62_ = "i";
#line 627 "main.c"
				}
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp64_ = _tmp62_;
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp60_ = _tmp64_;
#line 633 "main.c"
			}
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp65_ = _tmp60_;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp58_ = _tmp65_;
#line 639 "main.c"
		}
#line 115 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp66_ = modulename;
#line 115 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp67_ = _tmp58_;
#line 115 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp68_ = g_strdup_printf ("%s.%s", _tmp66_, _tmp67_);
#line 115 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_g_free0 (output);
#line 115 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		output = _tmp68_;
#line 651 "main.c"
	}
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_tmp69_ = gearoutput;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	if (_tmp69_) {
#line 657 "main.c"
		ValabindCompiler* _tmp70_;
		const gchar* _tmp71_;
		gboolean _tmp72_;
		gboolean _tmp73_;
		gboolean _tmp74_;
		const gchar* _tmp75_;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp70_ = vbc;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp71_ = output;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp72_ = show_externs;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp73_ = glibmode;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp74_ = cxxmode;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp75_ = includefile;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		valabind_compiler_emit_gear (_tmp70_, _tmp71_, _tmp72_, _tmp73_, _tmp74_, _tmp75_);
#line 678 "main.c"
	} else {
		gboolean _tmp76_;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		_tmp76_ = giroutput;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
		if (_tmp76_) {
#line 685 "main.c"
			ValabindCompiler* _tmp77_;
			const gchar* _tmp78_;
			gboolean _tmp79_;
			gboolean _tmp80_;
			gboolean _tmp81_;
			const gchar* _tmp82_;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp77_ = vbc;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp78_ = output;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp79_ = show_externs;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp80_ = glibmode;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp81_ = cxxmode;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp82_ = includefile;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			valabind_compiler_emit_gir (_tmp77_, _tmp78_, _tmp79_, _tmp80_, _tmp81_, _tmp82_);
#line 706 "main.c"
		} else {
			gboolean _tmp83_;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			_tmp83_ = cxxoutput;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
			if (_tmp83_) {
#line 713 "main.c"
				ValabindCompiler* _tmp84_;
				const gchar* _tmp85_;
				gboolean _tmp86_;
				gboolean _tmp87_;
				gboolean _tmp88_;
				const gchar* _tmp89_;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp84_ = vbc;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp85_ = output;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp86_ = show_externs;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp87_ = glibmode;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp88_ = cxxmode;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp89_ = includefile;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				valabind_compiler_emit_cxx (_tmp84_, _tmp85_, _tmp86_, _tmp87_, _tmp88_, _tmp89_);
#line 734 "main.c"
			} else {
				ValabindCompiler* _tmp90_;
				const gchar* _tmp91_;
				gboolean _tmp92_;
				gboolean _tmp93_;
				const gchar* _tmp94_;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp90_ = vbc;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp91_ = output;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp92_ = show_externs;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp93_ = glibmode;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				_tmp94_ = includefile;
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
				valabind_compiler_emit_swig (_tmp90_, _tmp91_, _tmp92_, _tmp93_, TRUE, _tmp94_);
#line 753 "main.c"
			}
		}
	}
#line 123 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	result = 0;
#line 123 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_valabind_compiler_unref0 (vbc);
#line 123 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	_g_free0 (profile);
#line 123 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	return result;
#line 765 "main.c"
}


int main (int argc, char ** argv) {
#line 54 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	g_type_init ();
#line 54 "/Users/pancake/prg/valabind/valabind-0.5.1/main.vala"
	return _vala_main (argv, argc);
#line 774 "main.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



