/* valabindcompiler.c generated by valac 0.14.0.17-9c67, the Vala compiler
 * generated from valabindcompiler.vala, do not modify */

/* Copyleft 2009-2011 -- pancake // nopcode.org */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <vala.h>
#include <glib/gstdio.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_VALABIND_COMPILER (valabind_compiler_get_type ())
#define VALABIND_COMPILER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VALABIND_COMPILER, ValabindCompiler))
#define VALABIND_COMPILER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VALABIND_COMPILER, ValabindCompilerClass))
#define IS_VALABIND_COMPILER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VALABIND_COMPILER))
#define IS_VALABIND_COMPILER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VALABIND_COMPILER))
#define VALABIND_COMPILER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VALABIND_COMPILER, ValabindCompilerClass))

typedef struct _ValabindCompiler ValabindCompiler;
typedef struct _ValabindCompilerClass ValabindCompilerClass;
typedef struct _ValabindCompilerPrivate ValabindCompilerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _vala_code_visitor_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_visitor_unref (var), NULL)))
#define _vala_source_file_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_file_unref (var), NULL)))

#define TYPE_GIR_WRITER (gir_writer_get_type ())
#define GIR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GIR_WRITER, GirWriter))
#define GIR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GIR_WRITER, GirWriterClass))
#define IS_GIR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GIR_WRITER))
#define IS_GIR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GIR_WRITER))
#define GIR_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GIR_WRITER, GirWriterClass))

typedef struct _GirWriter GirWriter;
typedef struct _GirWriterClass GirWriterClass;
typedef struct _GirWriterPrivate GirWriterPrivate;

#define TYPE_GEAR_WRITER (gear_writer_get_type ())
#define GEAR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GEAR_WRITER, GearWriter))
#define GEAR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GEAR_WRITER, GearWriterClass))
#define IS_GEAR_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GEAR_WRITER))
#define IS_GEAR_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GEAR_WRITER))
#define GEAR_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GEAR_WRITER, GearWriterClass))

typedef struct _GearWriter GearWriter;
typedef struct _GearWriterClass GearWriterClass;
typedef struct _GearWriterPrivate GearWriterPrivate;

#define TYPE_CXX_WRITER (cxx_writer_get_type ())
#define CXX_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CXX_WRITER, CxxWriter))
#define CXX_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CXX_WRITER, CxxWriterClass))
#define IS_CXX_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CXX_WRITER))
#define IS_CXX_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CXX_WRITER))
#define CXX_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CXX_WRITER, CxxWriterClass))

typedef struct _CxxWriter CxxWriter;
typedef struct _CxxWriterClass CxxWriterClass;
typedef struct _CxxWriterPrivate CxxWriterPrivate;

#define TYPE_SWIG_WRITER (swig_writer_get_type ())
#define SWIG_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SWIG_WRITER, SwigWriter))
#define SWIG_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SWIG_WRITER, SwigWriterClass))
#define IS_SWIG_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SWIG_WRITER))
#define IS_SWIG_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SWIG_WRITER))
#define SWIG_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SWIG_WRITER, SwigWriterClass))

typedef struct _SwigWriter SwigWriter;
typedef struct _SwigWriterClass SwigWriterClass;
typedef struct _SwigWriterPrivate SwigWriterPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecValabindCompiler ParamSpecValabindCompiler;

struct _ValabindCompiler {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValabindCompilerPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
};

struct _ValabindCompilerClass {
	GTypeClass parent_class;
	void (*finalize) (ValabindCompiler *self);
};

struct _ValabindCompilerPrivate {
	gchar* vapidir;
	gchar* modulename;
	ValaCodeContext* context;
	gchar** source_files;
	gint source_files_length1;
	gint _source_files_size_;
};

struct _GirWriter {
	ValaCodeVisitor parent_instance;
	GirWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gboolean show_externs;
	gboolean glib_mode;
	gboolean cxx_mode;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _GirWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _GearWriter {
	ValaCodeVisitor parent_instance;
	GearWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _GearWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _CxxWriter {
	ValaCodeVisitor parent_instance;
	CxxWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gboolean show_externs;
	gboolean glib_mode;
	gboolean cxx_mode;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _CxxWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _SwigWriter {
	ValaCodeVisitor parent_instance;
	SwigWriterPrivate * priv;
	gboolean pkgmode;
	gchar* pkgname;
	gboolean show_externs;
	gboolean glib_mode;
	gboolean cxx_mode;
	gchar** files;
	gint files_length1;
	GList* includefiles;
	GList* methods;
};

struct _SwigWriterClass {
	ValaCodeVisitorClass parent_class;
};

struct _ParamSpecValabindCompiler {
	GParamSpec parent_instance;
};


static gpointer valabind_compiler_parent_class = NULL;

gpointer valabind_compiler_ref (gpointer instance);
void valabind_compiler_unref (gpointer instance);
GParamSpec* param_spec_valabind_compiler (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_valabind_compiler (GValue* value, gpointer v_object);
void value_take_valabind_compiler (GValue* value, gpointer v_object);
gpointer value_get_valabind_compiler (const GValue* value);
GType valabind_compiler_get_type (void) G_GNUC_CONST;
#define VALABIND_COMPILER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_VALABIND_COMPILER, ValabindCompilerPrivate))
enum  {
	VALABIND_COMPILER_DUMMY_PROPERTY
};
ValabindCompiler* valabind_compiler_new (const gchar* modulename, const gchar* vapidir, const gchar* profile);
ValabindCompiler* valabind_compiler_construct (GType object_type, const gchar* modulename, const gchar* vapidir, const gchar* profile);
static gboolean valabind_compiler_add_package (ValabindCompiler* self, ValaCodeContext* context, const gchar* pkg);
void valabind_compiler_parse (ValabindCompiler* self);
gboolean valabind_compiler_init (ValabindCompiler* self);
void valabind_compiler_error (const gchar* msg);
gboolean valabind_compiler_add_external_package (ValabindCompiler* self, const gchar* pkg);
gboolean valabind_compiler_add_source_file (ValabindCompiler* self, const gchar* path);
static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value);
void valabind_compiler_emit_vapi (ValabindCompiler* self, const gchar* output, const gchar* file);
void valabind_compiler_emit_gir (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
GirWriter* gir_writer_new (const gchar* name);
GirWriter* gir_writer_construct (GType object_type, const gchar* name);
GType gir_writer_get_type (void) G_GNUC_CONST;
static gchar** _vala_array_dup1 (gchar** self, int length);
void gir_writer_write_file (GirWriter* self, ValaCodeContext* context, const gchar* filename);
void valabind_compiler_warning (const gchar* msg);
void valabind_compiler_emit_gear (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
GearWriter* gear_writer_new (const gchar* name);
GearWriter* gear_writer_construct (GType object_type, const gchar* name);
GType gear_writer_get_type (void) G_GNUC_CONST;
static gchar** _vala_array_dup2 (gchar** self, int length);
void gear_writer_write_file (GearWriter* self, ValaCodeContext* context, const gchar* filename);
void valabind_compiler_emit_cxx (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
CxxWriter* cxx_writer_new (const gchar* name);
CxxWriter* cxx_writer_construct (GType object_type, const gchar* name);
GType cxx_writer_get_type (void) G_GNUC_CONST;
static gchar** _vala_array_dup3 (gchar** self, int length);
void cxx_writer_write_file (CxxWriter* self, ValaCodeContext* context, const gchar* filename);
void valabind_compiler_emit_swig (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include);
SwigWriter* swig_writer_new (const gchar* name);
SwigWriter* swig_writer_construct (GType object_type, const gchar* name);
GType swig_writer_get_type (void) G_GNUC_CONST;
static gchar** _vala_array_dup4 (gchar** self, int length);
void swig_writer_write_file (SwigWriter* self, ValaCodeContext* context, const gchar* filename);
static void valabind_compiler_finalize (ValabindCompiler* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


ValabindCompiler* valabind_compiler_construct (GType object_type, const gchar* modulename, const gchar* vapidir, const gchar* profile) {
	ValabindCompiler* self = NULL;
	ValaCodeContext* _tmp0_;
	ValaCodeContext* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	ValaCodeContext* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar** _tmp9_ = NULL;
	ValaCodeContext* _tmp10_;
	ValaCodeContext* _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
	GQuark _tmp15_ = 0U;
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	static GQuark _tmp14_label0 = 0;
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	static GQuark _tmp14_label1 = 0;
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (modulename != NULL, NULL);
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (vapidir != NULL, NULL);
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (profile != NULL, NULL);
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self = (ValabindCompiler*) g_type_create_instance (object_type);
#line 14 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = vala_code_context_new ();
#line 14 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_context_unref0 (self->priv->context);
#line 14 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->context = _tmp0_;
#line 15 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = self->priv->context;
#line 15 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_code_context_push (_tmp1_);
#line 16 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = modulename;
#line 16 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 16 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (self->priv->modulename);
#line 16 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->modulename = _tmp3_;
#line 17 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp4_ = vapidir;
#line 17 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 17 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (self->priv->vapidir);
#line 17 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->vapidir = _tmp5_;
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_ = self->priv->context;
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp7_ = vapidir;
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp8_ = g_strdup (_tmp7_);
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp9_ = g_new0 (gchar*, 1 + 1);
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp9_[0] = _tmp8_;
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_->vapi_directories = (_vala_array_free (_tmp6_->vapi_directories, _tmp6_->vapi_directories_length1, (GDestroyNotify) g_free), NULL);
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_->vapi_directories = _tmp9_;
#line 19 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_->vapi_directories_length1 = 1;
#line 21 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->source_files = (_vala_array_free (self->priv->source_files, self->priv->source_files_length1, (GDestroyNotify) g_free), NULL);
#line 21 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->source_files = NULL;
#line 21 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->source_files_length1 = 0;
#line 21 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->_source_files_size_ = self->priv->source_files_length1;
#line 22 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp10_ = self->priv->context;
#line 22 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	valabind_compiler_add_package (self, _tmp10_, "glib-2.0");
#line 23 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp11_ = self->priv->context;
#line 23 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	valabind_compiler_add_package (self, _tmp11_, "gobject-2.0");
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp12_ = profile;
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp13_ = _tmp12_;
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp15_ = (NULL == _tmp13_) ? 0 : g_quark_from_string (_tmp13_);
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp15_ == ((0 != _tmp14_label0) ? _tmp14_label0 : (_tmp14_label0 = g_quark_from_static_string ("gobject")))) {
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		switch (0) {
#line 325 "valabindcompiler.c"
			default:
			{
				ValaCodeContext* _tmp16_;
				ValaCodeContext* _tmp17_;
#line 26 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp16_ = self->priv->context;
#line 26 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_set_profile (_tmp16_, VALA_PROFILE_GOBJECT);
#line 27 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp17_ = self->priv->context;
#line 27 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_add_define (_tmp17_, "GOBJECT");
#line 28 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				break;
#line 340 "valabindcompiler.c"
			}
		}
	} else if (_tmp15_ == ((0 != _tmp14_label1) ? _tmp14_label1 : (_tmp14_label1 = g_quark_from_static_string ("dova")))) {
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		switch (0) {
#line 346 "valabindcompiler.c"
			default:
			{
				ValaCodeContext* _tmp18_;
				ValaCodeContext* _tmp19_;
#line 30 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp18_ = self->priv->context;
#line 30 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_set_profile (_tmp18_, VALA_PROFILE_DOVA);
#line 31 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp19_ = self->priv->context;
#line 31 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_add_define (_tmp19_, "DOVA");
#line 32 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				break;
#line 361 "valabindcompiler.c"
			}
		}
	} else {
#line 24 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		switch (0) {
#line 367 "valabindcompiler.c"
			default:
			{
				ValaCodeContext* _tmp20_;
				ValaCodeContext* _tmp21_;
#line 35 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp20_ = self->priv->context;
#line 35 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_set_profile (_tmp20_, VALA_PROFILE_POSIX);
#line 36 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp21_ = self->priv->context;
#line 36 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				vala_code_context_add_define (_tmp21_, "POSIX");
#line 37 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				break;
#line 382 "valabindcompiler.c"
			}
		}
	}
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return self;
#line 388 "valabindcompiler.c"
}


ValabindCompiler* valabind_compiler_new (const gchar* modulename, const gchar* vapidir, const gchar* profile) {
#line 13 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return valabind_compiler_construct (TYPE_VALABIND_COMPILER, modulename, vapidir, profile);
#line 395 "valabindcompiler.c"
}


void valabind_compiler_parse (ValabindCompiler* self) {
	ValaParser* _tmp0_;
	ValaParser* parser;
	ValaParser* _tmp1_;
	ValaCodeContext* _tmp2_;
	gboolean _tmp3_ = FALSE;
#line 41 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 42 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = vala_parser_new ();
#line 42 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	parser = _tmp0_;
#line 43 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = parser;
#line 43 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = self->priv->context;
#line 43 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_parser_parse (_tmp1_, _tmp2_);
#line 44 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp3_ = valabind_compiler_init (self);
#line 44 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (!_tmp3_) {
#line 45 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_error ("valabind initialization failed");
#line 423 "valabindcompiler.c"
	}
#line 41 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (parser);
#line 427 "valabindcompiler.c"
}


gboolean valabind_compiler_init (ValabindCompiler* self) {
	gboolean result = FALSE;
	ValaCodeContext* _tmp0_;
	ValaCodeContext* _tmp1_;
	ValaReport* _tmp2_;
	ValaReport* _tmp3_;
	gint _tmp4_ = 0;
#line 48 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 50 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->context;
#line 50 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_code_context_check (_tmp0_);
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = self->priv->context;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = vala_code_context_get_report (_tmp1_);
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp3_ = _tmp2_;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp4_ = vala_report_get_errors (_tmp3_);
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = _tmp4_ == 0;
#line 65 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 456 "valabindcompiler.c"
}


gboolean valabind_compiler_add_external_package (ValabindCompiler* self, const gchar* pkg) {
	gboolean result = FALSE;
	ValaCodeContext* _tmp0_;
	const gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
#line 68 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 68 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (pkg != NULL, FALSE);
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->context;
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = pkg;
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = vala_code_context_add_external_package (_tmp0_, _tmp1_);
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = _tmp2_;
#line 69 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 479 "valabindcompiler.c"
}


static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value) {
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if ((*length) == (*size)) {
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 490 "valabindcompiler.c"
	}
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	(*array)[(*length)++] = value;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	(*array)[*length] = NULL;
#line 496 "valabindcompiler.c"
}


gboolean valabind_compiler_add_source_file (ValabindCompiler* self, const gchar* path) {
	gboolean result = FALSE;
	gchar** _tmp0_;
	gint _tmp0__length1;
	const gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	gboolean ret;
	gboolean _tmp6_;
#line 72 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 72 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (path != NULL, FALSE);
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->source_files;
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0__length1 = self->priv->source_files_length1;
#line 516 "valabindcompiler.c"
	{
		gchar** f_collection = NULL;
		gint f_collection_length1 = 0;
		gint _f_collection_size_ = 0;
		gint f_it = 0;
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		f_collection = _tmp0_;
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		f_collection_length1 = _tmp0__length1;
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		for (f_it = 0; f_it < _tmp0__length1; f_it = f_it + 1) {
#line 528 "valabindcompiler.c"
			gchar* _tmp1_;
			gchar* f = NULL;
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp1_ = g_strdup (f_collection[f_it]);
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			f = _tmp1_;
#line 535 "valabindcompiler.c"
			{
				const gchar* _tmp2_;
				const gchar* _tmp3_;
#line 74 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp2_ = path;
#line 74 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_tmp3_ = f;
#line 74 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				if (g_strcmp0 (_tmp2_, _tmp3_) == 0) {
#line 75 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
					result = FALSE;
#line 75 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
					_g_free0 (f);
#line 75 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
					return result;
#line 551 "valabindcompiler.c"
				}
#line 73 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_g_free0 (f);
#line 555 "valabindcompiler.c"
			}
		}
	}
#line 78 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp4_ = path;
#line 78 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp5_ = g_file_test (_tmp4_, G_FILE_TEST_IS_REGULAR);
#line 78 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	ret = _tmp5_;
#line 79 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_ = ret;
#line 79 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp6_) {
#line 569 "valabindcompiler.c"
		gboolean _tmp7_;
		gchar** _tmp13_;
		gint _tmp13__length1;
		const gchar* _tmp14_;
		gchar* _tmp15_;
#line 80 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_ = self->pkgmode;
#line 80 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (!_tmp7_) {
#line 579 "valabindcompiler.c"
			ValaCodeContext* _tmp8_;
			ValaCodeContext* _tmp9_;
			const gchar* _tmp10_;
			ValaSourceFile* _tmp11_;
			ValaSourceFile* _tmp12_;
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp8_ = self->priv->context;
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp9_ = self->priv->context;
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp10_ = path;
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp11_ = vala_source_file_new (_tmp9_, VALA_SOURCE_FILE_TYPE_PACKAGE, _tmp10_, NULL);
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp12_ = _tmp11_;
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			vala_code_context_add_source_file (_tmp8_, _tmp12_);
#line 82 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_vala_source_file_unref0 (_tmp12_);
#line 599 "valabindcompiler.c"
		}
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13_ = self->priv->source_files;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13__length1 = self->priv->source_files_length1;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14_ = path;
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp15_ = g_strdup (_tmp14_);
#line 87 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_vala_array_add1 (&self->priv->source_files, &self->priv->source_files_length1, &self->priv->_source_files_size_, _tmp15_);
#line 611 "valabindcompiler.c"
	} else {
		ValaCodeContext* _tmp16_;
		const gchar* _tmp17_;
		gboolean _tmp18_ = FALSE;
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp16_ = self->priv->context;
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp17_ = path;
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_ = valabind_compiler_add_package (self, _tmp16_, _tmp17_);
#line 89 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (!_tmp18_) {
#line 624 "valabindcompiler.c"
			const gchar* _tmp19_;
			gchar* _tmp20_ = NULL;
			gchar* _tmp21_;
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp19_ = path;
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp20_ = g_strdup_printf ("Cannot find '%s'.\n", _tmp19_);
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp21_ = _tmp20_;
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			valabind_compiler_error (_tmp21_);
#line 90 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (_tmp21_);
#line 638 "valabindcompiler.c"
		}
	}
#line 91 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = ret;
#line 91 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 645 "valabindcompiler.c"
}


void valabind_compiler_emit_vapi (ValabindCompiler* self, const gchar* output, const gchar* file) {
	ValaCodeWriter* _tmp0_;
	ValaCodeWriter* swig_writer;
	ValaCodeContext* _tmp1_;
	const gchar* _tmp2_;
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (file != NULL);
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = vala_code_writer_new (VALA_CODE_WRITER_TYPE_EXTERNAL);
#line 95 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	swig_writer = _tmp0_;
#line 96 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = self->priv->context;
#line 96 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = file;
#line 96 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_code_writer_write_file (swig_writer, _tmp1_, _tmp2_);
#line 94 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (swig_writer);
#line 670 "valabindcompiler.c"
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = g_new0 (gchar*, length + 1);
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	for (i = 0; i < length; i++) {
#line 681 "valabindcompiler.c"
		gchar* _tmp0_;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp0_ = g_strdup (self[i]);
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result[i] = _tmp0_;
#line 687 "valabindcompiler.c"
	}
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 691 "valabindcompiler.c"
}


void valabind_compiler_emit_gir (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include) {
	const gchar* _tmp0_;
	GirWriter* _tmp1_;
	GirWriter* gir_writer;
	GirWriter* _tmp2_;
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (file != NULL);
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->modulename;
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = gir_writer_new (_tmp0_);
#line 100 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	gir_writer = _tmp1_;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = gir_writer;
#line 101 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp2_ != NULL) {
#line 714 "valabindcompiler.c"
		GirWriter* _tmp3_;
		gboolean _tmp4_;
		GirWriter* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		GirWriter* _tmp12_;
		gchar** _tmp13_;
		gint _tmp13__length1;
		gchar** _tmp14_;
		gint _tmp14__length1;
		GirWriter* _tmp15_;
		ValaCodeContext* _tmp16_;
		const gchar* _tmp17_;
#line 103 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_ = gir_writer;
#line 103 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp4_ = self->pkgmode;
#line 103 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_->pkgmode = _tmp4_;
#line 104 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_ = gir_writer;
#line 104 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp6_ = self->pkgname;
#line 104 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_ = g_strdup (_tmp6_);
#line 104 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_g_free0 (_tmp5_->pkgname);
#line 104 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_->pkgname = _tmp7_;
#line 105 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp8_ = include;
#line 105 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (_tmp8_ != NULL) {
#line 749 "valabindcompiler.c"
			GirWriter* _tmp9_;
			const gchar* _tmp10_;
			gchar* _tmp11_;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp9_ = gir_writer;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp10_ = include;
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp11_ = g_strdup (_tmp10_);
#line 106 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp9_->includefiles = g_list_append (_tmp9_->includefiles, _tmp11_);
#line 761 "valabindcompiler.c"
		}
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_ = gir_writer;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13_ = self->priv->source_files;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13__length1 = self->priv->source_files_length1;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14_ = (_tmp13_ != NULL) ? _vala_array_dup1 (_tmp13_, _tmp13__length1) : ((gpointer) _tmp13_);
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14__length1 = _tmp13__length1;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files = (_vala_array_free (_tmp12_->files, _tmp12_->files_length1, (GDestroyNotify) g_free), NULL);
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files = _tmp14_;
#line 107 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files_length1 = _tmp14__length1;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp15_ = gir_writer;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp16_ = self->priv->context;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp17_ = file;
#line 108 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		gir_writer_write_file (_tmp15_, _tmp16_, _tmp17_);
#line 787 "valabindcompiler.c"
	} else {
#line 109 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_warning ("cannot create swig writer");
#line 791 "valabindcompiler.c"
	}
#line 99 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (gir_writer);
#line 795 "valabindcompiler.c"
}


static gchar** _vala_array_dup2 (gchar** self, int length) {
	gchar** result;
	int i;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = g_new0 (gchar*, length + 1);
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	for (i = 0; i < length; i++) {
#line 806 "valabindcompiler.c"
		gchar* _tmp0_;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp0_ = g_strdup (self[i]);
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result[i] = _tmp0_;
#line 812 "valabindcompiler.c"
	}
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 816 "valabindcompiler.c"
}


void valabind_compiler_emit_gear (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include) {
	const gchar* _tmp0_;
	GearWriter* _tmp1_;
	GearWriter* gear_writer;
	GearWriter* _tmp2_;
#line 112 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 112 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (file != NULL);
#line 113 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->modulename;
#line 113 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = gear_writer_new (_tmp0_);
#line 113 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	gear_writer = _tmp1_;
#line 114 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = gear_writer;
#line 114 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp2_ != NULL) {
#line 839 "valabindcompiler.c"
		GearWriter* _tmp3_;
		gboolean _tmp4_;
		GearWriter* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		GearWriter* _tmp12_;
		gchar** _tmp13_;
		gint _tmp13__length1;
		gchar** _tmp14_;
		gint _tmp14__length1;
		GearWriter* _tmp15_;
		ValaCodeContext* _tmp16_;
		const gchar* _tmp17_;
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_ = gear_writer;
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp4_ = self->pkgmode;
#line 116 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_->pkgmode = _tmp4_;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_ = gear_writer;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp6_ = self->pkgname;
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_ = g_strdup (_tmp6_);
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_g_free0 (_tmp5_->pkgname);
#line 117 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_->pkgname = _tmp7_;
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp8_ = include;
#line 118 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (_tmp8_ != NULL) {
#line 874 "valabindcompiler.c"
			GearWriter* _tmp9_;
			const gchar* _tmp10_;
			gchar* _tmp11_;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp9_ = gear_writer;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp10_ = include;
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp11_ = g_strdup (_tmp10_);
#line 119 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp9_->includefiles = g_list_append (_tmp9_->includefiles, _tmp11_);
#line 886 "valabindcompiler.c"
		}
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_ = gear_writer;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13_ = self->priv->source_files;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13__length1 = self->priv->source_files_length1;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14_ = (_tmp13_ != NULL) ? _vala_array_dup2 (_tmp13_, _tmp13__length1) : ((gpointer) _tmp13_);
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14__length1 = _tmp13__length1;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files = (_vala_array_free (_tmp12_->files, _tmp12_->files_length1, (GDestroyNotify) g_free), NULL);
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files = _tmp14_;
#line 120 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_->files_length1 = _tmp14__length1;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp15_ = gear_writer;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp16_ = self->priv->context;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp17_ = file;
#line 121 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		gear_writer_write_file (_tmp15_, _tmp16_, _tmp17_);
#line 912 "valabindcompiler.c"
	} else {
#line 122 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_warning ("cannot create swig writer");
#line 916 "valabindcompiler.c"
	}
#line 112 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (gear_writer);
#line 920 "valabindcompiler.c"
}


static gchar** _vala_array_dup3 (gchar** self, int length) {
	gchar** result;
	int i;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = g_new0 (gchar*, length + 1);
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	for (i = 0; i < length; i++) {
#line 931 "valabindcompiler.c"
		gchar* _tmp0_;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp0_ = g_strdup (self[i]);
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result[i] = _tmp0_;
#line 937 "valabindcompiler.c"
	}
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 941 "valabindcompiler.c"
}


void valabind_compiler_emit_cxx (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include) {
	const gchar* _tmp0_;
	CxxWriter* _tmp1_;
	CxxWriter* cxx_writer;
	CxxWriter* _tmp2_;
#line 125 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 125 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (file != NULL);
#line 126 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->modulename;
#line 126 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = cxx_writer_new (_tmp0_);
#line 126 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	cxx_writer = _tmp1_;
#line 127 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = cxx_writer;
#line 127 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp2_ != NULL) {
#line 964 "valabindcompiler.c"
		CxxWriter* _tmp3_;
		gboolean _tmp4_;
		CxxWriter* _tmp5_;
		gboolean _tmp6_;
		CxxWriter* _tmp7_;
		gboolean _tmp8_;
		CxxWriter* _tmp9_;
		gboolean _tmp10_;
		CxxWriter* _tmp11_;
		const gchar* _tmp12_;
		gchar* _tmp13_;
		const gchar* _tmp14_;
		CxxWriter* _tmp18_;
		gchar** _tmp19_;
		gint _tmp19__length1;
		gchar** _tmp20_;
		gint _tmp20__length1;
		CxxWriter* _tmp21_;
		ValaCodeContext* _tmp22_;
		const gchar* _tmp23_;
#line 129 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_ = cxx_writer;
#line 129 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp4_ = show_externs;
#line 129 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_->show_externs = _tmp4_;
#line 130 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_ = cxx_writer;
#line 130 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp6_ = glibmode;
#line 130 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_->glib_mode = _tmp6_;
#line 131 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_ = cxx_writer;
#line 131 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp8_ = cxxmode;
#line 131 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_->cxx_mode = _tmp8_;
#line 132 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp9_ = cxx_writer;
#line 132 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp10_ = self->pkgmode;
#line 132 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp9_->pkgmode = _tmp10_;
#line 133 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp11_ = cxx_writer;
#line 133 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_ = self->pkgname;
#line 133 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13_ = g_strdup (_tmp12_);
#line 133 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_g_free0 (_tmp11_->pkgname);
#line 133 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp11_->pkgname = _tmp13_;
#line 134 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14_ = include;
#line 134 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (_tmp14_ != NULL) {
#line 1023 "valabindcompiler.c"
			CxxWriter* _tmp15_;
			const gchar* _tmp16_;
			gchar* _tmp17_;
#line 135 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp15_ = cxx_writer;
#line 135 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp16_ = include;
#line 135 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp17_ = g_strdup (_tmp16_);
#line 135 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp15_->includefiles = g_list_append (_tmp15_->includefiles, _tmp17_);
#line 1035 "valabindcompiler.c"
		}
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_ = cxx_writer;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp19_ = self->priv->source_files;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp19__length1 = self->priv->source_files_length1;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp20_ = (_tmp19_ != NULL) ? _vala_array_dup3 (_tmp19_, _tmp19__length1) : ((gpointer) _tmp19_);
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp20__length1 = _tmp19__length1;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files = (_vala_array_free (_tmp18_->files, _tmp18_->files_length1, (GDestroyNotify) g_free), NULL);
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files = _tmp20_;
#line 136 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files_length1 = _tmp20__length1;
#line 137 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp21_ = cxx_writer;
#line 137 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp22_ = self->priv->context;
#line 137 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp23_ = file;
#line 137 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		cxx_writer_write_file (_tmp21_, _tmp22_, _tmp23_);
#line 1061 "valabindcompiler.c"
	} else {
#line 138 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_warning ("cannot create swig writer");
#line 1065 "valabindcompiler.c"
	}
#line 125 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (cxx_writer);
#line 1069 "valabindcompiler.c"
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = g_new0 (gchar*, length + 1);
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	for (i = 0; i < length; i++) {
#line 1080 "valabindcompiler.c"
		gchar* _tmp0_;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp0_ = g_strdup (self[i]);
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result[i] = _tmp0_;
#line 1086 "valabindcompiler.c"
	}
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 1090 "valabindcompiler.c"
}


void valabind_compiler_emit_swig (ValabindCompiler* self, const gchar* file, gboolean show_externs, gboolean glibmode, gboolean cxxmode, const gchar* include) {
	const gchar* _tmp0_;
	SwigWriter* _tmp1_;
	SwigWriter* swig_writer;
	SwigWriter* _tmp2_;
#line 141 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (self != NULL);
#line 141 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (file != NULL);
#line 142 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = self->priv->modulename;
#line 142 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = swig_writer_new (_tmp0_);
#line 142 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	swig_writer = _tmp1_;
#line 143 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = swig_writer;
#line 143 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp2_ != NULL) {
#line 1113 "valabindcompiler.c"
		SwigWriter* _tmp3_;
		gboolean _tmp4_;
		SwigWriter* _tmp5_;
		gboolean _tmp6_;
		SwigWriter* _tmp7_;
		gboolean _tmp8_;
		SwigWriter* _tmp9_;
		gboolean _tmp10_;
		SwigWriter* _tmp11_;
		const gchar* _tmp12_;
		gchar* _tmp13_;
		const gchar* _tmp14_;
		SwigWriter* _tmp18_;
		gchar** _tmp19_;
		gint _tmp19__length1;
		gchar** _tmp20_;
		gint _tmp20__length1;
		SwigWriter* _tmp21_;
		ValaCodeContext* _tmp22_;
		const gchar* _tmp23_;
#line 145 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_ = swig_writer;
#line 145 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp4_ = show_externs;
#line 145 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp3_->show_externs = _tmp4_;
#line 146 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_ = swig_writer;
#line 146 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp6_ = glibmode;
#line 146 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp5_->glib_mode = _tmp6_;
#line 147 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_ = swig_writer;
#line 147 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp8_ = cxxmode;
#line 147 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp7_->cxx_mode = _tmp8_;
#line 148 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp9_ = swig_writer;
#line 148 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp10_ = self->pkgmode;
#line 148 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp9_->pkgmode = _tmp10_;
#line 149 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp11_ = swig_writer;
#line 149 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp12_ = self->pkgname;
#line 149 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp13_ = g_strdup (_tmp12_);
#line 149 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_g_free0 (_tmp11_->pkgname);
#line 149 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp11_->pkgname = _tmp13_;
#line 150 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp14_ = include;
#line 150 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (_tmp14_ != NULL) {
#line 1172 "valabindcompiler.c"
			SwigWriter* _tmp15_;
			const gchar* _tmp16_;
			gchar* _tmp17_;
#line 151 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp15_ = swig_writer;
#line 151 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp16_ = include;
#line 151 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp17_ = g_strdup (_tmp16_);
#line 151 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp15_->includefiles = g_list_append (_tmp15_->includefiles, _tmp17_);
#line 1184 "valabindcompiler.c"
		}
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_ = swig_writer;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp19_ = self->priv->source_files;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp19__length1 = self->priv->source_files_length1;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp20_ = (_tmp19_ != NULL) ? _vala_array_dup4 (_tmp19_, _tmp19__length1) : ((gpointer) _tmp19_);
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp20__length1 = _tmp19__length1;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files = (_vala_array_free (_tmp18_->files, _tmp18_->files_length1, (GDestroyNotify) g_free), NULL);
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files = _tmp20_;
#line 152 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp18_->files_length1 = _tmp20__length1;
#line 153 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp21_ = swig_writer;
#line 153 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp22_ = self->priv->context;
#line 153 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp23_ = file;
#line 153 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		swig_writer_write_file (_tmp21_, _tmp22_, _tmp23_);
#line 1210 "valabindcompiler.c"
	} else {
#line 154 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_warning ("cannot create swig writer");
#line 1214 "valabindcompiler.c"
	}
#line 141 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_visitor_unref0 (swig_writer);
#line 1218 "valabindcompiler.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _result_;
	const gchar* _tmp1_;
#line 1229 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1230 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1230 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1231 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1231 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1232 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	result = _result_;
#line 1232 "/usr/share/vala-0.16/vapi/glib-2.0.vapi"
	return result;
#line 1241 "valabindcompiler.c"
}


static gboolean valabind_compiler_add_package (ValabindCompiler* self, ValaCodeContext* context, const gchar* pkg) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	ValaCodeContext* _tmp1_;
	const gchar* _tmp2_;
	gboolean _tmp3_ = FALSE;
	ValaCodeContext* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* package_path;
	const gchar* _tmp7_;
	gboolean _tmp10_;
	ValaCodeContext* _tmp12_;
	ValaCodeContext* _tmp13_;
	const gchar* _tmp14_;
	ValaSourceFile* _tmp15_;
	ValaSourceFile* _tmp16_;
	ValaCodeContext* _tmp17_;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_;
	gchar* deps_filename;
	const gchar* _tmp27_;
	gboolean _tmp28_ = FALSE;
	GError * _inner_error_ = NULL;
#line 158 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 158 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (context != NULL, FALSE);
#line 158 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (pkg != NULL, FALSE);
#line 159 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = pkg;
#line 159 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_print ("Adding dependency package %s\n", _tmp0_);
#line 162 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = context;
#line 162 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp2_ = pkg;
#line 162 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp3_ = vala_code_context_has_package (_tmp1_, _tmp2_);
#line 162 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp3_) {
#line 163 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result = TRUE;
#line 163 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		return result;
#line 1298 "valabindcompiler.c"
	}
#line 166 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp4_ = context;
#line 166 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp5_ = pkg;
#line 166 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp6_ = vala_code_context_get_vapi_path (_tmp4_, _tmp5_);
#line 166 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	package_path = _tmp6_;
#line 171 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp7_ = package_path;
#line 171 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp7_ == NULL) {
#line 1312 "valabindcompiler.c"
		FILE* _tmp8_;
		const gchar* _tmp9_;
#line 172 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp8_ = stderr;
#line 172 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp9_ = pkg;
#line 172 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		fprintf (_tmp8_, "Cannot find package path '%s'", _tmp9_);
#line 173 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		result = FALSE;
#line 173 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_g_free0 (package_path);
#line 173 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		return result;
#line 1327 "valabindcompiler.c"
	}
#line 176 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp10_ = self->pkgmode;
#line 176 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp10_) {
#line 1333 "valabindcompiler.c"
		const gchar* _tmp11_;
#line 177 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		_tmp11_ = package_path;
#line 177 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_add_source_file (self, _tmp11_);
#line 1339 "valabindcompiler.c"
	}
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp12_ = context;
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp13_ = context;
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp14_ = package_path;
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp15_ = vala_source_file_new (_tmp13_, VALA_SOURCE_FILE_TYPE_PACKAGE, _tmp14_, NULL);
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp16_ = _tmp15_;
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_code_context_add_source_file (_tmp12_, _tmp16_);
#line 179 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_source_file_unref0 (_tmp16_);
#line 183 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp17_ = context;
#line 183 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp18_ = pkg;
#line 183 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	vala_code_context_add_package (_tmp17_, _tmp18_);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp19_ = package_path;
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp20_ = g_path_get_dirname (_tmp19_);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp21_ = _tmp20_;
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp22_ = pkg;
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp23_ = g_strdup_printf ("%s.deps", _tmp22_);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp24_ = _tmp23_;
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp25_ = g_build_filename (_tmp21_, _tmp24_, NULL);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp26_ = _tmp25_;
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (_tmp24_);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (_tmp21_);
#line 185 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	deps_filename = _tmp26_;
#line 186 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp27_ = deps_filename;
#line 186 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp28_ = g_file_test (_tmp27_, G_FILE_TEST_EXISTS);
#line 186 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (_tmp28_) {
#line 1389 "valabindcompiler.c"
		{
			gchar* deps_content = NULL;
			gsize deps_len = 0UL;
			const gchar* _tmp29_;
			gchar* _tmp30_ = NULL;
			gsize _tmp31_ = 0UL;
			const gchar* _tmp32_;
			gchar** _tmp33_;
			gchar** _tmp34_ = NULL;
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp29_ = deps_filename;
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			g_file_get_contents (_tmp29_, &_tmp30_, &_tmp31_, &_inner_error_);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (deps_content);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			deps_content = _tmp30_;
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			deps_len = _tmp31_;
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			if (_inner_error_ != NULL) {
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_g_free0 (deps_content);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				if (_inner_error_->domain == G_FILE_ERROR) {
#line 1415 "valabindcompiler.c"
					goto __catch1_g_file_error;
				}
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_g_free0 (deps_content);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_g_free0 (deps_filename);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				_g_free0 (package_path);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				g_clear_error (&_inner_error_);
#line 191 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				return FALSE;
#line 1430 "valabindcompiler.c"
			}
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp32_ = deps_content;
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp34_ = _tmp33_ = g_strsplit (_tmp32_, "\n", 0);
#line 1436 "valabindcompiler.c"
			{
				gchar** dep_collection = NULL;
				gint dep_collection_length1 = 0;
				gint _dep_collection_size_ = 0;
				gint dep_it = 0;
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				dep_collection = _tmp34_;
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				dep_collection_length1 = _vala_array_length (_tmp33_);
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				for (dep_it = 0; dep_it < _vala_array_length (_tmp33_); dep_it = dep_it + 1) {
#line 1448 "valabindcompiler.c"
					gchar* _tmp35_;
					gchar* dep = NULL;
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
					_tmp35_ = g_strdup (dep_collection[dep_it]);
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
					dep = _tmp35_;
#line 1455 "valabindcompiler.c"
					{
						const gchar* _tmp36_;
						gchar* _tmp37_ = NULL;
						const gchar* _tmp38_;
#line 193 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						_tmp36_ = dep;
#line 193 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						_tmp37_ = string_strip (_tmp36_);
#line 193 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						_g_free0 (dep);
#line 193 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						dep = _tmp37_;
#line 194 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						_tmp38_ = dep;
#line 194 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						if (g_strcmp0 (_tmp38_, "") != 0) {
#line 1472 "valabindcompiler.c"
							ValaCodeContext* _tmp39_;
							const gchar* _tmp40_;
							gboolean _tmp41_ = FALSE;
#line 195 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
							_tmp39_ = context;
#line 195 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
							_tmp40_ = dep;
#line 195 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
							_tmp41_ = valabind_compiler_add_package (self, _tmp39_, _tmp40_);
#line 195 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
							if (!_tmp41_) {
#line 1484 "valabindcompiler.c"
								const gchar* _tmp42_;
								const gchar* _tmp43_;
								gchar* _tmp44_ = NULL;
								gchar* _tmp45_;
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								_tmp42_ = dep;
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								_tmp43_ = pkg;
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								_tmp44_ = g_strdup_printf ("%s, dependency of %s, not found in specified Vala API directories", _tmp42_, _tmp43_);
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								_tmp45_ = _tmp44_;
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								vala_report_error (NULL, _tmp45_);
#line 196 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
								_g_free0 (_tmp45_);
#line 1501 "valabindcompiler.c"
							}
						}
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
						_g_free0 (dep);
#line 1506 "valabindcompiler.c"
					}
				}
#line 192 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
				dep_collection = (_vala_array_free (dep_collection, dep_collection_length1, (GDestroyNotify) g_free), NULL);
#line 1511 "valabindcompiler.c"
			}
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (deps_content);
#line 1515 "valabindcompiler.c"
		}
		goto __finally1;
		__catch1_g_file_error:
		{
			GError* e = NULL;
			GError* _tmp46_;
			const gchar* _tmp47_;
			gchar* _tmp48_ = NULL;
			gchar* _tmp49_;
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			e = _inner_error_;
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_inner_error_ = NULL;
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp46_ = e;
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp47_ = _tmp46_->message;
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp48_ = g_strdup_printf ("Unable to read dependency file: %s", _tmp47_);
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_tmp49_ = _tmp48_;
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			vala_report_error (NULL, _tmp49_);
#line 200 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (_tmp49_);
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_error_free0 (e);
#line 1543 "valabindcompiler.c"
		}
		__finally1:
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (_inner_error_ != NULL) {
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (deps_filename);
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			_g_free0 (package_path);
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			g_clear_error (&_inner_error_);
#line 187 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			return FALSE;
#line 1558 "valabindcompiler.c"
		}
	}
#line 204 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	result = TRUE;
#line 204 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (deps_filename);
#line 204 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (package_path);
#line 204 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return result;
#line 1569 "valabindcompiler.c"
}


void valabind_compiler_error (const gchar* msg) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
#line 207 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (msg != NULL);
#line 208 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = stderr;
#line 208 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = msg;
#line 208 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	fprintf (_tmp0_, "\x1b[31mERROR:\x1b[0m %s\n", _tmp1_);
#line 209 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	exit (1);
#line 1586 "valabindcompiler.c"
}


void valabind_compiler_warning (const gchar* msg) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
#line 212 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (msg != NULL);
#line 213 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp0_ = stderr;
#line 213 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_tmp1_ = msg;
#line 213 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	fprintf (_tmp0_, "\x1b[33mWARNING:\x1b[0m %s\n", _tmp1_);
#line 1601 "valabindcompiler.c"
}


static void value_valabind_compiler_init (GValue* value) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	value->data[0].v_pointer = NULL;
#line 1608 "valabindcompiler.c"
}


static void value_valabind_compiler_free_value (GValue* value) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (value->data[0].v_pointer) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_unref (value->data[0].v_pointer);
#line 1617 "valabindcompiler.c"
	}
}


static void value_valabind_compiler_copy_value (const GValue* src_value, GValue* dest_value) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (src_value->data[0].v_pointer) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		dest_value->data[0].v_pointer = valabind_compiler_ref (src_value->data[0].v_pointer);
#line 1627 "valabindcompiler.c"
	} else {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1631 "valabindcompiler.c"
	}
}


static gpointer value_valabind_compiler_peek_pointer (const GValue* value) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return value->data[0].v_pointer;
#line 1639 "valabindcompiler.c"
}


static gchar* value_valabind_compiler_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (collect_values[0].v_pointer) {
#line 1646 "valabindcompiler.c"
		ValabindCompiler* object;
		object = collect_values[0].v_pointer;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		if (object->parent_instance.g_class == NULL) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1653 "valabindcompiler.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1657 "valabindcompiler.c"
		}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = valabind_compiler_ref (object);
#line 1661 "valabindcompiler.c"
	} else {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = NULL;
#line 1665 "valabindcompiler.c"
	}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return NULL;
#line 1669 "valabindcompiler.c"
}


static gchar* value_valabind_compiler_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ValabindCompiler** object_p;
	object_p = collect_values[0].v_pointer;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (!object_p) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1680 "valabindcompiler.c"
	}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (!value->data[0].v_pointer) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		*object_p = NULL;
#line 1686 "valabindcompiler.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		*object_p = value->data[0].v_pointer;
#line 1690 "valabindcompiler.c"
	} else {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		*object_p = valabind_compiler_ref (value->data[0].v_pointer);
#line 1694 "valabindcompiler.c"
	}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return NULL;
#line 1698 "valabindcompiler.c"
}


GParamSpec* param_spec_valabind_compiler (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecValabindCompiler* spec;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_VALABIND_COMPILER), NULL);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return G_PARAM_SPEC (spec);
#line 1712 "valabindcompiler.c"
}


gpointer value_get_valabind_compiler (const GValue* value) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_VALABIND_COMPILER), NULL);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return value->data[0].v_pointer;
#line 1721 "valabindcompiler.c"
}


void value_set_valabind_compiler (GValue* value, gpointer v_object) {
	ValabindCompiler* old;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_VALABIND_COMPILER));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	old = value->data[0].v_pointer;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (v_object) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_VALABIND_COMPILER));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = v_object;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_ref (value->data[0].v_pointer);
#line 1741 "valabindcompiler.c"
	} else {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = NULL;
#line 1745 "valabindcompiler.c"
	}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (old) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_unref (old);
#line 1751 "valabindcompiler.c"
	}
}


void value_take_valabind_compiler (GValue* value, gpointer v_object) {
	ValabindCompiler* old;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_VALABIND_COMPILER));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	old = value->data[0].v_pointer;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (v_object) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_VALABIND_COMPILER));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = v_object;
#line 1770 "valabindcompiler.c"
	} else {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		value->data[0].v_pointer = NULL;
#line 1774 "valabindcompiler.c"
	}
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (old) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		valabind_compiler_unref (old);
#line 1780 "valabindcompiler.c"
	}
}


static void valabind_compiler_class_init (ValabindCompilerClass * klass) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	valabind_compiler_parent_class = g_type_class_peek_parent (klass);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	VALABIND_COMPILER_CLASS (klass)->finalize = valabind_compiler_finalize;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_type_class_add_private (klass, sizeof (ValabindCompilerPrivate));
#line 1792 "valabindcompiler.c"
}


static void valabind_compiler_instance_init (ValabindCompiler * self) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv = VALABIND_COMPILER_GET_PRIVATE (self);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->ref_count = 1;
#line 1801 "valabindcompiler.c"
}


static void valabind_compiler_finalize (ValabindCompiler* obj) {
	ValabindCompiler * self;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self = VALABIND_COMPILER (obj);
#line 6 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (self->priv->vapidir);
#line 7 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (self->priv->modulename);
#line 8 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_vala_code_context_unref0 (self->priv->context);
#line 10 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	_g_free0 (self->pkgname);
#line 11 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	self->priv->source_files = (_vala_array_free (self->priv->source_files, self->priv->source_files_length1, (GDestroyNotify) g_free), NULL);
#line 1819 "valabindcompiler.c"
}


GType valabind_compiler_get_type (void) {
	static volatile gsize valabind_compiler_type_id__volatile = 0;
	if (g_once_init_enter (&valabind_compiler_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_valabind_compiler_init, value_valabind_compiler_free_value, value_valabind_compiler_copy_value, value_valabind_compiler_peek_pointer, "p", value_valabind_compiler_collect_value, "p", value_valabind_compiler_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValabindCompilerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valabind_compiler_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValabindCompiler), 0, (GInstanceInitFunc) valabind_compiler_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType valabind_compiler_type_id;
		valabind_compiler_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValabindCompiler", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&valabind_compiler_type_id__volatile, valabind_compiler_type_id);
	}
	return valabind_compiler_type_id__volatile;
}


gpointer valabind_compiler_ref (gpointer instance) {
	ValabindCompiler* self;
	self = instance;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	g_atomic_int_inc (&self->ref_count);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	return instance;
#line 1844 "valabindcompiler.c"
}


void valabind_compiler_unref (gpointer instance) {
	ValabindCompiler* self;
	self = instance;
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		VALABIND_COMPILER_GET_CLASS (self)->finalize (self);
#line 5 "/Users/pancake/prg/valabind/valabind-0.5.1/valabindcompiler.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1857 "valabindcompiler.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



